java -jar D:\work\JavaContent\others\tango-icon-theme-0.7.1\batik-1.6\batik-rasterizer.jar -m image/jpeg -d d:\work\JavaContent\others\tango-icon-theme-0.7.1\output-48x48\actions -w 48 -h 48 D:\work\JavaContent\others\tango-icon-theme-0.7.1\scalable\actions
java -jar D:\work\JavaContent\others\tango-icon-theme-0.7.1\batik-1.6\batik-rasterizer.jar -m image/jpeg -d d:\work\JavaContent\others\tango-icon-theme-0.7.1\output-48x48\animations -w 48 -h 48 D:\work\JavaContent\others\tango-icon-theme-0.7.1\scalable\animations
java -jar D:\work\JavaContent\others\tango-icon-theme-0.7.1\batik-1.6\batik-rasterizer.jar -m image/jpeg -d d:\work\JavaContent\others\tango-icon-theme-0.7.1\output-48x48\apps -w 48 -h 48 D:\work\JavaContent\others\tango-icon-theme-0.7.1\scalable\apps
java -jar D:\work\JavaContent\others\tango-icon-theme-0.7.1\batik-1.6\batik-rasterizer.jar -m image/jpeg -d d:\work\JavaContent\others\tango-icon-theme-0.7.1\output-48x48\categories -w 48 -h 48 D:\work\JavaContent\others\tango-icon-theme-0.7.1\scalable\categories
java -jar D:\work\JavaContent\others\tango-icon-theme-0.7.1\batik-1.6\batik-rasterizer.jar -m image/jpeg -d d:\work\JavaContent\others\tango-icon-theme-0.7.1\output-48x48\devices -w 48 -h 48 D:\work\JavaContent\others\tango-icon-theme-0.7.1\scalable\devices
java -jar D:\work\JavaContent\others\tango-icon-theme-0.7.1\batik-1.6\batik-rasterizer.jar -m image/jpeg -d d:\work\JavaContent\others\tango-icon-theme-0.7.1\output-48x48\emblems -w 48 -h 48 D:\work\JavaContent\others\tango-icon-theme-0.7.1\scalable\emblems
java -jar D:\work\JavaContent\others\tango-icon-theme-0.7.1\batik-1.6\batik-rasterizer.jar -m image/jpeg -d d:\work\JavaContent\others\tango-icon-theme-0.7.1\output-48x48\emotes -w 48 -h 48 D:\work\JavaContent\others\tango-icon-theme-0.7.1\scalable\emotes
java -jar D:\work\JavaContent\others\tango-icon-theme-0.7.1\batik-1.6\batik-rasterizer.jar -m image/jpeg -d d:\work\JavaContent\others\tango-icon-theme-0.7.1\output-48x48\mimetypes -w 48 -h 48 D:\work\JavaContent\others\tango-icon-theme-0.7.1\scalable\mimetypes
java -jar D:\work\JavaContent\others\tango-icon-theme-0.7.1\batik-1.6\batik-rasterizer.jar -m image/jpeg -d d:\work\JavaContent\others\tango-icon-theme-0.7.1\output-48x48\places -w 48 -h 48 D:\work\JavaContent\others\tango-icon-theme-0.7.1\scalable\places
java -jar D:\work\JavaContent\others\tango-icon-theme-0.7.1\batik-1.6\batik-rasterizer.jar -m image/jpeg -d d:\work\JavaContent\others\tango-icon-theme-0.7.1\output-48x48\status -w 48 -h 48 D:\work\JavaContent\others\tango-icon-theme-0.7.1\scalable\status

