
package org.tempuri;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import com.microsoft.schemas._2003._10.serialization.arrays.ArrayOfint;
import com.microsoft.schemas._2003._10.serialization.arrays.ArrayOfstring;
import org.datacontract.schemas._2004._07.microsoft_mt_web_service.ArrayOfGetTranslationsResponse;
import org.datacontract.schemas._2004._07.microsoft_mt_web_service.ArrayOfTranslateArrayResponse;
import org.datacontract.schemas._2004._07.microsoft_mt_web_service.ArrayOfTranslation;
import org.datacontract.schemas._2004._07.microsoft_mt_web_service.GetTranslationsResponse;
import org.datacontract.schemas._2004._07.microsoft_mt_web_service.TranslateOptions;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "LanguageService", targetNamespace = "http://api.microsofttranslator.com/V2")
@XmlSeeAlso({
    org.datacontract.schemas._2004._07.microsoft_mt_web_service.ObjectFactory.class,
    com.microsoft.schemas._2003._10.serialization.arrays.ObjectFactory.class,
    com.microsofttranslator.api.v2.ObjectFactory.class,
    com.microsoft.schemas._2003._10.serialization.ObjectFactory.class
})
public interface LanguageService {


    /**
     * 
     * @param to
     * @param category
     * @param appId
     * @param originalText
     * @param contentType
     * @param rating
     * @param from
     * @param translatedText
     * @param uri
     * @param user
     */
    @WebMethod(operationName = "AddTranslation", action = "http://api.microsofttranslator.com/V2/LanguageService/AddTranslation")
    @RequestWrapper(localName = "AddTranslation", targetNamespace = "http://api.microsofttranslator.com/V2", className = "com.microsofttranslator.api.v2.AddTranslation")
    @ResponseWrapper(localName = "AddTranslationResponse", targetNamespace = "http://api.microsofttranslator.com/V2", className = "com.microsofttranslator.api.v2.AddTranslationResponse")
    public void addTranslation(
        @WebParam(name = "appId", targetNamespace = "http://api.microsofttranslator.com/V2")
        String appId,
        @WebParam(name = "originalText", targetNamespace = "http://api.microsofttranslator.com/V2")
        String originalText,
        @WebParam(name = "translatedText", targetNamespace = "http://api.microsofttranslator.com/V2")
        String translatedText,
        @WebParam(name = "from", targetNamespace = "http://api.microsofttranslator.com/V2")
        String from,
        @WebParam(name = "to", targetNamespace = "http://api.microsofttranslator.com/V2")
        String to,
        @WebParam(name = "rating", targetNamespace = "http://api.microsofttranslator.com/V2")
        Integer rating,
        @WebParam(name = "contentType", targetNamespace = "http://api.microsofttranslator.com/V2")
        String contentType,
        @WebParam(name = "category", targetNamespace = "http://api.microsofttranslator.com/V2")
        String category,
        @WebParam(name = "user", targetNamespace = "http://api.microsofttranslator.com/V2")
        String user,
        @WebParam(name = "uri", targetNamespace = "http://api.microsofttranslator.com/V2")
        String uri);

    /**
     * 
     * @param text
     * @param appId
     * @param language
     * @return
     *     returns com.microsoft.schemas._2003._10.serialization.arrays.ArrayOfint
     */
    @WebMethod(operationName = "BreakSentences", action = "http://api.microsofttranslator.com/V2/LanguageService/BreakSentences")
    @WebResult(name = "BreakSentencesResult", targetNamespace = "http://api.microsofttranslator.com/V2")
    @RequestWrapper(localName = "BreakSentences", targetNamespace = "http://api.microsofttranslator.com/V2", className = "com.microsofttranslator.api.v2.BreakSentences")
    @ResponseWrapper(localName = "BreakSentencesResponse", targetNamespace = "http://api.microsofttranslator.com/V2", className = "com.microsofttranslator.api.v2.BreakSentencesResponse")
    public ArrayOfint breakSentences(
        @WebParam(name = "appId", targetNamespace = "http://api.microsofttranslator.com/V2")
        String appId,
        @WebParam(name = "text", targetNamespace = "http://api.microsofttranslator.com/V2")
        String text,
        @WebParam(name = "language", targetNamespace = "http://api.microsofttranslator.com/V2")
        String language);

    /**
     * 
     * @param text
     * @param appId
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "Detect", action = "http://api.microsofttranslator.com/V2/LanguageService/Detect")
    @WebResult(name = "DetectResult", targetNamespace = "http://api.microsofttranslator.com/V2")
    @RequestWrapper(localName = "Detect", targetNamespace = "http://api.microsofttranslator.com/V2", className = "com.microsofttranslator.api.v2.Detect")
    @ResponseWrapper(localName = "DetectResponse", targetNamespace = "http://api.microsofttranslator.com/V2", className = "com.microsofttranslator.api.v2.DetectResponse")
    public String detect(
        @WebParam(name = "appId", targetNamespace = "http://api.microsofttranslator.com/V2")
        String appId,
        @WebParam(name = "text", targetNamespace = "http://api.microsofttranslator.com/V2")
        String text);

    /**
     * 
     * @param texts
     * @param appId
     * @return
     *     returns com.microsoft.schemas._2003._10.serialization.arrays.ArrayOfstring
     */
    @WebMethod(operationName = "DetectArray", action = "http://api.microsofttranslator.com/V2/LanguageService/DetectArray")
    @WebResult(name = "DetectArrayResult", targetNamespace = "http://api.microsofttranslator.com/V2")
    @RequestWrapper(localName = "DetectArray", targetNamespace = "http://api.microsofttranslator.com/V2", className = "com.microsofttranslator.api.v2.DetectArray")
    @ResponseWrapper(localName = "DetectArrayResponse", targetNamespace = "http://api.microsofttranslator.com/V2", className = "com.microsofttranslator.api.v2.DetectArrayResponse")
    public ArrayOfstring detectArray(
        @WebParam(name = "appId", targetNamespace = "http://api.microsofttranslator.com/V2")
        String appId,
        @WebParam(name = "texts", targetNamespace = "http://api.microsofttranslator.com/V2")
        ArrayOfstring texts);

    /**
     * 
     * @param appId
     * @param expireSeconds
     * @param maxRatingWrite
     * @param minRatingRead
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetAppIdToken", action = "http://api.microsofttranslator.com/V2/LanguageService/GetAppIdToken")
    @WebResult(name = "GetAppIdTokenResult", targetNamespace = "http://api.microsofttranslator.com/V2")
    @RequestWrapper(localName = "GetAppIdToken", targetNamespace = "http://api.microsofttranslator.com/V2", className = "com.microsofttranslator.api.v2.GetAppIdToken")
    @ResponseWrapper(localName = "GetAppIdTokenResponse", targetNamespace = "http://api.microsofttranslator.com/V2", className = "com.microsofttranslator.api.v2.GetAppIdTokenResponse")
    public String getAppIdToken(
        @WebParam(name = "appId", targetNamespace = "http://api.microsofttranslator.com/V2")
        String appId,
        @WebParam(name = "minRatingRead", targetNamespace = "http://api.microsofttranslator.com/V2")
        Integer minRatingRead,
        @WebParam(name = "maxRatingWrite", targetNamespace = "http://api.microsofttranslator.com/V2")
        Integer maxRatingWrite,
        @WebParam(name = "expireSeconds", targetNamespace = "http://api.microsofttranslator.com/V2")
        Integer expireSeconds);

    /**
     * 
     * @param appId
     * @param locale
     * @param languageCodes
     * @return
     *     returns com.microsoft.schemas._2003._10.serialization.arrays.ArrayOfstring
     */
    @WebMethod(operationName = "GetLanguageNames", action = "http://api.microsofttranslator.com/V2/LanguageService/GetLanguageNames")
    @WebResult(name = "GetLanguageNamesResult", targetNamespace = "http://api.microsofttranslator.com/V2")
    @RequestWrapper(localName = "GetLanguageNames", targetNamespace = "http://api.microsofttranslator.com/V2", className = "com.microsofttranslator.api.v2.GetLanguageNames")
    @ResponseWrapper(localName = "GetLanguageNamesResponse", targetNamespace = "http://api.microsofttranslator.com/V2", className = "com.microsofttranslator.api.v2.GetLanguageNamesResponse")
    public ArrayOfstring getLanguageNames(
        @WebParam(name = "appId", targetNamespace = "http://api.microsofttranslator.com/V2")
        String appId,
        @WebParam(name = "locale", targetNamespace = "http://api.microsofttranslator.com/V2")
        String locale,
        @WebParam(name = "languageCodes", targetNamespace = "http://api.microsofttranslator.com/V2")
        ArrayOfstring languageCodes);

    /**
     * 
     * @param appId
     * @return
     *     returns com.microsoft.schemas._2003._10.serialization.arrays.ArrayOfstring
     */
    @WebMethod(operationName = "GetLanguagesForSpeak", action = "http://api.microsofttranslator.com/V2/LanguageService/GetLanguagesForSpeak")
    @WebResult(name = "GetLanguagesForSpeakResult", targetNamespace = "http://api.microsofttranslator.com/V2")
    @RequestWrapper(localName = "GetLanguagesForSpeak", targetNamespace = "http://api.microsofttranslator.com/V2", className = "com.microsofttranslator.api.v2.GetLanguagesForSpeak")
    @ResponseWrapper(localName = "GetLanguagesForSpeakResponse", targetNamespace = "http://api.microsofttranslator.com/V2", className = "com.microsofttranslator.api.v2.GetLanguagesForSpeakResponse")
    public ArrayOfstring getLanguagesForSpeak(
        @WebParam(name = "appId", targetNamespace = "http://api.microsofttranslator.com/V2")
        String appId);

    /**
     * 
     * @param appId
     * @return
     *     returns com.microsoft.schemas._2003._10.serialization.arrays.ArrayOfstring
     */
    @WebMethod(operationName = "GetLanguagesForTranslate", action = "http://api.microsofttranslator.com/V2/LanguageService/GetLanguagesForTranslate")
    @WebResult(name = "GetLanguagesForTranslateResult", targetNamespace = "http://api.microsofttranslator.com/V2")
    @RequestWrapper(localName = "GetLanguagesForTranslate", targetNamespace = "http://api.microsofttranslator.com/V2", className = "com.microsofttranslator.api.v2.GetLanguagesForTranslate")
    @ResponseWrapper(localName = "GetLanguagesForTranslateResponse", targetNamespace = "http://api.microsofttranslator.com/V2", className = "com.microsofttranslator.api.v2.GetLanguagesForTranslateResponse")
    public ArrayOfstring getLanguagesForTranslate(
        @WebParam(name = "appId", targetNamespace = "http://api.microsofttranslator.com/V2")
        String appId);

    /**
     * 
     * @param to
     * @param text
     * @param appId
     * @param from
     * @param options
     * @param maxTranslations
     * @return
     *     returns org.datacontract.schemas._2004._07.microsoft_mt_web_service.GetTranslationsResponse
     */
    @WebMethod(operationName = "GetTranslations", action = "http://api.microsofttranslator.com/V2/LanguageService/GetTranslations")
    @WebResult(name = "GetTranslationsResult", targetNamespace = "http://api.microsofttranslator.com/V2")
    @RequestWrapper(localName = "GetTranslations", targetNamespace = "http://api.microsofttranslator.com/V2", className = "com.microsofttranslator.api.v2.GetTranslations")
    @ResponseWrapper(localName = "GetTranslationsResponse", targetNamespace = "http://api.microsofttranslator.com/V2", className = "com.microsofttranslator.api.v2.GetTranslationsResponse")
    public GetTranslationsResponse getTranslations(
        @WebParam(name = "appId", targetNamespace = "http://api.microsofttranslator.com/V2")
        String appId,
        @WebParam(name = "text", targetNamespace = "http://api.microsofttranslator.com/V2")
        String text,
        @WebParam(name = "from", targetNamespace = "http://api.microsofttranslator.com/V2")
        String from,
        @WebParam(name = "to", targetNamespace = "http://api.microsofttranslator.com/V2")
        String to,
        @WebParam(name = "maxTranslations", targetNamespace = "http://api.microsofttranslator.com/V2")
        Integer maxTranslations,
        @WebParam(name = "options", targetNamespace = "http://api.microsofttranslator.com/V2")
        TranslateOptions options);

    /**
     * 
     * @param to
     * @param category
     * @param text
     * @param appId
     * @param contentType
     * @param from
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "Translate", action = "http://api.microsofttranslator.com/V2/LanguageService/Translate")
    @WebResult(name = "TranslateResult", targetNamespace = "http://api.microsofttranslator.com/V2")
    @RequestWrapper(localName = "Translate", targetNamespace = "http://api.microsofttranslator.com/V2", className = "com.microsofttranslator.api.v2.Translate")
    @ResponseWrapper(localName = "TranslateResponse", targetNamespace = "http://api.microsofttranslator.com/V2", className = "com.microsofttranslator.api.v2.TranslateResponse")
    public String translate(
        @WebParam(name = "appId", targetNamespace = "http://api.microsofttranslator.com/V2")
        String appId,
        @WebParam(name = "text", targetNamespace = "http://api.microsofttranslator.com/V2")
        String text,
        @WebParam(name = "from", targetNamespace = "http://api.microsofttranslator.com/V2")
        String from,
        @WebParam(name = "to", targetNamespace = "http://api.microsofttranslator.com/V2")
        String to,
        @WebParam(name = "contentType", targetNamespace = "http://api.microsofttranslator.com/V2")
        String contentType,
        @WebParam(name = "category", targetNamespace = "http://api.microsofttranslator.com/V2")
        String category);

    /**
     * 
     * @param to
     * @param appId
     * @param translations
     * @param from
     * @param options
     */
    @WebMethod(operationName = "AddTranslationArray", action = "http://api.microsofttranslator.com/V2/LanguageService/AddTranslationArray")
    @RequestWrapper(localName = "AddTranslationArray", targetNamespace = "http://api.microsofttranslator.com/V2", className = "com.microsofttranslator.api.v2.AddTranslationArray")
    @ResponseWrapper(localName = "AddTranslationArrayResponse", targetNamespace = "http://api.microsofttranslator.com/V2", className = "com.microsofttranslator.api.v2.AddTranslationArrayResponse")
    public void addTranslationArray(
        @WebParam(name = "appId", targetNamespace = "http://api.microsofttranslator.com/V2")
        String appId,
        @WebParam(name = "translations", targetNamespace = "http://api.microsofttranslator.com/V2")
        ArrayOfTranslation translations,
        @WebParam(name = "from", targetNamespace = "http://api.microsofttranslator.com/V2")
        String from,
        @WebParam(name = "to", targetNamespace = "http://api.microsofttranslator.com/V2")
        String to,
        @WebParam(name = "options", targetNamespace = "http://api.microsofttranslator.com/V2")
        TranslateOptions options);

    /**
     * 
     * @param to
     * @param texts
     * @param appId
     * @param from
     * @param options
     * @param maxTranslations
     * @return
     *     returns org.datacontract.schemas._2004._07.microsoft_mt_web_service.ArrayOfGetTranslationsResponse
     */
    @WebMethod(operationName = "GetTranslationsArray", action = "http://api.microsofttranslator.com/V2/LanguageService/GetTranslationsArray")
    @WebResult(name = "GetTranslationsArrayResult", targetNamespace = "http://api.microsofttranslator.com/V2")
    @RequestWrapper(localName = "GetTranslationsArray", targetNamespace = "http://api.microsofttranslator.com/V2", className = "com.microsofttranslator.api.v2.GetTranslationsArray")
    @ResponseWrapper(localName = "GetTranslationsArrayResponse", targetNamespace = "http://api.microsofttranslator.com/V2", className = "com.microsofttranslator.api.v2.GetTranslationsArrayResponse")
    public ArrayOfGetTranslationsResponse getTranslationsArray(
        @WebParam(name = "appId", targetNamespace = "http://api.microsofttranslator.com/V2")
        String appId,
        @WebParam(name = "texts", targetNamespace = "http://api.microsofttranslator.com/V2")
        ArrayOfstring texts,
        @WebParam(name = "from", targetNamespace = "http://api.microsofttranslator.com/V2")
        String from,
        @WebParam(name = "to", targetNamespace = "http://api.microsofttranslator.com/V2")
        String to,
        @WebParam(name = "maxTranslations", targetNamespace = "http://api.microsofttranslator.com/V2")
        Integer maxTranslations,
        @WebParam(name = "options", targetNamespace = "http://api.microsofttranslator.com/V2")
        TranslateOptions options);

    /**
     * 
     * @param text
     * @param appId
     * @param format
     * @param language
     * @param options
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "Speak", action = "http://api.microsofttranslator.com/V2/LanguageService/Speak")
    @WebResult(name = "SpeakResult", targetNamespace = "http://api.microsofttranslator.com/V2")
    @RequestWrapper(localName = "Speak", targetNamespace = "http://api.microsofttranslator.com/V2", className = "com.microsofttranslator.api.v2.Speak")
    @ResponseWrapper(localName = "SpeakResponse", targetNamespace = "http://api.microsofttranslator.com/V2", className = "com.microsofttranslator.api.v2.SpeakResponse")
    public String speak(
        @WebParam(name = "appId", targetNamespace = "http://api.microsofttranslator.com/V2")
        String appId,
        @WebParam(name = "text", targetNamespace = "http://api.microsofttranslator.com/V2")
        String text,
        @WebParam(name = "language", targetNamespace = "http://api.microsofttranslator.com/V2")
        String language,
        @WebParam(name = "format", targetNamespace = "http://api.microsofttranslator.com/V2")
        String format,
        @WebParam(name = "options", targetNamespace = "http://api.microsofttranslator.com/V2")
        String options);

    /**
     * 
     * @param to
     * @param texts
     * @param appId
     * @param from
     * @param options
     * @return
     *     returns org.datacontract.schemas._2004._07.microsoft_mt_web_service.ArrayOfTranslateArrayResponse
     */
    @WebMethod(operationName = "TranslateArray", action = "http://api.microsofttranslator.com/V2/LanguageService/TranslateArray")
    @WebResult(name = "TranslateArrayResult", targetNamespace = "http://api.microsofttranslator.com/V2")
    @RequestWrapper(localName = "TranslateArray", targetNamespace = "http://api.microsofttranslator.com/V2", className = "com.microsofttranslator.api.v2.TranslateArray")
    @ResponseWrapper(localName = "TranslateArrayResponse", targetNamespace = "http://api.microsofttranslator.com/V2", className = "com.microsofttranslator.api.v2.TranslateArrayResponse")
    public ArrayOfTranslateArrayResponse translateArray(
        @WebParam(name = "appId", targetNamespace = "http://api.microsofttranslator.com/V2")
        String appId,
        @WebParam(name = "texts", targetNamespace = "http://api.microsofttranslator.com/V2")
        ArrayOfstring texts,
        @WebParam(name = "from", targetNamespace = "http://api.microsofttranslator.com/V2")
        String from,
        @WebParam(name = "to", targetNamespace = "http://api.microsofttranslator.com/V2")
        String to,
        @WebParam(name = "options", targetNamespace = "http://api.microsofttranslator.com/V2")
        TranslateOptions options);

}
