
package org.tempuri;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "SoapService", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://api.microsofttranslator.com/V2/Soap.svc?wsdl")
public class SoapService
    extends Service
{

    private final static URL SOAPSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(org.tempuri.SoapService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = org.tempuri.SoapService.class.getResource(".");
            url = new URL(baseUrl, "http://api.microsofttranslator.com/V2/Soap.svc?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://api.microsofttranslator.com/V2/Soap.svc?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        SOAPSERVICE_WSDL_LOCATION = url;
    }

    public SoapService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SoapService() {
        super(SOAPSERVICE_WSDL_LOCATION, new QName("http://tempuri.org/", "SoapService"));
    }

    /**
     * 
     * @return
     *     returns LanguageService
     */
    @WebEndpoint(name = "BasicHttpBinding_LanguageService")
    public LanguageService getBasicHttpBindingLanguageService() {
        return super.getPort(new QName("http://tempuri.org/", "BasicHttpBinding_LanguageService"), LanguageService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns LanguageService
     */
    @WebEndpoint(name = "BasicHttpBinding_LanguageService")
    public LanguageService getBasicHttpBindingLanguageService(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "BasicHttpBinding_LanguageService"), LanguageService.class, features);
    }

}
