/*
 * Copyright 2007-2010 JadaSite.

 * This file is part of JadaSite.
 
 * JadaSite is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.

 * JadaSite is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.

 * You should have received a copy of the GNU General Public License
 * along with JadaSite.  If not, see <http://www.gnu.org/licenses/>.
 */

package com.jada.jpa.entity;

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Cache generated by hbm2java
 */
@Entity
@Table(name = "cache")
public class Cache implements java.io.Serializable {
	private static final long serialVersionUID = 3807226497925890384L;
	private Long cacheId;
	private String cacheKey;
	private char cacheTypeCode;
	private byte[] cacheValue;
	private String cacheText;
	private String recUpdateBy;
	private Date recUpdateDatetime;
	private String recCreateBy;
	private Date recCreateDatetime;
	private String siteId;
	private Site site;

	public Cache() {
	}

	public Cache(String cacheKey, char cacheTypeCode, String recUpdateBy,
			Date recUpdateDatetime, String recCreateBy, Date recCreateDatetime,
			String siteId, Site site) {
		this.cacheKey = cacheKey;
		this.cacheTypeCode = cacheTypeCode;
		this.recUpdateBy = recUpdateBy;
		this.recUpdateDatetime = recUpdateDatetime;
		this.recCreateBy = recCreateBy;
		this.recCreateDatetime = recCreateDatetime;
		this.siteId = siteId;
		this.site = site;
	}

	public Cache(String cacheKey, char cacheTypeCode, byte[] cacheValue,
			String cacheText, String recUpdateBy, Date recUpdateDatetime,
			String recCreateBy, Date recCreateDatetime, String siteId, Site site) {
		this.cacheKey = cacheKey;
		this.cacheTypeCode = cacheTypeCode;
		this.cacheValue = cacheValue;
		this.cacheText = cacheText;
		this.recUpdateBy = recUpdateBy;
		this.recUpdateDatetime = recUpdateDatetime;
		this.recCreateBy = recCreateBy;
		this.recCreateDatetime = recCreateDatetime;
		this.siteId = siteId;
		this.site = site;
	}

	@Id
	@GeneratedValue
	@Column(name = "cache_id", nullable = false)
	public Long getCacheId() {
		return this.cacheId;
	}

	public void setCacheId(Long cacheId) {
		this.cacheId = cacheId;
	}

	@Column(name = "cache_key", nullable = false, length = 40)
	public String getCacheKey() {
		return this.cacheKey;
	}

	public void setCacheKey(String cacheKey) {
		this.cacheKey = cacheKey;
	}

	@Column(name = "cache_type_code", nullable = false, length = 1)
	public char getCacheTypeCode() {
		return this.cacheTypeCode;
	}

	public void setCacheTypeCode(char cacheTypeCode) {
		this.cacheTypeCode = cacheTypeCode;
	}

	@Column(name = "cache_value", length = 100000000)
	public byte[] getCacheValue() {
		return this.cacheValue;
	}

	public void setCacheValue(byte[] cacheValue) {
		this.cacheValue = cacheValue;
	}

	@Column(name = "cache_text", length = 100000000)
	public String getCacheText() {
		return this.cacheText;
	}

	public void setCacheText(String cacheText) {
		this.cacheText = cacheText;
	}

	@Column(name = "rec_update_by", nullable = false, length = 20)
	public String getRecUpdateBy() {
		return this.recUpdateBy;
	}

	public void setRecUpdateBy(String recUpdateBy) {
		this.recUpdateBy = recUpdateBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "rec_update_datetime", nullable = false)
	public Date getRecUpdateDatetime() {
		return this.recUpdateDatetime;
	}

	public void setRecUpdateDatetime(Date recUpdateDatetime) {
		this.recUpdateDatetime = recUpdateDatetime;
	}

	@Column(name = "rec_create_by", nullable = false, length = 20)
	public String getRecCreateBy() {
		return this.recCreateBy;
	}

	public void setRecCreateBy(String recCreateBy) {
		this.recCreateBy = recCreateBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "rec_create_datetime", nullable = false)
	public Date getRecCreateDatetime() {
		return this.recCreateDatetime;
	}

	public void setRecCreateDatetime(Date recCreateDatetime) {
		this.recCreateDatetime = recCreateDatetime;
	}

	@Column(name = "site_id", nullable = false, insertable = false, updatable = false, length = 20)
	public String getSiteId() {
		return this.siteId;
	}

	public void setSiteId(String siteId) {
		this.siteId = siteId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "site_id", nullable = false)
	public Site getSite() {
		return this.site;
	}

	public void setSite(Site site) {
		this.site = site;
	}
}
