/*
 * Copyright 2007-2010 JadaSite.

 * This file is part of JadaSite.
 
 * JadaSite is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.

 * JadaSite is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.

 * You should have received a copy of the GNU General Public License
 * along with JadaSite.  If not, see <http://www.gnu.org/licenses/>.
 */

package com.jada.jpa.entity;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Comment generated by hbm2java
 */
@Entity
@Table(name = "comment")
public class Comment implements java.io.Serializable {
	private static final long serialVersionUID = -76545413038109530L;
	private Long commentId;
	private String commentTitle;
	private String comment;
	private Integer commentRating;
	private Character moderation;
	private Character commentApproved;
	private Character active;
	private String recUpdateBy;
	private Date recUpdateDatetime;
	private String recCreateBy;
	private Date recCreateDatetime;
	private Item item;
	private Content content;
	private Customer customer;
	private Set<Customer> agreeCustomers = new HashSet<Customer>(0);
	private Set<Customer> disagreeCustomers = new HashSet<Customer>(0);

	public Comment() {
	}

	public Comment(String commentTitle, String comment, Integer commentRating,
			Character active, String recUpdateBy, Date recUpdateDatetime,
			String recCreateBy, Date recCreateDatetime) {
		this.commentTitle = commentTitle;
		this.comment = comment;
		this.commentRating = commentRating;
		this.active = active;
		this.recUpdateBy = recUpdateBy;
		this.recUpdateDatetime = recUpdateDatetime;
		this.recCreateBy = recCreateBy;
		this.recCreateDatetime = recCreateDatetime;
	}

	public Comment(String commentTitle, String comment, Integer commentRating,
			Character moderation, Character commentApproved, Character active,
			String recUpdateBy, Date recUpdateDatetime, String recCreateBy,
			Date recCreateDatetime, Item item, Content content,
			Customer customer, Set<Customer> agreeCustomers,
			Set<Customer> disagreeCustomers) {
		this.commentTitle = commentTitle;
		this.comment = comment;
		this.commentRating = commentRating;
		this.moderation = moderation;
		this.commentApproved = commentApproved;
		this.active = active;
		this.recUpdateBy = recUpdateBy;
		this.recUpdateDatetime = recUpdateDatetime;
		this.recCreateBy = recCreateBy;
		this.recCreateDatetime = recCreateDatetime;
		this.item = item;
		this.content = content;
		this.customer = customer;
		this.agreeCustomers = agreeCustomers;
		this.disagreeCustomers = disagreeCustomers;
	}

	@Id
	@GeneratedValue
	@Column(name = "comment_id", nullable = false)
	public Long getCommentId() {
		return this.commentId;
	}

	public void setCommentId(Long commentId) {
		this.commentId = commentId;
	}

	@Column(name = "comment_title", nullable = false)
	public String getCommentTitle() {
		return this.commentTitle;
	}

	public void setCommentTitle(String commentTitle) {
		this.commentTitle = commentTitle;
	}

	@Column(name = "comment", nullable = false, length = 100000000)
	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

	@Column(name = "comment_rating", nullable = false)
	public Integer getCommentRating() {
		return this.commentRating;
	}

	public void setCommentRating(Integer commentRating) {
		this.commentRating = commentRating;
	}

	@Column(name = "moderation", length = 1)
	public Character getModeration() {
		return this.moderation;
	}

	public void setModeration(Character moderation) {
		this.moderation = moderation;
	}

	@Column(name = "comment_approved", length = 1)
	public Character getCommentApproved() {
		return this.commentApproved;
	}

	public void setCommentApproved(Character commentApproved) {
		this.commentApproved = commentApproved;
	}

	@Column(name = "active", nullable = false, length = 1)
	public Character getActive() {
		return this.active;
	}

	public void setActive(Character active) {
		this.active = active;
	}

	@Column(name = "rec_update_by", nullable = false, length = 20)
	public String getRecUpdateBy() {
		return this.recUpdateBy;
	}

	public void setRecUpdateBy(String recUpdateBy) {
		this.recUpdateBy = recUpdateBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "rec_update_datetime", nullable = false)
	public Date getRecUpdateDatetime() {
		return this.recUpdateDatetime;
	}

	public void setRecUpdateDatetime(Date recUpdateDatetime) {
		this.recUpdateDatetime = recUpdateDatetime;
	}

	@Column(name = "rec_create_by", nullable = false, length = 20)
	public String getRecCreateBy() {
		return this.recCreateBy;
	}

	public void setRecCreateBy(String recCreateBy) {
		this.recCreateBy = recCreateBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "rec_create_datetime", nullable = false)
	public Date getRecCreateDatetime() {
		return this.recCreateDatetime;
	}

	public void setRecCreateDatetime(Date recCreateDatetime) {
		this.recCreateDatetime = recCreateDatetime;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "item_id")
	public Item getItem() {
		return this.item;
	}

	public void setItem(Item item) {
		this.item = item;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "content_id")
	public Content getContent() {
		return this.content;
	}

	public void setContent(Content content) {
		this.content = content;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cust_id")
	public Customer getCustomer() {
		return this.customer;
	}

	public void setCustomer(Customer customer) {
		this.customer = customer;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "comment_agree_customer", joinColumns = { @JoinColumn(name = "comment_id", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "customer_id", nullable = false, updatable = false) })
	public Set<Customer> getAgreeCustomers() {
		return this.agreeCustomers;
	}

	public void setAgreeCustomers(Set<Customer> agreeCustomers) {
		this.agreeCustomers = agreeCustomers;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "comment_disagree_customer", joinColumns = { @JoinColumn(name = "comment_id", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "customer_id", nullable = false, updatable = false) })
	public Set<Customer> getDisagreeCustomers() {
		return this.disagreeCustomers;
	}

	public void setDisagreeCustomers(Set<Customer> disagreeCustomers) {
		this.disagreeCustomers = disagreeCustomers;
	}

}
