/*
 * Copyright 2007-2010 JadaSite.

 * This file is part of JadaSite.
 
 * JadaSite is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.

 * JadaSite is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.

 * You should have received a copy of the GNU General Public License
 * along with JadaSite.  If not, see <http://www.gnu.org/licenses/>.
 */

package com.jada.jpa.entity;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ContactUs generated by hbm2java
 */
@Entity
@Table(name = "contact_us")
public class ContactUs implements java.io.Serializable {
	private static final long serialVersionUID = -625020582267066219L;
	private Long contactUsId;
	private String contactUsAddressLine1;
	private String contactUsAddressLine2;
	private String contactUsCityName;
	private String contactUsStateName;
	private String contactUsStateCode;
	private String contactUsCountryName;
	private String contactUsCountryCode;
	private String contactUsZipCode;
	private String contactUsEmail;
	private String contactUsPhone;
	private Integer seqNum;
	private Character active;
	private String recUpdateBy;
	private Date recUpdateDatetime;
	private String recCreateBy;
	private Date recCreateDatetime;
	private String siteId;
	private ContactUsLanguage contactUsLanguage;
	private Set<ContactUsLanguage> contactUsLanguages = new HashSet<ContactUsLanguage>(
			0);
	private Site site;

	public ContactUs() {
	}

	public ContactUs(String contactUsAddressLine1,
			String contactUsAddressLine2, String contactUsCityName,
			String contactUsStateName, String contactUsStateCode,
			String contactUsCountryName, String contactUsCountryCode,
			String contactUsZipCode, String contactUsEmail, Integer seqNum,
			Character active, String recUpdateBy, Date recUpdateDatetime,
			String recCreateBy, Date recCreateDatetime, String siteId,
			ContactUsLanguage contactUsLanguage, Site site) {
		this.contactUsAddressLine1 = contactUsAddressLine1;
		this.contactUsAddressLine2 = contactUsAddressLine2;
		this.contactUsCityName = contactUsCityName;
		this.contactUsStateName = contactUsStateName;
		this.contactUsStateCode = contactUsStateCode;
		this.contactUsCountryName = contactUsCountryName;
		this.contactUsCountryCode = contactUsCountryCode;
		this.contactUsZipCode = contactUsZipCode;
		this.contactUsEmail = contactUsEmail;
		this.seqNum = seqNum;
		this.active = active;
		this.recUpdateBy = recUpdateBy;
		this.recUpdateDatetime = recUpdateDatetime;
		this.recCreateBy = recCreateBy;
		this.recCreateDatetime = recCreateDatetime;
		this.siteId = siteId;
		this.contactUsLanguage = contactUsLanguage;
		this.site = site;
	}

	public ContactUs(String contactUsAddressLine1,
			String contactUsAddressLine2, String contactUsCityName,
			String contactUsStateName, String contactUsStateCode,
			String contactUsCountryName, String contactUsCountryCode,
			String contactUsZipCode, String contactUsEmail,
			String contactUsPhone, Integer seqNum, Character active,
			String recUpdateBy, Date recUpdateDatetime, String recCreateBy,
			Date recCreateDatetime, String siteId,
			ContactUsLanguage contactUsLanguage,
			Set<ContactUsLanguage> contactUsLanguages, Site site) {
		this.contactUsAddressLine1 = contactUsAddressLine1;
		this.contactUsAddressLine2 = contactUsAddressLine2;
		this.contactUsCityName = contactUsCityName;
		this.contactUsStateName = contactUsStateName;
		this.contactUsStateCode = contactUsStateCode;
		this.contactUsCountryName = contactUsCountryName;
		this.contactUsCountryCode = contactUsCountryCode;
		this.contactUsZipCode = contactUsZipCode;
		this.contactUsEmail = contactUsEmail;
		this.contactUsPhone = contactUsPhone;
		this.seqNum = seqNum;
		this.active = active;
		this.recUpdateBy = recUpdateBy;
		this.recUpdateDatetime = recUpdateDatetime;
		this.recCreateBy = recCreateBy;
		this.recCreateDatetime = recCreateDatetime;
		this.siteId = siteId;
		this.contactUsLanguage = contactUsLanguage;
		this.contactUsLanguages = contactUsLanguages;
		this.site = site;
	}

	@Id
	@GeneratedValue
	@Column(name = "contact_us_id", nullable = false)
	public Long getContactUsId() {
		return this.contactUsId;
	}

	public void setContactUsId(Long contactUsId) {
		this.contactUsId = contactUsId;
	}

	@Column(name = "contact_us_address_line1", nullable = false, length = 30)
	public String getContactUsAddressLine1() {
		return this.contactUsAddressLine1;
	}

	public void setContactUsAddressLine1(String contactUsAddressLine1) {
		this.contactUsAddressLine1 = contactUsAddressLine1;
	}

	@Column(name = "contact_us_address_line2", nullable = false, length = 30)
	public String getContactUsAddressLine2() {
		return this.contactUsAddressLine2;
	}

	public void setContactUsAddressLine2(String contactUsAddressLine2) {
		this.contactUsAddressLine2 = contactUsAddressLine2;
	}

	@Column(name = "contact_us_city_name", nullable = false, length = 25)
	public String getContactUsCityName() {
		return this.contactUsCityName;
	}

	public void setContactUsCityName(String contactUsCityName) {
		this.contactUsCityName = contactUsCityName;
	}

	@Column(name = "contact_us_state_name", nullable = false, length = 40)
	public String getContactUsStateName() {
		return this.contactUsStateName;
	}

	public void setContactUsStateName(String contactUsStateName) {
		this.contactUsStateName = contactUsStateName;
	}

	@Column(name = "contact_us_state_code", nullable = false, length = 2)
	public String getContactUsStateCode() {
		return this.contactUsStateCode;
	}

	public void setContactUsStateCode(String contactUsStateCode) {
		this.contactUsStateCode = contactUsStateCode;
	}

	@Column(name = "contact_us_country_name", nullable = false, length = 40)
	public String getContactUsCountryName() {
		return this.contactUsCountryName;
	}

	public void setContactUsCountryName(String contactUsCountryName) {
		this.contactUsCountryName = contactUsCountryName;
	}

	@Column(name = "contact_us_country_code", nullable = false, length = 2)
	public String getContactUsCountryCode() {
		return this.contactUsCountryCode;
	}

	public void setContactUsCountryCode(String contactUsCountryCode) {
		this.contactUsCountryCode = contactUsCountryCode;
	}

	@Column(name = "contact_us_zip_code", nullable = false, length = 10)
	public String getContactUsZipCode() {
		return this.contactUsZipCode;
	}

	public void setContactUsZipCode(String contactUsZipCode) {
		this.contactUsZipCode = contactUsZipCode;
	}

	@Column(name = "contact_us_email", nullable = false, length = 50)
	public String getContactUsEmail() {
		return this.contactUsEmail;
	}

	public void setContactUsEmail(String contactUsEmail) {
		this.contactUsEmail = contactUsEmail;
	}

	@Column(name = "contact_us_phone", length = 20)
	public String getContactUsPhone() {
		return this.contactUsPhone;
	}

	public void setContactUsPhone(String contactUsPhone) {
		this.contactUsPhone = contactUsPhone;
	}

	@Column(name = "seq_num", nullable = false)
	public Integer getSeqNum() {
		return this.seqNum;
	}

	public void setSeqNum(Integer seqNum) {
		this.seqNum = seqNum;
	}

	@Column(name = "active", nullable = false, length = 1)
	public Character getActive() {
		return this.active;
	}

	public void setActive(Character active) {
		this.active = active;
	}

	@Column(name = "rec_update_by", nullable = false, length = 20)
	public String getRecUpdateBy() {
		return this.recUpdateBy;
	}

	public void setRecUpdateBy(String recUpdateBy) {
		this.recUpdateBy = recUpdateBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "rec_update_datetime", nullable = false)
	public Date getRecUpdateDatetime() {
		return this.recUpdateDatetime;
	}

	public void setRecUpdateDatetime(Date recUpdateDatetime) {
		this.recUpdateDatetime = recUpdateDatetime;
	}

	@Column(name = "rec_create_by", nullable = false, length = 20)
	public String getRecCreateBy() {
		return this.recCreateBy;
	}

	public void setRecCreateBy(String recCreateBy) {
		this.recCreateBy = recCreateBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "rec_create_datetime", nullable = false)
	public Date getRecCreateDatetime() {
		return this.recCreateDatetime;
	}

	public void setRecCreateDatetime(Date recCreateDatetime) {
		this.recCreateDatetime = recCreateDatetime;
	}

	@Column(name = "site_id", nullable = false, insertable = false, updatable = false, length = 20)
	public String getSiteId() {
		return this.siteId;
	}

	public void setSiteId(String siteId) {
		this.siteId = siteId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "contact_us_lang_id", nullable = false)
	public ContactUsLanguage getContactUsLanguage() {
		return this.contactUsLanguage;
	}

	public void setContactUsLanguage(ContactUsLanguage contactUsLanguage) {
		this.contactUsLanguage = contactUsLanguage;
	}

	@OneToMany(fetch = FetchType.LAZY)
	@JoinColumn(name = "contact_us_id")
	public Set<ContactUsLanguage> getContactUsLanguages() {
		return this.contactUsLanguages;
	}

	public void setContactUsLanguages(Set<ContactUsLanguage> contactUsLanguages) {
		this.contactUsLanguages = contactUsLanguages;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "site_id", nullable = false)
	public Site getSite() {
		return this.site;
	}

	public void setSite(Site site) {
		this.site = site;
	}

}
