/*
 * Copyright 2007-2010 JadaSite.

 * This file is part of JadaSite.
 
 * JadaSite is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.

 * JadaSite is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.

 * You should have received a copy of the GNU General Public License
 * along with JadaSite.  If not, see <http://www.gnu.org/licenses/>.
 */

package com.jada.jpa.entity;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OrderBy;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ContentLanguage generated by hbm2java
 */
@Entity
@Table(name = "content_language")
public class ContentLanguage implements java.io.Serializable {
	private static final long serialVersionUID = 6316484002602942608L;
	private Long contentLangId;
	private String contentTitle;
	private String contentShortDesc;
	private String contentDesc;
	private String pageTitle;
	private String contentImageOverride;
	private String metaKeywords;
	private String metaDescription;
	private String recUpdateBy;
	private Date recUpdateDatetime;
	private String recCreateBy;
	private Date recCreateDatetime;
	private Content content;
	private ContentImage image;
	private SiteProfileClass siteProfileClass;
	private Set<ContentImage> images = new HashSet<ContentImage>(0);

	public ContentLanguage() {
	}

	public ContentLanguage(String contentImageOverride, String recUpdateBy,
			Date recUpdateDatetime, String recCreateBy, Date recCreateDatetime) {
		this.contentImageOverride = contentImageOverride;
		this.recUpdateBy = recUpdateBy;
		this.recUpdateDatetime = recUpdateDatetime;
		this.recCreateBy = recCreateBy;
		this.recCreateDatetime = recCreateDatetime;
	}

	public ContentLanguage(String contentTitle, String contentShortDesc,
			String contentDesc, String pageTitle, String contentImageOverride,
			String metaKeywords, String metaDescription,
			String recUpdateBy, Date recUpdateDatetime, String recCreateBy,
			Date recCreateDatetime, Content content, ContentImage image,
			SiteProfileClass siteProfileClass, Set<ContentImage> images) {
		this.contentTitle = contentTitle;
		this.contentShortDesc = contentShortDesc;
		this.contentDesc = contentDesc;
		this.pageTitle = pageTitle;
		this.contentImageOverride = contentImageOverride;
		this.metaKeywords = metaKeywords;
		this.metaDescription = metaDescription;
		this.recUpdateBy = recUpdateBy;
		this.recUpdateDatetime = recUpdateDatetime;
		this.recCreateBy = recCreateBy;
		this.recCreateDatetime = recCreateDatetime;
		this.content = content;
		this.image = image;
		this.siteProfileClass = siteProfileClass;
		this.images = images;
	}

	@Id
	@GeneratedValue
	@Column(name = "content_lang_id", nullable = false, length = 20)
	public Long getContentLangId() {
		return this.contentLangId;
	}

	public void setContentLangId(Long contentLangId) {
		this.contentLangId = contentLangId;
	}

	@Column(name = "content_title", length = 128)
	public String getContentTitle() {
		return this.contentTitle;
	}

	public void setContentTitle(String contentTitle) {
		this.contentTitle = contentTitle;
	}

	@Column(name = "content_short_desc", length = 100000000)
	public String getContentShortDesc() {
		return this.contentShortDesc;
	}

	public void setContentShortDesc(String contentShortDesc) {
		this.contentShortDesc = contentShortDesc;
	}

	@Column(name = "content_desc", length = 100000000)
	public String getContentDesc() {
		return this.contentDesc;
	}

	public void setContentDesc(String contentDesc) {
		this.contentDesc = contentDesc;
	}

	@Column(name = "page_title")
	public String getPageTitle() {
		return this.pageTitle;
	}

	public void setPageTitle(String pageTitle) {
		this.pageTitle = pageTitle;
	}

	@Column(name = "content_image_override", nullable = false, length = 1)
	public String getContentImageOverride() {
		return this.contentImageOverride;
	}

	public void setContentImageOverride(String contentImageOverride) {
		this.contentImageOverride = contentImageOverride;
	}

	@Column(name = "meta_keywords", length = 1000)
	public String getMetaKeywords() {
		return this.metaKeywords;
	}

	public void setMetaKeywords(String metaKeywords) {
		this.metaKeywords = metaKeywords;
	}

	@Column(name = "meta_description", length = 1000)
	public String getMetaDescription() {
		return this.metaDescription;
	}

	public void setMetaDescription(String metaDescription) {
		this.metaDescription = metaDescription;
	}

	@Column(name = "rec_update_by", nullable = false, length = 20)
	public String getRecUpdateBy() {
		return this.recUpdateBy;
	}

	public void setRecUpdateBy(String recUpdateBy) {
		this.recUpdateBy = recUpdateBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "rec_update_datetime", nullable = false)
	public Date getRecUpdateDatetime() {
		return this.recUpdateDatetime;
	}

	public void setRecUpdateDatetime(Date recUpdateDatetime) {
		this.recUpdateDatetime = recUpdateDatetime;
	}

	@Column(name = "rec_create_by", nullable = false, length = 20)
	public String getRecCreateBy() {
		return this.recCreateBy;
	}

	public void setRecCreateBy(String recCreateBy) {
		this.recCreateBy = recCreateBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "rec_create_datetime", nullable = false)
	public Date getRecCreateDatetime() {
		return this.recCreateDatetime;
	}

	public void setRecCreateDatetime(Date recCreateDatetime) {
		this.recCreateDatetime = recCreateDatetime;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "content_id")
	public Content getContent() {
		return this.content;
	}

	public void setContent(Content content) {
		this.content = content;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "image_id", unique = true)
	public ContentImage getImage() {
		return this.image;
	}

	public void setImage(ContentImage image) {
		this.image = image;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "site_profile_class_id")
	public SiteProfileClass getSiteProfileClass() {
		return this.siteProfileClass;
	}

	public void setSiteProfileClass(SiteProfileClass siteProfileClass) {
		this.siteProfileClass = siteProfileClass;
	}

	@OneToMany(fetch = FetchType.LAZY)
	@OrderBy(value="imageId")
	@JoinColumn(name = "content_lang_id", updatable = false)
	public Set<ContentImage> getImages() {
		return this.images;
	}

	public void setImages(Set<ContentImage> images) {
		this.images = images;
	}

}
