/*
 * Copyright 2007-2010 JadaSite.

 * This file is part of JadaSite.
 
 * JadaSite is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.

 * JadaSite is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.

 * You should have received a copy of the GNU General Public License
 * along with JadaSite.  If not, see <http://www.gnu.org/licenses/>.
 */

package com.jada.jpa.entity;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Control generated by hbm2java
 */
@Entity
@Table(name = "control")
public class Control implements java.io.Serializable {
	private static final long serialVersionUID = -6555861282776381510L;
	private String controlKey;
	private String controlValue;

	public Control() {
	}

	public Control(String controlKey, String controlValue) {
		this.controlKey = controlKey;
		this.controlValue = controlValue;
	}

	@Id
	@Column(name = "control_key", nullable = false, length = 20)
	public String getControlKey() {
		return this.controlKey;
	}

	public void setControlKey(String controlKey) {
		this.controlKey = controlKey;
	}

	@Column(name = "control_value", nullable = false, length = 50)
	public String getControlValue() {
		return this.controlValue;
	}

	public void setControlValue(String controlValue) {
		this.controlValue = controlValue;
	}

}
