/*
 * Copyright 2007-2010 JadaSite.

 * This file is part of JadaSite.
 
 * JadaSite is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.

 * JadaSite is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.

 * You should have received a copy of the GNU General Public License
 * along with JadaSite.  If not, see <http://www.gnu.org/licenses/>.
 */

package com.jada.jpa.entity;

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ContactUsLanguage generated by hbm2java
 */
@Entity
@Table(name = "contact_us_language")
public class ContactUsLanguage implements java.io.Serializable {
	private static final long serialVersionUID = 2347161583768701577L;
	private Long contactUsLangId;
	private String contactUsName;
	private String contactUsDesc;
	private String recUpdateBy;
	private Date recUpdateDatetime;
	private String recCreateBy;
	private Date recCreateDatetime;
	private ContactUs contactUs;
	private SiteProfileClass siteProfileClass;

	public ContactUsLanguage() {
	}

	public ContactUsLanguage(String recUpdateBy, Date recUpdateDatetime,
			String recCreateBy, Date recCreateDatetime) {
		this.recUpdateBy = recUpdateBy;
		this.recUpdateDatetime = recUpdateDatetime;
		this.recCreateBy = recCreateBy;
		this.recCreateDatetime = recCreateDatetime;
	}

	public ContactUsLanguage(String contactUsName, String contactUsDesc,
			String recUpdateBy, Date recUpdateDatetime, String recCreateBy,
			Date recCreateDatetime, ContactUs contactUs,
			SiteProfileClass siteProfileClass) {
		this.contactUsName = contactUsName;
		this.contactUsDesc = contactUsDesc;
		this.recUpdateBy = recUpdateBy;
		this.recUpdateDatetime = recUpdateDatetime;
		this.recCreateBy = recCreateBy;
		this.recCreateDatetime = recCreateDatetime;
		this.contactUs = contactUs;
		this.siteProfileClass = siteProfileClass;
	}

	@Id
	@GeneratedValue
	@Column(name = "contact_us_lang_id", nullable = false, length = 20)
	public Long getContactUsLangId() {
		return this.contactUsLangId;
	}

	public void setContactUsLangId(Long contactUsLangId) {
		this.contactUsLangId = contactUsLangId;
	}

	@Column(name = "contact_us_name", length = 50)
	public String getContactUsName() {
		return this.contactUsName;
	}

	public void setContactUsName(String contactUsName) {
		this.contactUsName = contactUsName;
	}

	@Column(name = "contact_us_desc", length = 100000000)
	public String getContactUsDesc() {
		return this.contactUsDesc;
	}

	public void setContactUsDesc(String contactUsDesc) {
		this.contactUsDesc = contactUsDesc;
	}

	@Column(name = "rec_update_by", nullable = false, length = 20)
	public String getRecUpdateBy() {
		return this.recUpdateBy;
	}

	public void setRecUpdateBy(String recUpdateBy) {
		this.recUpdateBy = recUpdateBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "rec_update_datetime", nullable = false)
	public Date getRecUpdateDatetime() {
		return this.recUpdateDatetime;
	}

	public void setRecUpdateDatetime(Date recUpdateDatetime) {
		this.recUpdateDatetime = recUpdateDatetime;
	}

	@Column(name = "rec_create_by", nullable = false, length = 20)
	public String getRecCreateBy() {
		return this.recCreateBy;
	}

	public void setRecCreateBy(String recCreateBy) {
		this.recCreateBy = recCreateBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "rec_create_datetime", nullable = false)
	public Date getRecCreateDatetime() {
		return this.recCreateDatetime;
	}

	public void setRecCreateDatetime(Date recCreateDatetime) {
		this.recCreateDatetime = recCreateDatetime;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "contact_us_id")
	public ContactUs getContactUs() {
		return this.contactUs;
	}

	public void setContactUs(ContactUs contactUs) {
		this.contactUs = contactUs;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "site_profile_class_id")
	public SiteProfileClass getSiteProfileClass() {
		return this.siteProfileClass;
	}

	public void setSiteProfileClass(SiteProfileClass siteProfileClass) {
		this.siteProfileClass = siteProfileClass;
	}

}
