/*
 * Copyright 2007-2010 JadaSite.

 * This file is part of JadaSite.
 
 * JadaSite is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.

 * JadaSite is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.

 * You should have received a copy of the GNU General Public License
 * along with JadaSite.  If not, see <http://www.gnu.org/licenses/>.
 */

package com.jada.jpa.entity;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OrderBy;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Coupon generated by hbm2java
 */
@Entity
@Table(name = "coupon", uniqueConstraints = @UniqueConstraint(columnNames = {
		"coupon_code", "site_id" }))
public class Coupon implements java.io.Serializable {
	private static final long serialVersionUID = 8814952353896249944L;
	private Long couponId;
	private String couponCode;
	private Date couponStartDate;
	private Date couponEndDate;
	private char couponAutoApply;
	private char couponApplyAll;
	private char couponType;
	private char couponScope;
	private Float couponDiscountPercent;
	private Integer couponTotalUsed;
	private Integer couponMaxUse;
	private Integer couponMaxCustUse;
	private Integer couponPriority;
	private char published;
	private String recUpdateBy;
	private Date recUpdateDatetime;
	private String recCreateBy;
	private Date recCreateDatetime;
	private String siteId;
	private CouponLanguage couponLanguage;
	private CouponCurrency couponCurrency;
	private Set<Item> items = new HashSet<Item>(0);
	private Set<Category> categories = new HashSet<Category>(0);
	private Set<CouponLanguage> couponLanguages = new HashSet<CouponLanguage>(0);
	private Set<CouponCurrency> couponCurrencies = new HashSet<CouponCurrency>(
			0);
	private Site site;

	public Coupon() {
	}

	public Coupon(String couponCode, Date couponStartDate, Date couponEndDate,
			char couponAutoApply, char couponApplyAll, char couponType,
			char couponScope, Integer couponTotalUsed, char published,
			String recUpdateBy, Date recUpdateDatetime, String recCreateBy,
			Date recCreateDatetime, String siteId,
			CouponLanguage couponLanguage, CouponCurrency couponCurrency,
			Site site) {
		this.couponCode = couponCode;
		this.couponStartDate = couponStartDate;
		this.couponEndDate = couponEndDate;
		this.couponAutoApply = couponAutoApply;
		this.couponApplyAll = couponApplyAll;
		this.couponType = couponType;
		this.couponScope = couponScope;
		this.couponTotalUsed = couponTotalUsed;
		this.published = published;
		this.recUpdateBy = recUpdateBy;
		this.recUpdateDatetime = recUpdateDatetime;
		this.recCreateBy = recCreateBy;
		this.recCreateDatetime = recCreateDatetime;
		this.siteId = siteId;
		this.couponLanguage = couponLanguage;
		this.couponCurrency = couponCurrency;
		this.site = site;
	}

	public Coupon(String couponCode, Date couponStartDate, Date couponEndDate,
			char couponAutoApply, char couponApplyAll, char couponType,
			char couponScope, Float couponDiscountPercent,
			Integer couponTotalUsed, Integer couponMaxUse,
			Integer couponMaxCustUse, Integer couponPriority, char published,
			String recUpdateBy, Date recUpdateDatetime, String recCreateBy,
			Date recCreateDatetime, String siteId,
			CouponLanguage couponLanguage, CouponCurrency couponCurrency,
			Set<Item> items, Set<Category> categories,
			Set<CouponLanguage> couponLanguages,
			Set<CouponCurrency> couponCurrencies, Site site) {
		this.couponCode = couponCode;
		this.couponStartDate = couponStartDate;
		this.couponEndDate = couponEndDate;
		this.couponAutoApply = couponAutoApply;
		this.couponApplyAll = couponApplyAll;
		this.couponType = couponType;
		this.couponScope = couponScope;
		this.couponDiscountPercent = couponDiscountPercent;
		this.couponTotalUsed = couponTotalUsed;
		this.couponMaxUse = couponMaxUse;
		this.couponMaxCustUse = couponMaxCustUse;
		this.couponPriority = couponPriority;
		this.published = published;
		this.recUpdateBy = recUpdateBy;
		this.recUpdateDatetime = recUpdateDatetime;
		this.recCreateBy = recCreateBy;
		this.recCreateDatetime = recCreateDatetime;
		this.siteId = siteId;
		this.couponLanguage = couponLanguage;
		this.couponCurrency = couponCurrency;
		this.items = items;
		this.categories = categories;
		this.couponLanguages = couponLanguages;
		this.couponCurrencies = couponCurrencies;
		this.site = site;
	}

	@Id
	@GeneratedValue
	@Column(name = "coupon_id", nullable = false)
	public Long getCouponId() {
		return this.couponId;
	}

	public void setCouponId(Long couponId) {
		this.couponId = couponId;
	}

	@Column(name = "coupon_code", nullable = false, length = 20)
	public String getCouponCode() {
		return this.couponCode;
	}

	public void setCouponCode(String couponCode) {
		this.couponCode = couponCode;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "coupon_start_date", nullable = false, length = 10)
	public Date getCouponStartDate() {
		return this.couponStartDate;
	}

	public void setCouponStartDate(Date couponStartDate) {
		this.couponStartDate = couponStartDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "coupon_end_date", nullable = false, length = 10)
	public Date getCouponEndDate() {
		return this.couponEndDate;
	}

	public void setCouponEndDate(Date couponEndDate) {
		this.couponEndDate = couponEndDate;
	}

	@Column(name = "coupon_auto_apply", nullable = false, length = 1)
	public char getCouponAutoApply() {
		return this.couponAutoApply;
	}

	public void setCouponAutoApply(char couponAutoApply) {
		this.couponAutoApply = couponAutoApply;
	}

	@Column(name = "coupon_apply_all", nullable = false, length = 1)
	public char getCouponApplyAll() {
		return this.couponApplyAll;
	}

	public void setCouponApplyAll(char couponApplyAll) {
		this.couponApplyAll = couponApplyAll;
	}

	@Column(name = "coupon_type", nullable = false, length = 1)
	public char getCouponType() {
		return this.couponType;
	}

	public void setCouponType(char couponType) {
		this.couponType = couponType;
	}

	@Column(name = "coupon_scope", nullable = false, length = 1)
	public char getCouponScope() {
		return this.couponScope;
	}

	public void setCouponScope(char couponScope) {
		this.couponScope = couponScope;
	}

	@Column(name = "couponDiscountPercent")
	public Float getCouponDiscountPercent() {
		return this.couponDiscountPercent;
	}

	public void setCouponDiscountPercent(Float couponDiscountPercent) {
		this.couponDiscountPercent = couponDiscountPercent;
	}

	@Column(name = "coupon_total_used", nullable = false)
	public Integer getCouponTotalUsed() {
		return this.couponTotalUsed;
	}

	public void setCouponTotalUsed(Integer couponTotalUsed) {
		this.couponTotalUsed = couponTotalUsed;
	}

	@Column(name = "coupon_max_use")
	public Integer getCouponMaxUse() {
		return this.couponMaxUse;
	}

	public void setCouponMaxUse(Integer couponMaxUse) {
		this.couponMaxUse = couponMaxUse;
	}

	@Column(name = "coupon_max_cust_use")
	public Integer getCouponMaxCustUse() {
		return this.couponMaxCustUse;
	}

	public void setCouponMaxCustUse(Integer couponMaxCustUse) {
		this.couponMaxCustUse = couponMaxCustUse;
	}

	@Column(name = "coupon_priority")
	public Integer getCouponPriority() {
		return this.couponPriority;
	}

	public void setCouponPriority(Integer couponPriority) {
		this.couponPriority = couponPriority;
	}

	@Column(name = "published", nullable = false, length = 1)
	public char getPublished() {
		return this.published;
	}

	public void setPublished(char published) {
		this.published = published;
	}

	@Column(name = "rec_update_by", nullable = false, length = 20)
	public String getRecUpdateBy() {
		return this.recUpdateBy;
	}

	public void setRecUpdateBy(String recUpdateBy) {
		this.recUpdateBy = recUpdateBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "rec_update_datetime", nullable = false)
	public Date getRecUpdateDatetime() {
		return this.recUpdateDatetime;
	}

	public void setRecUpdateDatetime(Date recUpdateDatetime) {
		this.recUpdateDatetime = recUpdateDatetime;
	}

	@Column(name = "rec_create_by", nullable = false, length = 20)
	public String getRecCreateBy() {
		return this.recCreateBy;
	}

	public void setRecCreateBy(String recCreateBy) {
		this.recCreateBy = recCreateBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "rec_create_datetime", nullable = false)
	public Date getRecCreateDatetime() {
		return this.recCreateDatetime;
	}

	public void setRecCreateDatetime(Date recCreateDatetime) {
		this.recCreateDatetime = recCreateDatetime;
	}

	@Column(name = "site_id", nullable = false, insertable = false, updatable = false, length = 20)
	public String getSiteId() {
		return this.siteId;
	}

	public void setSiteId(String siteId) {
		this.siteId = siteId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "coupon_lang_id", nullable = false)
	public CouponLanguage getCouponLanguage() {
		return this.couponLanguage;
	}

	public void setCouponLanguage(CouponLanguage couponLanguage) {
		this.couponLanguage = couponLanguage;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "coupon_curr_id", nullable = false)
	public CouponCurrency getCouponCurrency() {
		return this.couponCurrency;
	}

	public void setCouponCurrency(CouponCurrency couponCurrency) {
		this.couponCurrency = couponCurrency;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@OrderBy(value="itemId")
	@JoinTable(name = "coupon_item", joinColumns = { @JoinColumn(name = "coupon_id", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "item_id", nullable = false, updatable = false) })
	public Set<Item> getItems() {
		return this.items;
	}

	public void setItems(Set<Item> items) {
		this.items = items;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@OrderBy(value="catId")
	@JoinTable(name = "coupon_category", joinColumns = { @JoinColumn(name = "coupon_id", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "cat_id", nullable = false, updatable = false) })
	public Set<Category> getCategories() {
		return this.categories;
	}

	public void setCategories(Set<Category> categories) {
		this.categories = categories;
	}

	@OneToMany(fetch = FetchType.LAZY)
	@JoinColumn(name = "coupon_id", updatable = false)
	public Set<CouponLanguage> getCouponLanguages() {
		return this.couponLanguages;
	}

	public void setCouponLanguages(Set<CouponLanguage> couponLanguages) {
		this.couponLanguages = couponLanguages;
	}

	@OneToMany(fetch = FetchType.LAZY)
	@JoinColumn(name = "coupon_id", updatable = false)
	public Set<CouponCurrency> getCouponCurrencies() {
		return this.couponCurrencies;
	}

	public void setCouponCurrencies(Set<CouponCurrency> couponCurrencies) {
		this.couponCurrencies = couponCurrencies;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "site_id", nullable = false)
	public Site getSite() {
		return this.site;
	}

	public void setSite(Site site) {
		this.site = site;
	}

}
