/*
 * Copyright 2007-2010 JadaSite.

 * This file is part of JadaSite.
 
 * JadaSite is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.

 * JadaSite is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.

 * You should have received a copy of the GNU General Public License
 * along with JadaSite.  If not, see <http://www.gnu.org/licenses/>.
 */

package com.jada.jpa.entity;

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CreditDetailTax generated by hbm2java
 */
@Entity
@Table(name = "credit_detail_tax")
public class CreditDetailTax implements java.io.Serializable {
	private static final long serialVersionUID = -5491695739270791368L;
	private Long creditDetailTaxId;
	private String taxName;
	private Float taxAmount;
	private String recUpdateBy;
	private Date recUpdateDatetime;
	private String recCreateBy;
	private Date recCreateDatetime;
	private CreditDetail creditDetail;
	private CreditHeader creditHeader;
	private Tax tax;

	public CreditDetailTax() {
	}

	public CreditDetailTax(String taxName, Float taxAmount, String recUpdateBy,
			Date recUpdateDatetime, String recCreateBy, Date recCreateDatetime) {
		this.taxName = taxName;
		this.taxAmount = taxAmount;
		this.recUpdateBy = recUpdateBy;
		this.recUpdateDatetime = recUpdateDatetime;
		this.recCreateBy = recCreateBy;
		this.recCreateDatetime = recCreateDatetime;
	}

	public CreditDetailTax(String taxName, Float taxAmount, String recUpdateBy,
			Date recUpdateDatetime, String recCreateBy, Date recCreateDatetime,
			CreditDetail creditDetail, CreditHeader creditHeader, Tax tax) {
		this.taxName = taxName;
		this.taxAmount = taxAmount;
		this.recUpdateBy = recUpdateBy;
		this.recUpdateDatetime = recUpdateDatetime;
		this.recCreateBy = recCreateBy;
		this.recCreateDatetime = recCreateDatetime;
		this.creditDetail = creditDetail;
		this.creditHeader = creditHeader;
		this.tax = tax;
	}

	@Id
	@GeneratedValue
	@Column(name = "credit_detail_tax_id", nullable = false)
	public Long getCreditDetailTaxId() {
		return this.creditDetailTaxId;
	}

	public void setCreditDetailTaxId(Long creditDetailTaxId) {
		this.creditDetailTaxId = creditDetailTaxId;
	}

	@Column(name = "tax_name", nullable = false, length = 40)
	public String getTaxName() {
		return this.taxName;
	}

	public void setTaxName(String taxName) {
		this.taxName = taxName;
	}

	@Column(name = "tax_amount", nullable = false)
	public Float getTaxAmount() {
		return this.taxAmount;
	}

	public void setTaxAmount(Float taxAmount) {
		this.taxAmount = taxAmount;
	}

	@Column(name = "rec_update_by", nullable = false, length = 20)
	public String getRecUpdateBy() {
		return this.recUpdateBy;
	}

	public void setRecUpdateBy(String recUpdateBy) {
		this.recUpdateBy = recUpdateBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "rec_update_datetime", nullable = false)
	public Date getRecUpdateDatetime() {
		return this.recUpdateDatetime;
	}

	public void setRecUpdateDatetime(Date recUpdateDatetime) {
		this.recUpdateDatetime = recUpdateDatetime;
	}

	@Column(name = "rec_create_by", nullable = false, length = 20)
	public String getRecCreateBy() {
		return this.recCreateBy;
	}

	public void setRecCreateBy(String recCreateBy) {
		this.recCreateBy = recCreateBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "rec_create_datetime", nullable = false)
	public Date getRecCreateDatetime() {
		return this.recCreateDatetime;
	}

	public void setRecCreateDatetime(Date recCreateDatetime) {
		this.recCreateDatetime = recCreateDatetime;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "credit_detail_id")
	public CreditDetail getCreditDetail() {
		return this.creditDetail;
	}

	public void setCreditDetail(CreditDetail creditDetail) {
		this.creditDetail = creditDetail;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "credit_header_id")
	public CreditHeader getCreditHeader() {
		return this.creditHeader;
	}

	public void setCreditHeader(CreditHeader creditHeader) {
		this.creditHeader = creditHeader;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "tax_id")
	public Tax getTax() {
		return this.tax;
	}

	public void setTax(Tax tax) {
		this.tax = tax;
	}

}
