/*
 * Copyright 2007-2010 JadaSite.

 * This file is part of JadaSite.
 
 * JadaSite is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.

 * JadaSite is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.

 * You should have received a copy of the GNU General Public License
 * along with JadaSite.  If not, see <http://www.gnu.org/licenses/>.
 */

package com.jada.jpa.entity;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CreditDetail generated by hbm2java
 */
@Entity
@Table(name = "credit_detail")
public class CreditDetail implements java.io.Serializable {
	private static final long serialVersionUID = 3832268542709620674L;
	private Long creditDetailId;
	private Integer seqNum;
	private Integer itemCreditQty;
	private Float itemCreditAmount;
	private String recUpdateBy;
	private Date recUpdateDatetime;
	private String recCreateBy;
	private Date recCreateDatetime;
	private Set<CreditDetailTax> creditDetailTaxes = new HashSet<CreditDetailTax>(
			0);
	private CreditHeader creditHeader;
	private OrderItemDetail orderItemDetail;

	public CreditDetail() {
	}

	public CreditDetail(Integer seqNum, Integer itemCreditQty,
			Float itemCreditAmount, String recUpdateBy, Date recUpdateDatetime,
			String recCreateBy, Date recCreateDatetime) {
		this.seqNum = seqNum;
		this.itemCreditQty = itemCreditQty;
		this.itemCreditAmount = itemCreditAmount;
		this.recUpdateBy = recUpdateBy;
		this.recUpdateDatetime = recUpdateDatetime;
		this.recCreateBy = recCreateBy;
		this.recCreateDatetime = recCreateDatetime;
	}

	public CreditDetail(Integer seqNum, Integer itemCreditQty,
			Float itemCreditAmount, String recUpdateBy, Date recUpdateDatetime,
			String recCreateBy, Date recCreateDatetime,
			Set<CreditDetailTax> creditDetailTaxes, CreditHeader creditHeader,
			OrderItemDetail orderItemDetail) {
		this.seqNum = seqNum;
		this.itemCreditQty = itemCreditQty;
		this.itemCreditAmount = itemCreditAmount;
		this.recUpdateBy = recUpdateBy;
		this.recUpdateDatetime = recUpdateDatetime;
		this.recCreateBy = recCreateBy;
		this.recCreateDatetime = recCreateDatetime;
		this.creditDetailTaxes = creditDetailTaxes;
		this.creditHeader = creditHeader;
		this.orderItemDetail = orderItemDetail;
	}

	@Id
	@GeneratedValue
	@Column(name = "credit_detail_id", nullable = false)
	public Long getCreditDetailId() {
		return this.creditDetailId;
	}

	public void setCreditDetailId(Long creditDetailId) {
		this.creditDetailId = creditDetailId;
	}

	@Column(name = "seq_num", nullable = false)
	public Integer getSeqNum() {
		return this.seqNum;
	}

	public void setSeqNum(Integer seqNum) {
		this.seqNum = seqNum;
	}

	@Column(name = "item_credit_qty", nullable = false)
	public Integer getItemCreditQty() {
		return this.itemCreditQty;
	}

	public void setItemCreditQty(Integer itemCreditQty) {
		this.itemCreditQty = itemCreditQty;
	}

	@Column(name = "item_credit_amount", nullable = false)
	public Float getItemCreditAmount() {
		return this.itemCreditAmount;
	}

	public void setItemCreditAmount(Float itemCreditAmount) {
		this.itemCreditAmount = itemCreditAmount;
	}

	@Column(name = "rec_update_by", nullable = false, length = 20)
	public String getRecUpdateBy() {
		return this.recUpdateBy;
	}

	public void setRecUpdateBy(String recUpdateBy) {
		this.recUpdateBy = recUpdateBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "rec_update_datetime", nullable = false)
	public Date getRecUpdateDatetime() {
		return this.recUpdateDatetime;
	}

	public void setRecUpdateDatetime(Date recUpdateDatetime) {
		this.recUpdateDatetime = recUpdateDatetime;
	}

	@Column(name = "rec_create_by", nullable = false, length = 20)
	public String getRecCreateBy() {
		return this.recCreateBy;
	}

	public void setRecCreateBy(String recCreateBy) {
		this.recCreateBy = recCreateBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "rec_create_datetime", nullable = false)
	public Date getRecCreateDatetime() {
		return this.recCreateDatetime;
	}

	public void setRecCreateDatetime(Date recCreateDatetime) {
		this.recCreateDatetime = recCreateDatetime;
	}

	@OneToMany(fetch = FetchType.LAZY)
	@JoinColumn(name = "credit_detail_id", updatable = false)
	public Set<CreditDetailTax> getCreditDetailTaxes() {
		return this.creditDetailTaxes;
	}

	public void setCreditDetailTaxes(Set<CreditDetailTax> creditDetailTaxes) {
		this.creditDetailTaxes = creditDetailTaxes;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "credit_header_id")
	public CreditHeader getCreditHeader() {
		return this.creditHeader;
	}

	public void setCreditHeader(CreditHeader creditHeader) {
		this.creditHeader = creditHeader;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "order_item_detail_id")
	public OrderItemDetail getOrderItemDetail() {
		return this.orderItemDetail;
	}

	public void setOrderItemDetail(OrderItemDetail orderItemDetail) {
		this.orderItemDetail = orderItemDetail;
	}

}
