/*
 * Copyright 2007-2010 JadaSite.

 * This file is part of JadaSite.
 
 * JadaSite is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.

 * JadaSite is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.

 * You should have received a copy of the GNU General Public License
 * along with JadaSite.  If not, see <http://www.gnu.org/licenses/>.
 */

package com.jada.jpa.entity;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CreditHeader generated by hbm2java
 */
@Entity
@Table(name = "credit_header")
public class CreditHeader implements java.io.Serializable {
	private static final long serialVersionUID = -6678359372639134682L;
	private Long creditHeaderId;
	private String creditNum;
	private String updateInventory;
	private Float shippingTotal;
	private Float creditTotal;
	private String creditStatus;
	private Date creditDate;
	private String recUpdateBy;
	private Date recUpdateDatetime;
	private String recCreateBy;
	private Date recCreateDatetime;
	private Set<CreditDetail> creditDetails = new HashSet<CreditDetail>(0);
	private Set<CreditDetailTax> creditTaxes = new HashSet<CreditDetailTax>(0);
	private Set<OrderTracking> creditTrackings = new HashSet<OrderTracking>(0);
	private PaymentTran paymentTran;
	private PaymentTran voidPaymentTran;
	private OrderHeader orderHeader;
	private InvoiceHeader invoiceHeader;

	public CreditHeader() {
	}

	public CreditHeader(String creditNum, String updateInventory,
			Float shippingTotal, Float creditTotal, String creditStatus,
			Date creditDate, String recUpdateBy, Date recUpdateDatetime,
			String recCreateBy, Date recCreateDatetime) {
		this.creditNum = creditNum;
		this.updateInventory = updateInventory;
		this.shippingTotal = shippingTotal;
		this.creditTotal = creditTotal;
		this.creditStatus = creditStatus;
		this.creditDate = creditDate;
		this.recUpdateBy = recUpdateBy;
		this.recUpdateDatetime = recUpdateDatetime;
		this.recCreateBy = recCreateBy;
		this.recCreateDatetime = recCreateDatetime;
	}

	public CreditHeader(String creditNum, String updateInventory,
			Float shippingTotal, Float creditTotal, String creditStatus,
			Date creditDate, String recUpdateBy, Date recUpdateDatetime,
			String recCreateBy, Date recCreateDatetime,
			Set<CreditDetail> creditDetails, Set<CreditDetailTax> creditTaxes,
			Set<OrderTracking> creditTrackings, PaymentTran paymentTran,
			PaymentTran voidPaymentTran, OrderHeader orderHeader, InvoiceHeader invoiceHeader) {
		this.creditNum = creditNum;
		this.updateInventory = updateInventory;
		this.shippingTotal = shippingTotal;
		this.creditTotal = creditTotal;
		this.creditStatus = creditStatus;
		this.creditDate = creditDate;
		this.recUpdateBy = recUpdateBy;
		this.recUpdateDatetime = recUpdateDatetime;
		this.recCreateBy = recCreateBy;
		this.recCreateDatetime = recCreateDatetime;
		this.creditDetails = creditDetails;
		this.creditTaxes = creditTaxes;
		this.creditTrackings = creditTrackings;
		this.paymentTran = paymentTran;
		this.voidPaymentTran = voidPaymentTran;
		this.orderHeader = orderHeader;
		this.invoiceHeader = invoiceHeader;
	}

	@Id
	@GeneratedValue
	@Column(name = "credit_header_id", nullable = false)
	public Long getCreditHeaderId() {
		return this.creditHeaderId;
	}

	public void setCreditHeaderId(Long creditHeaderId) {
		this.creditHeaderId = creditHeaderId;
	}

	@Column(name = "credit_num", nullable = false, length = 20)
	public String getCreditNum() {
		return this.creditNum;
	}

	public void setCreditNum(String creditNum) {
		this.creditNum = creditNum;
	}

	@Column(name = "update_inventory", nullable = false, length = 1)
	public String getUpdateInventory() {
		return this.updateInventory;
	}

	public void setUpdateInventory(String updateInventory) {
		this.updateInventory = updateInventory;
	}

	@Column(name = "shipping_total", nullable = false)
	public Float getShippingTotal() {
		return this.shippingTotal;
	}

	public void setShippingTotal(Float shippingTotal) {
		this.shippingTotal = shippingTotal;
	}

	@Column(name = "credit_total", nullable = false)
	public Float getCreditTotal() {
		return this.creditTotal;
	}

	public void setCreditTotal(Float creditTotal) {
		this.creditTotal = creditTotal;
	}

	@Column(name = "credit_status", nullable = false, length = 1)
	public String getCreditStatus() {
		return this.creditStatus;
	}

	public void setCreditStatus(String creditStatus) {
		this.creditStatus = creditStatus;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "credit_date", nullable = false)
	public Date getCreditDate() {
		return this.creditDate;
	}

	public void setCreditDate(Date creditDate) {
		this.creditDate = creditDate;
	}

	@Column(name = "rec_update_by", nullable = false, length = 20)
	public String getRecUpdateBy() {
		return this.recUpdateBy;
	}

	public void setRecUpdateBy(String recUpdateBy) {
		this.recUpdateBy = recUpdateBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "rec_update_datetime", nullable = false)
	public Date getRecUpdateDatetime() {
		return this.recUpdateDatetime;
	}

	public void setRecUpdateDatetime(Date recUpdateDatetime) {
		this.recUpdateDatetime = recUpdateDatetime;
	}

	@Column(name = "rec_create_by", nullable = false, length = 20)
	public String getRecCreateBy() {
		return this.recCreateBy;
	}

	public void setRecCreateBy(String recCreateBy) {
		this.recCreateBy = recCreateBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "rec_create_datetime", nullable = false)
	public Date getRecCreateDatetime() {
		return this.recCreateDatetime;
	}

	public void setRecCreateDatetime(Date recCreateDatetime) {
		this.recCreateDatetime = recCreateDatetime;
	}

	@OneToMany(fetch = FetchType.LAZY)
	@JoinColumn(name = "credit_header_id", updatable = false)
	public Set<CreditDetail> getCreditDetails() {
		return this.creditDetails;
	}

	public void setCreditDetails(Set<CreditDetail> creditDetails) {
		this.creditDetails = creditDetails;
	}

	@OneToMany(fetch = FetchType.LAZY)
	@JoinColumn(name = "credit_header_id", updatable = false)
	public Set<CreditDetailTax> getCreditTaxes() {
		return this.creditTaxes;
	}

	public void setCreditTaxes(Set<CreditDetailTax> creditTaxes) {
		this.creditTaxes = creditTaxes;
	}

	@OneToMany(fetch = FetchType.LAZY)
	@JoinColumn(name = "credit_header_id", updatable = false)
	public Set<OrderTracking> getCreditTrackings() {
		return this.creditTrackings;
	}

	public void setCreditTrackings(Set<OrderTracking> creditTrackings) {
		this.creditTrackings = creditTrackings;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "payment_tran_id")
	public PaymentTran getPaymentTran() {
		return this.paymentTran;
	}

	public void setPaymentTran(PaymentTran paymentTran) {
		this.paymentTran = paymentTran;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "void_payment_tran_id")
	public PaymentTran getVoidPaymentTran() {
		return this.voidPaymentTran;
	}

	public void setVoidPaymentTran(PaymentTran voidPaymentTran) {
		this.voidPaymentTran = voidPaymentTran;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "order_header_id")
	public OrderHeader getOrderHeader() {
		return this.orderHeader;
	}

	public void setOrderHeader(OrderHeader orderHeader) {
		this.orderHeader = orderHeader;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "invoice_header_id")
	public InvoiceHeader getInvoiceHeader() {
		return this.invoiceHeader;
	}

	public void setInvoiceHeader(InvoiceHeader invoiceHeader) {
		this.invoiceHeader = invoiceHeader;
	}
}
