/*
 * Copyright 2007-2010 JadaSite.

 * This file is part of JadaSite.
 
 * JadaSite is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.

 * JadaSite is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.

 * You should have received a copy of the GNU General Public License
 * along with JadaSite.  If not, see <http://www.gnu.org/licenses/>.
 */

package com.jada.jpa.entity;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Customer generated by hbm2java
 */
@Entity
@Table(name = "customer")
public class Customer implements java.io.Serializable {

	private static final long serialVersionUID = 7759859483506749232L;
	private Long custId;
	private String custEmail;
	private String custPassword;
	private String custPublicName;
	private String custSource;
	private String custSourceRef;
	private String custComments;
	private Character active;
	private String recUpdateBy;
	private Date recUpdateDatetime;
	private String recCreateBy;
	private Date recCreateDatetime;
	private CustomerAddress custAddress;
	private String siteId;
	private Set<CustomerAddress> custAddresses = new HashSet<CustomerAddress>(0);
	private Set<CustomerCreditCard> custCreditCards = new HashSet<CustomerCreditCard>(
			0);
	private Set<OrderHeader> orderHeaders = new HashSet<OrderHeader>(0);
	private CustomerClass customerClass;
	private Site site;
	private SiteDomain siteDomain;

	public Customer() {
	}

	public Customer(String custEmail, String custPublicName, String custSource,
			String custSourceRef, Character active, String recUpdateBy,
			Date recUpdateDatetime, String recCreateBy, Date recCreateDatetime,
			CustomerAddress custAddress, String siteId, Site site,
			SiteDomain siteDomain) {
		this.custEmail = custEmail;
		this.custPublicName = custPublicName;
		this.custSource = custSource;
		this.custSourceRef = custSourceRef;
		this.active = active;
		this.recUpdateBy = recUpdateBy;
		this.recUpdateDatetime = recUpdateDatetime;
		this.recCreateBy = recCreateBy;
		this.recCreateDatetime = recCreateDatetime;
		this.custAddress = custAddress;
		this.siteId = siteId;
		this.site = site;
		this.siteDomain = siteDomain;
	}

	public Customer(String custEmail, String custPassword,
			String custPublicName, String custSource, String custSourceRef,
			String custComments, Character active, String recUpdateBy,
			Date recUpdateDatetime, String recCreateBy, Date recCreateDatetime,
			CustomerAddress custAddress, String siteId,
			Set<CustomerAddress> custAddresses,
			Set<CustomerCreditCard> custCreditCards,
			Set<OrderHeader> orderHeaders, CustomerClass customerClass,
			Site site, SiteDomain siteDomain) {
		this.custEmail = custEmail;
		this.custPassword = custPassword;
		this.custPublicName = custPublicName;
		this.custSource = custSource;
		this.custSourceRef = custSourceRef;
		this.custComments = custComments;
		this.active = active;
		this.recUpdateBy = recUpdateBy;
		this.recUpdateDatetime = recUpdateDatetime;
		this.recCreateBy = recCreateBy;
		this.recCreateDatetime = recCreateDatetime;
		this.custAddress = custAddress;
		this.siteId = siteId;
		this.custAddresses = custAddresses;
		this.custCreditCards = custCreditCards;
		this.orderHeaders = orderHeaders;
		this.customerClass = customerClass;
		this.site = site;
		this.siteDomain = siteDomain;
	}

	@Id
	@GeneratedValue
	@Column(name = "cust_id", nullable = false)
	public Long getCustId() {
		return this.custId;
	}

	public void setCustId(Long custId) {
		this.custId = custId;
	}

	@Column(name = "cust_email", nullable = false)
	public String getCustEmail() {
		return this.custEmail;
	}

	public void setCustEmail(String custEmail) {
		this.custEmail = custEmail;
	}

	@Column(name = "cust_password", length = 128)
	public String getCustPassword() {
		return this.custPassword;
	}

	public void setCustPassword(String custPassword) {
		this.custPassword = custPassword;
	}

	@Column(name = "cust_public_name", nullable = false, length = 20)
	public String getCustPublicName() {
		return this.custPublicName;
	}

	public void setCustPublicName(String custPublicName) {
		this.custPublicName = custPublicName;
	}

	@Column(name = "cust_source", nullable = false, length = 10)
	public String getCustSource() {
		return this.custSource;
	}

	public void setCustSource(String custSource) {
		this.custSource = custSource;
	}

	@Column(name = "cust_source_ref", nullable = false, length = 20)
	public String getCustSourceRef() {
		return this.custSourceRef;
	}

	public void setCustSourceRef(String custSourceRef) {
		this.custSourceRef = custSourceRef;
	}

	@Column(name = "cust_comments", length = 100000000)
	public String getCustComments() {
		return this.custComments;
	}

	public void setCustComments(String custComments) {
		this.custComments = custComments;
	}

	@Column(name = "active", nullable = false, length = 1)
	public Character getActive() {
		return this.active;
	}

	public void setActive(Character active) {
		this.active = active;
	}

	@Column(name = "rec_update_by", nullable = false, length = 20)
	public String getRecUpdateBy() {
		return this.recUpdateBy;
	}

	public void setRecUpdateBy(String recUpdateBy) {
		this.recUpdateBy = recUpdateBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "rec_update_datetime", nullable = false)
	public Date getRecUpdateDatetime() {
		return this.recUpdateDatetime;
	}

	public void setRecUpdateDatetime(Date recUpdateDatetime) {
		this.recUpdateDatetime = recUpdateDatetime;
	}

	@Column(name = "rec_create_by", nullable = false, length = 20)
	public String getRecCreateBy() {
		return this.recCreateBy;
	}

	public void setRecCreateBy(String recCreateBy) {
		this.recCreateBy = recCreateBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "rec_create_datetime", nullable = false)
	public Date getRecCreateDatetime() {
		return this.recCreateDatetime;
	}

	public void setRecCreateDatetime(Date recCreateDatetime) {
		this.recCreateDatetime = recCreateDatetime;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cust_address_id", nullable = false)
	public CustomerAddress getCustAddress() {
		return this.custAddress;
	}

	public void setCustAddress(CustomerAddress custAddress) {
		this.custAddress = custAddress;
	}

	@Column(name = "site_id", nullable = false, insertable = false, updatable = false, length = 20)
	public String getSiteId() {
		return this.siteId;
	}

	public void setSiteId(String siteId) {
		this.siteId = siteId;
	}

	@OneToMany(fetch = FetchType.LAZY)
	@JoinColumn(name = "cust_id")
	public Set<CustomerAddress> getCustAddresses() {
		return this.custAddresses;
	}

	public void setCustAddresses(Set<CustomerAddress> custAddresses) {
		this.custAddresses = custAddresses;
	}

	@OneToMany(fetch = FetchType.LAZY)
	@JoinColumn(name = "cust_id")
	public Set<CustomerCreditCard> getCustCreditCards() {
		return this.custCreditCards;
	}

	public void setCustCreditCards(Set<CustomerCreditCard> custCreditCards) {
		this.custCreditCards = custCreditCards;
	}

	@OneToMany(fetch = FetchType.LAZY)
	@JoinColumn(name = "cust_id", updatable = false)
	public Set<OrderHeader> getOrderHeaders() {
		return this.orderHeaders;
	}

	public void setOrderHeaders(Set<OrderHeader> orderHeaders) {
		this.orderHeaders = orderHeaders;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cust_class_id")
	public CustomerClass getCustomerClass() {
		return this.customerClass;
	}

	public void setCustomerClass(CustomerClass customerClass) {
		this.customerClass = customerClass;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "site_id", nullable = false)
	public Site getSite() {
		return this.site;
	}

	public void setSite(Site site) {
		this.site = site;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "site_domain_id", nullable = false)
	public SiteDomain getSiteDomain() {
		return this.siteDomain;
	}

	public void setSiteDomain(SiteDomain siteDomain) {
		this.siteDomain = siteDomain;
	}

}
