/*
 * Copyright 2007-2010 JadaSite.

 * This file is part of JadaSite.
 
 * JadaSite is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.

 * JadaSite is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.

 * You should have received a copy of the GNU General Public License
 * along with JadaSite.  If not, see <http://www.gnu.org/licenses/>.
 */

package com.jada.jpa.entity;

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CustomAttributeOptionCurrency generated by hbm2java
 */
@Entity
@Table(name = "custom_attrib_option_currency")
public class CustomAttributeOptionCurrency implements java.io.Serializable {

	private static final long serialVersionUID = -8308961174266837506L;
	private Long customAttribOptionCurrId;
	private String customAttribValue;
	private String recUpdateBy;
	private Date recUpdateDatetime;
	private String recCreateBy;
	private Date recCreateDatetime;
	private CustomAttributeOption customAttributeOption;
	private SiteCurrencyClass siteCurrencyClass;

	public CustomAttributeOptionCurrency() {
	}

	public CustomAttributeOptionCurrency(String recUpdateBy,
			Date recUpdateDatetime, String recCreateBy, Date recCreateDatetime) {
		this.recUpdateBy = recUpdateBy;
		this.recUpdateDatetime = recUpdateDatetime;
		this.recCreateBy = recCreateBy;
		this.recCreateDatetime = recCreateDatetime;
	}

	public CustomAttributeOptionCurrency(String customAttribValue,
			String recUpdateBy, Date recUpdateDatetime, String recCreateBy,
			Date recCreateDatetime,
			CustomAttributeOption customAttributeOption,
			SiteCurrencyClass siteCurrencyClass) {
		this.customAttribValue = customAttribValue;
		this.recUpdateBy = recUpdateBy;
		this.recUpdateDatetime = recUpdateDatetime;
		this.recCreateBy = recCreateBy;
		this.recCreateDatetime = recCreateDatetime;
		this.customAttributeOption = customAttributeOption;
		this.siteCurrencyClass = siteCurrencyClass;
	}

	@Id
	@GeneratedValue
	@Column(name = "custom_attrib_option_curr_id", nullable = false)
	public Long getCustomAttribOptionCurrId() {
		return this.customAttribOptionCurrId;
	}

	public void setCustomAttribOptionCurrId(Long customAttribOptionCurrId) {
		this.customAttribOptionCurrId = customAttribOptionCurrId;
	}

	@Column(name = "custom_attrib_value", length = 40)
	public String getCustomAttribValue() {
		return this.customAttribValue;
	}

	public void setCustomAttribValue(String customAttribValue) {
		this.customAttribValue = customAttribValue;
	}

	@Column(name = "rec_update_by", nullable = false, length = 20)
	public String getRecUpdateBy() {
		return this.recUpdateBy;
	}

	public void setRecUpdateBy(String recUpdateBy) {
		this.recUpdateBy = recUpdateBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "rec_update_datetime", nullable = false)
	public Date getRecUpdateDatetime() {
		return this.recUpdateDatetime;
	}

	public void setRecUpdateDatetime(Date recUpdateDatetime) {
		this.recUpdateDatetime = recUpdateDatetime;
	}

	@Column(name = "rec_create_by", nullable = false, length = 20)
	public String getRecCreateBy() {
		return this.recCreateBy;
	}

	public void setRecCreateBy(String recCreateBy) {
		this.recCreateBy = recCreateBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "rec_create_datetime", nullable = false)
	public Date getRecCreateDatetime() {
		return this.recCreateDatetime;
	}

	public void setRecCreateDatetime(Date recCreateDatetime) {
		this.recCreateDatetime = recCreateDatetime;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "custom_attrib_option_id")
	public CustomAttributeOption getCustomAttributeOption() {
		return this.customAttributeOption;
	}

	public void setCustomAttributeOption(
			CustomAttributeOption customAttributeOption) {
		this.customAttributeOption = customAttributeOption;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "site_currency_class_id")
	public SiteCurrencyClass getSiteCurrencyClass() {
		return this.siteCurrencyClass;
	}

	public void setSiteCurrencyClass(SiteCurrencyClass siteCurrencyClass) {
		this.siteCurrencyClass = siteCurrencyClass;
	}

}
