/*
 * Copyright 2007-2010 JadaSite.

 * This file is part of JadaSite.
 
 * JadaSite is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.

 * JadaSite is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.

 * You should have received a copy of the GNU General Public License
 * along with JadaSite.  If not, see <http://www.gnu.org/licenses/>.
 */

package com.jada.jpa.entity;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OrderBy;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * CustomAttributeGroup generated by hbm2java
 */
@Entity
@Table(name = "custom_attrib_group", uniqueConstraints = @UniqueConstraint(columnNames = {
		"custom_attrib_group_name", "site_id" }))
public class CustomAttributeGroup implements java.io.Serializable {
	private static final long serialVersionUID = -2335087121740675224L;
	private Long customAttribGroupId;
	private String customAttribGroupName;
	private String recUpdateBy;
	private Date recUpdateDatetime;
	private String recCreateBy;
	private Date recCreateDatetime;
	private String siteId;
	private Set<CustomAttributeDetail> customAttributeDetails = new HashSet<CustomAttributeDetail>(
			0);
	private Site site;

	public CustomAttributeGroup() {
	}

	public CustomAttributeGroup(String customAttribGroupName,
			String recUpdateBy, Date recUpdateDatetime, String recCreateBy,
			Date recCreateDatetime, String siteId, Site site) {
		this.customAttribGroupName = customAttribGroupName;
		this.recUpdateBy = recUpdateBy;
		this.recUpdateDatetime = recUpdateDatetime;
		this.recCreateBy = recCreateBy;
		this.recCreateDatetime = recCreateDatetime;
		this.siteId = siteId;
		this.site = site;
	}

	public CustomAttributeGroup(String customAttribGroupName,
			String recUpdateBy, Date recUpdateDatetime, String recCreateBy,
			Date recCreateDatetime, String siteId,
			Set<CustomAttributeDetail> customAttributeDetails, Site site) {
		this.customAttribGroupName = customAttribGroupName;
		this.recUpdateBy = recUpdateBy;
		this.recUpdateDatetime = recUpdateDatetime;
		this.recCreateBy = recCreateBy;
		this.recCreateDatetime = recCreateDatetime;
		this.siteId = siteId;
		this.customAttributeDetails = customAttributeDetails;
		this.site = site;
	}

	@Id
	@GeneratedValue
	@Column(name = "custom_attrib_group_id", nullable = false)
	public Long getCustomAttribGroupId() {
		return this.customAttribGroupId;
	}

	public void setCustomAttribGroupId(Long customAttribGroupId) {
		this.customAttribGroupId = customAttribGroupId;
	}

	@Column(name = "custom_attrib_group_name", nullable = false, length = 40)
	public String getCustomAttribGroupName() {
		return this.customAttribGroupName;
	}

	public void setCustomAttribGroupName(String customAttribGroupName) {
		this.customAttribGroupName = customAttribGroupName;
	}

	@Column(name = "rec_update_by", nullable = false, length = 20)
	public String getRecUpdateBy() {
		return this.recUpdateBy;
	}

	public void setRecUpdateBy(String recUpdateBy) {
		this.recUpdateBy = recUpdateBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "rec_update_datetime", nullable = false)
	public Date getRecUpdateDatetime() {
		return this.recUpdateDatetime;
	}

	public void setRecUpdateDatetime(Date recUpdateDatetime) {
		this.recUpdateDatetime = recUpdateDatetime;
	}

	@Column(name = "rec_create_by", nullable = false, length = 20)
	public String getRecCreateBy() {
		return this.recCreateBy;
	}

	public void setRecCreateBy(String recCreateBy) {
		this.recCreateBy = recCreateBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "rec_create_datetime", nullable = false)
	public Date getRecCreateDatetime() {
		return this.recCreateDatetime;
	}

	public void setRecCreateDatetime(Date recCreateDatetime) {
		this.recCreateDatetime = recCreateDatetime;
	}

	@Column(name = "site_id", nullable = false, insertable = false, updatable = false, length = 20)
	public String getSiteId() {
		return this.siteId;
	}

	public void setSiteId(String siteId) {
		this.siteId = siteId;
	}

	@OneToMany(fetch = FetchType.LAZY)
	@OrderBy(value="seqNum")
	@JoinColumn(name = "custom_attrib_group_id")
	public Set<CustomAttributeDetail> getCustomAttributeDetails() {
		return this.customAttributeDetails;
	}

	public void setCustomAttributeDetails(
			Set<CustomAttributeDetail> customAttributeDetails) {
		this.customAttributeDetails = customAttributeDetails;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "site_id", nullable = false)
	public Site getSite() {
		return this.site;
	}

	public void setSite(Site site) {
		this.site = site;
	}

}
