/*
 * Copyright 2007-2010 JadaSite.

 * This file is part of JadaSite.
 
 * JadaSite is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.

 * JadaSite is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.

 * You should have received a copy of the GNU General Public License
 * along with JadaSite.  If not, see <http://www.gnu.org/licenses/>.
 */

package com.jada.jpa.entity;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CustomAttributeOption generated by hbm2java
 */
@Entity
@Table(name = "custom_attrib_option")
public class CustomAttributeOption implements java.io.Serializable {

	private static final long serialVersionUID = 569761833060880935L;
	private Long customAttribOptionId;
	private String customAttribSkuCode;
	private String recUpdateBy;
	private Date recUpdateDatetime;
	private String recCreateBy;
	private Date recCreateDatetime;
	private CustomAttributeOptionLanguage customAttributeOptionLanguage;
	private CustomAttributeOptionCurrency customAttributeOptionCurrency;
	private Set<CustomAttributeOptionLanguage> customAttributeOptionLanguages = new HashSet<CustomAttributeOptionLanguage>(
			0);
	private Set<CustomAttributeOptionCurrency> customAttributeOptionCurrencies = new HashSet<CustomAttributeOptionCurrency>(
			0);
	private CustomAttribute customAttribute;

	public CustomAttributeOption() {
	}

	public CustomAttributeOption(String customAttribSkuCode,
			String recUpdateBy, Date recUpdateDatetime, String recCreateBy,
			Date recCreateDatetime, CustomAttribute customAttribute) {
		this.customAttribSkuCode = customAttribSkuCode;
		this.recUpdateBy = recUpdateBy;
		this.recUpdateDatetime = recUpdateDatetime;
		this.recCreateBy = recCreateBy;
		this.recCreateDatetime = recCreateDatetime;
		this.customAttribute = customAttribute;
	}

	public CustomAttributeOption(String customAttribSkuCode,
			String recUpdateBy, Date recUpdateDatetime, String recCreateBy,
			Date recCreateDatetime,
			CustomAttributeOptionLanguage customAttributeOptionLanguage,
			CustomAttributeOptionCurrency customAttributeOptionCurrency,
			Set<CustomAttributeOptionLanguage> customAttributeOptionLanguages,
			Set<CustomAttributeOptionCurrency> customAttributeOptionCurrencies,
			CustomAttribute customAttribute) {
		this.customAttribSkuCode = customAttribSkuCode;
		this.recUpdateBy = recUpdateBy;
		this.recUpdateDatetime = recUpdateDatetime;
		this.recCreateBy = recCreateBy;
		this.recCreateDatetime = recCreateDatetime;
		this.customAttributeOptionLanguage = customAttributeOptionLanguage;
		this.customAttributeOptionCurrency = customAttributeOptionCurrency;
		this.customAttributeOptionLanguages = customAttributeOptionLanguages;
		this.customAttributeOptionCurrencies = customAttributeOptionCurrencies;
		this.customAttribute = customAttribute;
	}

	@Id
	@GeneratedValue
	@Column(name = "custom_attrib_option_id", nullable = false)
	public Long getCustomAttribOptionId() {
		return this.customAttribOptionId;
	}

	public void setCustomAttribOptionId(Long customAttribOptionId) {
		this.customAttribOptionId = customAttribOptionId;
	}

	@Column(name = "custom_attrib_sku_code", nullable = false, length = 3)
	public String getCustomAttribSkuCode() {
		return this.customAttribSkuCode;
	}

	public void setCustomAttribSkuCode(String customAttribSkuCode) {
		this.customAttribSkuCode = customAttribSkuCode;
	}

	@Column(name = "rec_update_by", nullable = false, length = 20)
	public String getRecUpdateBy() {
		return this.recUpdateBy;
	}

	public void setRecUpdateBy(String recUpdateBy) {
		this.recUpdateBy = recUpdateBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "rec_update_datetime", nullable = false)
	public Date getRecUpdateDatetime() {
		return this.recUpdateDatetime;
	}

	public void setRecUpdateDatetime(Date recUpdateDatetime) {
		this.recUpdateDatetime = recUpdateDatetime;
	}

	@Column(name = "rec_create_by", nullable = false, length = 20)
	public String getRecCreateBy() {
		return this.recCreateBy;
	}

	public void setRecCreateBy(String recCreateBy) {
		this.recCreateBy = recCreateBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "rec_create_datetime", nullable = false)
	public Date getRecCreateDatetime() {
		return this.recCreateDatetime;
	}

	public void setRecCreateDatetime(Date recCreateDatetime) {
		this.recCreateDatetime = recCreateDatetime;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "custom_attrib_option_lang_id")
	public CustomAttributeOptionLanguage getCustomAttributeOptionLanguage() {
		return this.customAttributeOptionLanguage;
	}

	public void setCustomAttributeOptionLanguage(
			CustomAttributeOptionLanguage customAttributeOptionLanguage) {
		this.customAttributeOptionLanguage = customAttributeOptionLanguage;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "custom_attrib_option_curr_id")
	public CustomAttributeOptionCurrency getCustomAttributeOptionCurrency() {
		return this.customAttributeOptionCurrency;
	}

	public void setCustomAttributeOptionCurrency(
			CustomAttributeOptionCurrency customAttributeOptionCurrency) {
		this.customAttributeOptionCurrency = customAttributeOptionCurrency;
	}

	@OneToMany(fetch = FetchType.LAZY)
	@JoinColumn(name = "custom_attrib_option_id", updatable = false)
	public Set<CustomAttributeOptionLanguage> getCustomAttributeOptionLanguages() {
		return this.customAttributeOptionLanguages;
	}

	public void setCustomAttributeOptionLanguages(
			Set<CustomAttributeOptionLanguage> customAttributeOptionLanguages) {
		this.customAttributeOptionLanguages = customAttributeOptionLanguages;
	}

	@OneToMany(fetch = FetchType.LAZY)
	@JoinColumn(name = "custom_attrib_option_id", updatable = false)
	public Set<CustomAttributeOptionCurrency> getCustomAttributeOptionCurrencies() {
		return this.customAttributeOptionCurrencies;
	}

	public void setCustomAttributeOptionCurrencies(
			Set<CustomAttributeOptionCurrency> customAttributeOptionCurrencies) {
		this.customAttributeOptionCurrencies = customAttributeOptionCurrencies;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "custom_attrib_id", nullable = false)
	public CustomAttribute getCustomAttribute() {
		return this.customAttribute;
	}

	public void setCustomAttribute(CustomAttribute customAttribute) {
		this.customAttribute = customAttribute;
	}

}
