/*
 * Copyright 2007-2010 JadaSite.

 * This file is part of JadaSite.
 
 * JadaSite is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.

 * JadaSite is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.

 * You should have received a copy of the GNU General Public License
 * along with JadaSite.  If not, see <http://www.gnu.org/licenses/>.
 */

package com.jada.jpa.entity;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OrderBy;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CustomAttribute generated by hbm2java
 */
@Entity
@Table(name = "custom_attrib")
public class CustomAttribute implements java.io.Serializable {
	private static final long serialVersionUID = -2155875566300315049L;
	private Long customAttribId;
	private String customAttribName;
	private char itemCompare;
	private char customAttribDataTypeCode;
	private char customAttribTypeCode;
	private char systemRecord;
	private String recUpdateBy;
	private Date recUpdateDatetime;
	private String recCreateBy;
	private Date recCreateDatetime;
	private CustomAttributeLanguage customAttributeLanguage;
	private Set<CustomAttributeLanguage> customAttributeLanguages = new HashSet<CustomAttributeLanguage>(
			0);
	private Set<CustomAttributeOption> customAttributeOptions = new HashSet<CustomAttributeOption>(
			0);
	private Site site;

	public CustomAttribute() {
	}

	public CustomAttribute(char itemCompare, char customAttribDataTypeCode,
			char customAttribTypeCode, char systemRecord, String recUpdateBy,
			Date recUpdateDatetime, String recCreateBy, Date recCreateDatetime,
			CustomAttributeLanguage customAttributeLanguage, Site site) {
		this.itemCompare = itemCompare;
		this.customAttribDataTypeCode = customAttribDataTypeCode;
		this.customAttribTypeCode = customAttribTypeCode;
		this.systemRecord = systemRecord;
		this.recUpdateBy = recUpdateBy;
		this.recUpdateDatetime = recUpdateDatetime;
		this.recCreateBy = recCreateBy;
		this.recCreateDatetime = recCreateDatetime;
		this.customAttributeLanguage = customAttributeLanguage;
		this.site = site;
	}

	public CustomAttribute(String customAttribName, char itemCompare,
			char customAttribDataTypeCode, char customAttribTypeCode,
			char systemRecord, String recUpdateBy, Date recUpdateDatetime,
			String recCreateBy, Date recCreateDatetime,
			CustomAttributeLanguage customAttributeLanguage,
			Set<CustomAttributeLanguage> customAttributeLanguages,
			Set<CustomAttributeOption> customAttributeOptions, Site site) {
		this.customAttribName = customAttribName;
		this.itemCompare = itemCompare;
		this.customAttribDataTypeCode = customAttribDataTypeCode;
		this.customAttribTypeCode = customAttribTypeCode;
		this.systemRecord = systemRecord;
		this.recUpdateBy = recUpdateBy;
		this.recUpdateDatetime = recUpdateDatetime;
		this.recCreateBy = recCreateBy;
		this.recCreateDatetime = recCreateDatetime;
		this.customAttributeLanguage = customAttributeLanguage;
		this.customAttributeLanguages = customAttributeLanguages;
		this.customAttributeOptions = customAttributeOptions;
		this.site = site;
	}

	@Id
	@GeneratedValue
	@Column(name = "custom_attrib_id", nullable = false)
	public Long getCustomAttribId() {
		return this.customAttribId;
	}

	public void setCustomAttribId(Long customAttribId) {
		this.customAttribId = customAttribId;
	}

	@Column(name = "custom_attrib_name", length = 40)
	public String getCustomAttribName() {
		return this.customAttribName;
	}

	public void setCustomAttribName(String customAttribName) {
		this.customAttribName = customAttribName;
	}

	@Column(name = "item_compare", nullable = false, length = 1)
	public char getItemCompare() {
		return this.itemCompare;
	}

	public void setItemCompare(char itemCompare) {
		this.itemCompare = itemCompare;
	}

	@Column(name = "custom_attrib_data_type_code", nullable = false, length = 1)
	public char getCustomAttribDataTypeCode() {
		return this.customAttribDataTypeCode;
	}

	public void setCustomAttribDataTypeCode(char customAttribDataTypeCode) {
		this.customAttribDataTypeCode = customAttribDataTypeCode;
	}

	@Column(name = "custom_attrib_type_code", nullable = false, length = 1)
	public char getCustomAttribTypeCode() {
		return this.customAttribTypeCode;
	}

	public void setCustomAttribTypeCode(char customAttribTypeCode) {
		this.customAttribTypeCode = customAttribTypeCode;
	}

	@Column(name = "system_record", nullable = false, length = 1)
	public char getSystemRecord() {
		return this.systemRecord;
	}

	public void setSystemRecord(char systemRecord) {
		this.systemRecord = systemRecord;
	}

	@Column(name = "rec_update_by", nullable = false, length = 20)
	public String getRecUpdateBy() {
		return this.recUpdateBy;
	}

	public void setRecUpdateBy(String recUpdateBy) {
		this.recUpdateBy = recUpdateBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "rec_update_datetime", nullable = false)
	public Date getRecUpdateDatetime() {
		return this.recUpdateDatetime;
	}

	public void setRecUpdateDatetime(Date recUpdateDatetime) {
		this.recUpdateDatetime = recUpdateDatetime;
	}

	@Column(name = "rec_create_by", nullable = false, length = 20)
	public String getRecCreateBy() {
		return this.recCreateBy;
	}

	public void setRecCreateBy(String recCreateBy) {
		this.recCreateBy = recCreateBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "rec_create_datetime", nullable = false)
	public Date getRecCreateDatetime() {
		return this.recCreateDatetime;
	}

	public void setRecCreateDatetime(Date recCreateDatetime) {
		this.recCreateDatetime = recCreateDatetime;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "custom_attrib_lang_id", nullable = false)
	public CustomAttributeLanguage getCustomAttributeLanguage() {
		return this.customAttributeLanguage;
	}

	public void setCustomAttributeLanguage(
			CustomAttributeLanguage customAttributeLanguage) {
		this.customAttributeLanguage = customAttributeLanguage;
	}

	@OneToMany(fetch = FetchType.LAZY)
	@JoinColumn(name = "custom_attrib_id", updatable = false)
	public Set<CustomAttributeLanguage> getCustomAttributeLanguages() {
		return this.customAttributeLanguages;
	}

	public void setCustomAttributeLanguages(
			Set<CustomAttributeLanguage> customAttributeLanguages) {
		this.customAttributeLanguages = customAttributeLanguages;
	}

	@OneToMany(fetch = FetchType.LAZY)
	@JoinColumn(name = "custom_attrib_id", updatable = false)
	@OrderBy(value="customAttribOptionId")
	public Set<CustomAttributeOption> getCustomAttributeOptions() {
		return this.customAttributeOptions;
	}

	public void setCustomAttributeOptions(
			Set<CustomAttributeOption> customAttributeOptions) {
		this.customAttributeOptions = customAttributeOptions;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "site_id", nullable = false)
	public Site getSite() {
		return this.site;
	}

	public void setSite(Site site) {
		this.site = site;
	}

}
