/*
 * Copyright 2007-2010 JadaSite.

 * This file is part of JadaSite.
 
 * JadaSite is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.

 * JadaSite is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.

 * You should have received a copy of the GNU General Public License
 * along with JadaSite.  If not, see <http://www.gnu.org/licenses/>.
 */

package com.jada.jpa.entity;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OrderBy;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * HomePage generated by hbm2java
 */
@Entity
@Table(name = "home_page")
public class HomePage implements java.io.Serializable {

	private static final long serialVersionUID = 7763684495216474122L;
	private Long homePageId;
	private String recUpdateBy;
	private Date recUpdateDatetime;
	private String recCreateBy;
	private Date recCreateDatetime;
	private HomePageLanguage homePageLanguage;
	private HomePageDetail featureData;
	private Set<HomePageDetail> homePageDetails = new HashSet<HomePageDetail>(0);
	private Set<HomePageLanguage> homePageLanguages = new HashSet<HomePageLanguage>(
			0);

	public HomePage() {
	}

	public HomePage(String recUpdateBy, Date recUpdateDatetime,
			String recCreateBy, Date recCreateDatetime) {
		this.recUpdateBy = recUpdateBy;
		this.recUpdateDatetime = recUpdateDatetime;
		this.recCreateBy = recCreateBy;
		this.recCreateDatetime = recCreateDatetime;
	}

	public HomePage(String recUpdateBy, Date recUpdateDatetime,
			String recCreateBy, Date recCreateDatetime,
			HomePageLanguage homePageLanguage, HomePageDetail featureData,
			Set<HomePageDetail> homePageDetails,
			Set<HomePageLanguage> homePageLanguages) {
		this.recUpdateBy = recUpdateBy;
		this.recUpdateDatetime = recUpdateDatetime;
		this.recCreateBy = recCreateBy;
		this.recCreateDatetime = recCreateDatetime;
		this.homePageLanguage = homePageLanguage;
		this.featureData = featureData;
		this.homePageDetails = homePageDetails;
		this.homePageLanguages = homePageLanguages;
	}

	@Id
	@GeneratedValue
	@Column(name = "home_page_id", nullable = false)
	public Long getHomePageId() {
		return this.homePageId;
	}

	public void setHomePageId(Long homePageId) {
		this.homePageId = homePageId;
	}

	@Column(name = "rec_update_by", nullable = false, length = 20)
	public String getRecUpdateBy() {
		return this.recUpdateBy;
	}

	public void setRecUpdateBy(String recUpdateBy) {
		this.recUpdateBy = recUpdateBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "rec_update_datetime", nullable = false)
	public Date getRecUpdateDatetime() {
		return this.recUpdateDatetime;
	}

	public void setRecUpdateDatetime(Date recUpdateDatetime) {
		this.recUpdateDatetime = recUpdateDatetime;
	}

	@Column(name = "rec_create_by", nullable = false, length = 20)
	public String getRecCreateBy() {
		return this.recCreateBy;
	}

	public void setRecCreateBy(String recCreateBy) {
		this.recCreateBy = recCreateBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "rec_create_datetime", nullable = false)
	public Date getRecCreateDatetime() {
		return this.recCreateDatetime;
	}

	public void setRecCreateDatetime(Date recCreateDatetime) {
		this.recCreateDatetime = recCreateDatetime;
	}

	@ManyToOne(cascade = CascadeType.ALL, fetch = FetchType.LAZY)
	@JoinColumn(name = "home_page_lang_id")
	public HomePageLanguage getHomePageLanguage() {
		return this.homePageLanguage;
	}

	public void setHomePageLanguage(HomePageLanguage homePageLanguage) {
		this.homePageLanguage = homePageLanguage;
	}

	@ManyToOne(cascade = CascadeType.ALL, fetch = FetchType.LAZY)
	@JoinColumn(name = "home_page_feature_id")
	public HomePageDetail getFeatureData() {
		return this.featureData;
	}

	public void setFeatureData(HomePageDetail featureData) {
		this.featureData = featureData;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY)
	@OrderBy(value="seqNum")
	@JoinColumn(name = "home_page_id")
	public Set<HomePageDetail> getHomePageDetails() {
		return this.homePageDetails;
	}

	public void setHomePageDetails(Set<HomePageDetail> homePageDetails) {
		this.homePageDetails = homePageDetails;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "homePage")
	public Set<HomePageLanguage> getHomePageLanguages() {
		return this.homePageLanguages;
	}

	public void setHomePageLanguages(Set<HomePageLanguage> homePageLanguages) {
		this.homePageLanguages = homePageLanguages;
	}

}
