/*
 * Copyright 2007-2010 JadaSite.

 * This file is part of JadaSite.
 
 * JadaSite is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.

 * JadaSite is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.

 * You should have received a copy of the GNU General Public License
 * along with JadaSite.  If not, see <http://www.gnu.org/licenses/>.
 */

package com.jada.jpa.entity;

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * OrderItemDetail generated by hbm2java
 */
@Entity
@Table(name = "ie_profile_detail")
public class IeProfileDetail implements java.io.Serializable {

	private static final long serialVersionUID = 3013689761691407740L;
	private Long ieProfileDetailId;
	private Integer seqNum;
	private String ieProfileGroupName;
	private Integer ieProfileGroupIndex;
	private String ieProfileFieldName;
	private Integer ieProfilePosition;
	private String ieProfileFieldValue;
	private String recUpdateBy;
	private Date recUpdateDatetime;
	private String recCreateBy;
	private Date recCreateDatetime;
	private IeProfileHeader ieProfileHeader;

	public IeProfileDetail() {
	}

	@Id
	@GeneratedValue
	@Column(name = "ie_profile_detail_id", nullable = false)
	public Long getIeProfileDetailId() {
		return this.ieProfileDetailId;
	}

	public void setIeProfileDetailId(Long ieProfileDetailId) {
		this.ieProfileDetailId = ieProfileDetailId;
	}

	@Column(name = "seq_num", nullable = false)
	public Integer getSeqNum() {
		return seqNum;
	}

	public void setSeqNum(Integer seqNum) {
		this.seqNum = seqNum;
	}

	@Column(name = "ie_profile_group_name", nullable = true, length = 80)
	public String getIeProfileGroupName() {
		return ieProfileGroupName;
	}

	public void setIeProfileGroupName(String ieProfileGroupName) {
		this.ieProfileGroupName = ieProfileGroupName;
	}

	@Column(name = "ie_profile_group_index", nullable = true)
	public Integer getIeProfileGroupIndex() {
		return ieProfileGroupIndex;
	}

	public void setIeProfileGroupIndex(Integer ieProfileGroupIndex) {
		this.ieProfileGroupIndex = ieProfileGroupIndex;
	}
	
	@Column(name = "ie_profile_field_name", nullable = false, length = 80)
	public String getIeProfileFieldName() {
		return ieProfileFieldName;
	}

	public void setIeProfileFieldName(String ieProfileFieldName) {
		this.ieProfileFieldName = ieProfileFieldName;
	}

	@Column(name = "ie_profile_position", nullable = true)
	public Integer getIeProfilePosition() {
		return ieProfilePosition;
	}

	public void setIeProfilePosition(Integer ieProfilePosition) {
		this.ieProfilePosition = ieProfilePosition;
	}

	@Column(name = "ie_profile_field_value", nullable = true, length = 100000000)
	public String getIeProfileFieldValue() {
		return ieProfileFieldValue;
	}

	public void setIeProfileFieldValue(String ieProfileFieldValue) {
		this.ieProfileFieldValue = ieProfileFieldValue;
	}

	@Column(name = "rec_update_by", nullable = false, length = 20)
	public String getRecUpdateBy() {
		return recUpdateBy;
	}

	public void setRecUpdateBy(String recUpdateBy) {
		this.recUpdateBy = recUpdateBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "rec_update_datetime", nullable = false)
	public Date getRecUpdateDatetime() {
		return recUpdateDatetime;
	}

	public void setRecUpdateDatetime(Date recUpdateDatetime) {
		this.recUpdateDatetime = recUpdateDatetime;
	}

	@Column(name = "rec_create_by", nullable = false, length = 20)
	public String getRecCreateBy() {
		return recCreateBy;
	}

	public void setRecCreateBy(String recCreateBy) {
		this.recCreateBy = recCreateBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "rec_create_datetime", nullable = false)
	public Date getRecCreateDatetime() {
		return recCreateDatetime;
	}

	public void setRecCreateDatetime(Date recCreateDatetime) {
		this.recCreateDatetime = recCreateDatetime;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ie_profile_header_id")
	public IeProfileHeader getIeProfileHeader() {
		return ieProfileHeader;
	}

	public void setIeProfileHeader(IeProfileHeader ieProfileHeader) {
		this.ieProfileHeader = ieProfileHeader;
	}
}
