/*
 * Copyright 2007-2010 JadaSite.

 * This file is part of JadaSite.
 
 * JadaSite is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.

 * JadaSite is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.

 * You should have received a copy of the GNU General Public License
 * along with JadaSite.  If not, see <http://www.gnu.org/licenses/>.
 */

package com.jada.jpa.entity;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OrderBy;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * InvoiceHeader generated by hbm2java
 */
@Entity
@Table(name = "invoice_header", uniqueConstraints = @UniqueConstraint(columnNames = "invoice_num"))
public class InvoiceHeader implements java.io.Serializable {

	private static final long serialVersionUID = 9210214410400675988L;
	private Long invoiceHeaderId;
	private String invoiceNum;
	private Float shippingTotal;
	private Float invoiceTotal;
	private String invoiceStatus;
	private Date invoiceDate;
	private String recUpdateBy;
	private Date recUpdateDatetime;
	private String recCreateBy;
	private Date recCreateDatetime;
	private Set<InvoiceDetailTax> invoiceTaxes = new HashSet<InvoiceDetailTax>(
			0);
	private Set<InvoiceDetail> invoiceDetails = new HashSet<InvoiceDetail>(0);
	private Set<OrderTracking> invoiceTrackings = new HashSet<OrderTracking>(0);
	private Set<CreditHeader> creditHeaders = new HashSet<CreditHeader>(0);
	private PaymentTran paymentTran;
	private PaymentTran voidPaymentTran;
	private OrderHeader OrderHeader;

	public InvoiceHeader() {
	}

	public InvoiceHeader(String invoiceNum, Float shippingTotal,
			Float invoiceTotal, String invoiceStatus, Date invoiceDate,
			String recUpdateBy, Date recUpdateDatetime, String recCreateBy,
			Date recCreateDatetime) {
		this.invoiceNum = invoiceNum;
		this.shippingTotal = shippingTotal;
		this.invoiceTotal = invoiceTotal;
		this.invoiceStatus = invoiceStatus;
		this.invoiceDate = invoiceDate;
		this.recUpdateBy = recUpdateBy;
		this.recUpdateDatetime = recUpdateDatetime;
		this.recCreateBy = recCreateBy;
		this.recCreateDatetime = recCreateDatetime;
	}

	public InvoiceHeader(String invoiceNum, Float shippingTotal,
			Float invoiceTotal, String invoiceStatus, Date invoiceDate,
			String recUpdateBy, Date recUpdateDatetime, String recCreateBy,
			Date recCreateDatetime, Set<InvoiceDetailTax> invoiceTaxes,
			Set<InvoiceDetail> invoiceDetails,
			Set<OrderTracking> invoiceTrackings, Set<CreditHeader> creditHeaders, 
			PaymentTran paymentTran,
			PaymentTran voidPaymentTran, OrderHeader OrderHeader) {
		this.invoiceNum = invoiceNum;
		this.shippingTotal = shippingTotal;
		this.invoiceTotal = invoiceTotal;
		this.invoiceStatus = invoiceStatus;
		this.invoiceDate = invoiceDate;
		this.recUpdateBy = recUpdateBy;
		this.recUpdateDatetime = recUpdateDatetime;
		this.recCreateBy = recCreateBy;
		this.recCreateDatetime = recCreateDatetime;
		this.invoiceTaxes = invoiceTaxes;
		this.invoiceDetails = invoiceDetails;
		this.invoiceTrackings = invoiceTrackings;
		this.creditHeaders = creditHeaders;
		this.paymentTran = paymentTran;
		this.voidPaymentTran = voidPaymentTran;
		this.OrderHeader = OrderHeader;
	}

	@Id
	@GeneratedValue
	@Column(name = "invoice_header_id", nullable = false)
	public Long getInvoiceHeaderId() {
		return this.invoiceHeaderId;
	}

	public void setInvoiceHeaderId(Long invoiceHeaderId) {
		this.invoiceHeaderId = invoiceHeaderId;
	}

	@Column(name = "invoice_num", nullable = false, length = 20)
	public String getInvoiceNum() {
		return this.invoiceNum;
	}

	public void setInvoiceNum(String invoiceNum) {
		this.invoiceNum = invoiceNum;
	}

	@Column(name = "shipping_total", nullable = false)
	public Float getShippingTotal() {
		return this.shippingTotal;
	}

	public void setShippingTotal(Float shippingTotal) {
		this.shippingTotal = shippingTotal;
	}

	@Column(name = "invoice_total", nullable = false)
	public Float getInvoiceTotal() {
		return this.invoiceTotal;
	}

	public void setInvoiceTotal(Float invoiceTotal) {
		this.invoiceTotal = invoiceTotal;
	}

	@Column(name = "invoice_status", nullable = false, length = 1)
	public String getInvoiceStatus() {
		return this.invoiceStatus;
	}

	public void setInvoiceStatus(String invoiceStatus) {
		this.invoiceStatus = invoiceStatus;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "invoice_date", nullable = false)
	public Date getInvoiceDate() {
		return this.invoiceDate;
	}

	public void setInvoiceDate(Date invoiceDate) {
		this.invoiceDate = invoiceDate;
	}

	@Column(name = "rec_update_by", nullable = false, length = 20)
	public String getRecUpdateBy() {
		return this.recUpdateBy;
	}

	public void setRecUpdateBy(String recUpdateBy) {
		this.recUpdateBy = recUpdateBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "rec_update_datetime", nullable = false)
	public Date getRecUpdateDatetime() {
		return this.recUpdateDatetime;
	}

	public void setRecUpdateDatetime(Date recUpdateDatetime) {
		this.recUpdateDatetime = recUpdateDatetime;
	}

	@Column(name = "rec_create_by", nullable = false, length = 20)
	public String getRecCreateBy() {
		return this.recCreateBy;
	}

	public void setRecCreateBy(String recCreateBy) {
		this.recCreateBy = recCreateBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "rec_create_datetime", nullable = false)
	public Date getRecCreateDatetime() {
		return this.recCreateDatetime;
	}

	public void setRecCreateDatetime(Date recCreateDatetime) {
		this.recCreateDatetime = recCreateDatetime;
	}

	@OneToMany(fetch = FetchType.LAZY)
	@JoinColumn(name = "invoice_header_id", updatable = false)
	public Set<InvoiceDetailTax> getInvoiceTaxes() {
		return this.invoiceTaxes;
	}

	public void setInvoiceTaxes(Set<InvoiceDetailTax> invoiceTaxes) {
		this.invoiceTaxes = invoiceTaxes;
	}

	@OneToMany(fetch = FetchType.LAZY)
	@OrderBy(value="invoiceDetailId")
	@JoinColumn(name = "invoice_header_id", updatable = false)
	public Set<InvoiceDetail> getInvoiceDetails() {
		return this.invoiceDetails;
	}

	public void setInvoiceDetails(Set<InvoiceDetail> invoiceDetails) {
		this.invoiceDetails = invoiceDetails;
	}

	@OneToMany(fetch = FetchType.LAZY)
	@JoinColumn(name = "invoice_header_id", updatable = false)
	public Set<OrderTracking> getInvoiceTrackings() {
		return this.invoiceTrackings;
	}

	public void setInvoiceTrackings(Set<OrderTracking> invoiceTrackings) {
		this.invoiceTrackings = invoiceTrackings;
	}
	
	@OneToMany(fetch = FetchType.LAZY)
	@OrderBy(value="creditHeaderId")
	@JoinColumn(name = "invoice_header_id", updatable = false)
	public Set<CreditHeader> getCreditHeaders() {
		return this.creditHeaders;
	}

	public void setCreditHeaders(Set<CreditHeader> creditHeaders) {
		this.creditHeaders = creditHeaders;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "payment_tran_id")
	public PaymentTran getPaymentTran() {
		return this.paymentTran;
	}

	public void setPaymentTran(PaymentTran paymentTran) {
		this.paymentTran = paymentTran;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "void_payment_tran_id")
	public PaymentTran getVoidPaymentTran() {
		return this.voidPaymentTran;
	}

	public void setVoidPaymentTran(PaymentTran voidPaymentTran) {
		this.voidPaymentTran = voidPaymentTran;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "order_header_id")
	public OrderHeader getOrderHeader() {
		return this.OrderHeader;
	}

	public void setOrderHeader(OrderHeader OrderHeader) {
		this.OrderHeader = OrderHeader;
	}

}
