/*
 * Copyright 2007-2010 JadaSite.

 * This file is part of JadaSite.
 
 * JadaSite is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.

 * JadaSite is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.

 * You should have received a copy of the GNU General Public License
 * along with JadaSite.  If not, see <http://www.gnu.org/licenses/>.
 */

package com.jada.jpa.entity;

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ItemCurrency generated by hbm2java
 */
@Entity
@Table(name = "item_currency")
public class ItemCurrency implements java.io.Serializable {

	private static final long serialVersionUID = 6107882010320635424L;
	private Long itemCurrId;
	private Float itemPrice;
	private Float itemSpecPrice;
	private Float itemEffPrice;
	private Float itemEffSpecPrice;
	private Integer itemEffPriceXfactor;
	private Integer itemEffSpecPriceXfactor;
	private String recUpdateBy;
	private Date recUpdateDatetime;
	private String recCreateBy;
	private Date recCreateDatetime;
	private Item item;
	private SiteCurrencyClass siteCurrencyClass;

	public ItemCurrency() {
	}

	public ItemCurrency(Float itemPrice, Float itemEffPrice,
			Integer itemEffPriceXfactor, Integer itemEffSpecPriceXfactor,
			String recUpdateBy, Date recUpdateDatetime, String recCreateBy,
			Date recCreateDatetime) {
		this.itemPrice = itemPrice;
		this.itemEffPrice = itemEffPrice;
		this.itemEffPriceXfactor = itemEffPriceXfactor;
		this.itemEffSpecPriceXfactor = itemEffSpecPriceXfactor;
		this.recUpdateBy = recUpdateBy;
		this.recUpdateDatetime = recUpdateDatetime;
		this.recCreateBy = recCreateBy;
		this.recCreateDatetime = recCreateDatetime;
	}

	public ItemCurrency(Float itemPrice, Float itemSpecPrice,
			Float itemEffPrice, Float itemEffSpecPrice,
			Integer itemEffPriceXfactor, Integer itemEffSpecPriceXfactor,
			String recUpdateBy, Date recUpdateDatetime, String recCreateBy,
			Date recCreateDatetime, Item item,
			SiteCurrencyClass siteCurrencyClass) {
		this.itemPrice = itemPrice;
		this.itemSpecPrice = itemSpecPrice;
		this.itemEffPrice = itemEffPrice;
		this.itemEffSpecPrice = itemEffSpecPrice;
		this.itemEffPriceXfactor = itemEffPriceXfactor;
		this.itemEffSpecPriceXfactor = itemEffSpecPriceXfactor;
		this.recUpdateBy = recUpdateBy;
		this.recUpdateDatetime = recUpdateDatetime;
		this.recCreateBy = recCreateBy;
		this.recCreateDatetime = recCreateDatetime;
		this.item = item;
		this.siteCurrencyClass = siteCurrencyClass;
	}

	@Id
	@GeneratedValue
	@Column(name = "item_curr_id", nullable = false, length = 20)
	public Long getItemCurrId() {
		return this.itemCurrId;
	}

	public void setItemCurrId(Long itemCurrId) {
		this.itemCurrId = itemCurrId;
	}

	@Column(name = "item_price", nullable = false)
	public Float getItemPrice() {
		return this.itemPrice;
	}

	public void setItemPrice(Float itemPrice) {
		this.itemPrice = itemPrice;
	}

	@Column(name = "item_spec_price")
	public Float getItemSpecPrice() {
		return this.itemSpecPrice;
	}

	public void setItemSpecPrice(Float itemSpecPrice) {
		this.itemSpecPrice = itemSpecPrice;
	}

	@Column(name = "item_eff_price", nullable = false)
	public Float getItemEffPrice() {
		return this.itemEffPrice;
	}

	public void setItemEffPrice(Float itemEffPrice) {
		this.itemEffPrice = itemEffPrice;
	}

	@Column(name = "item_eff_spec_price")
	public Float getItemEffSpecPrice() {
		return this.itemEffSpecPrice;
	}

	public void setItemEffSpecPrice(Float itemEffSpecPrice) {
		this.itemEffSpecPrice = itemEffSpecPrice;
	}

	@Column(name = "item_eff_price_xfactor", nullable = false)
	public Integer getItemEffPriceXfactor() {
		return this.itemEffPriceXfactor;
	}

	public void setItemEffPriceXfactor(Integer itemEffPriceXfactor) {
		this.itemEffPriceXfactor = itemEffPriceXfactor;
	}

	@Column(name = "item_eff_spec_price_xfactor", nullable = false)
	public Integer getItemEffSpecPriceXfactor() {
		return this.itemEffSpecPriceXfactor;
	}

	public void setItemEffSpecPriceXfactor(Integer itemEffSpecPriceXfactor) {
		this.itemEffSpecPriceXfactor = itemEffSpecPriceXfactor;
	}

	@Column(name = "rec_update_by", nullable = false, length = 20)
	public String getRecUpdateBy() {
		return this.recUpdateBy;
	}

	public void setRecUpdateBy(String recUpdateBy) {
		this.recUpdateBy = recUpdateBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "rec_update_datetime", nullable = false)
	public Date getRecUpdateDatetime() {
		return this.recUpdateDatetime;
	}

	public void setRecUpdateDatetime(Date recUpdateDatetime) {
		this.recUpdateDatetime = recUpdateDatetime;
	}

	@Column(name = "rec_create_by", nullable = false, length = 20)
	public String getRecCreateBy() {
		return this.recCreateBy;
	}

	public void setRecCreateBy(String recCreateBy) {
		this.recCreateBy = recCreateBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "rec_create_datetime", nullable = false)
	public Date getRecCreateDatetime() {
		return this.recCreateDatetime;
	}

	public void setRecCreateDatetime(Date recCreateDatetime) {
		this.recCreateDatetime = recCreateDatetime;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "item_id")
	public Item getItem() {
		return this.item;
	}

	public void setItem(Item item) {
		this.item = item;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "site_currency_class_id")
	public SiteCurrencyClass getSiteCurrencyClass() {
		return this.siteCurrencyClass;
	}

	public void setSiteCurrencyClass(SiteCurrencyClass siteCurrencyClass) {
		this.siteCurrencyClass = siteCurrencyClass;
	}

}
