/*
 * Copyright 2007-2010 JadaSite.

 * This file is part of JadaSite.
 
 * JadaSite is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.

 * JadaSite is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.

 * You should have received a copy of the GNU General Public License
 * along with JadaSite.  If not, see <http://www.gnu.org/licenses/>.
 */

package com.jada.jpa.entity;

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ItemAttributeDetailLanguage generated by hbm2java
 */
@Entity
@Table(name = "item_attrib_detail_language")
public class ItemAttributeDetailLanguage implements java.io.Serializable {

	private static final long serialVersionUID = 5968067541268948413L;
	private Long itemAttribDetailLangId;
	private String itemAttribDetailValue;
	private String recUpdateBy;
	private Date recUpdateDatetime;
	private String recCreateBy;
	private Date recCreateDatetime;
	private ItemAttributeDetail itemAttributeDetail;
	private SiteProfileClass siteProfileClass;

	public ItemAttributeDetailLanguage() {
	}

	public ItemAttributeDetailLanguage(String recUpdateBy,
			Date recUpdateDatetime, String recCreateBy, Date recCreateDatetime) {
		this.recUpdateBy = recUpdateBy;
		this.recUpdateDatetime = recUpdateDatetime;
		this.recCreateBy = recCreateBy;
		this.recCreateDatetime = recCreateDatetime;
	}

	public ItemAttributeDetailLanguage(String itemAttribDetailValue,
			String recUpdateBy, Date recUpdateDatetime, String recCreateBy,
			Date recCreateDatetime, ItemAttributeDetail itemAttributeDetail,
			SiteProfileClass siteProfileClass) {
		this.itemAttribDetailValue = itemAttribDetailValue;
		this.recUpdateBy = recUpdateBy;
		this.recUpdateDatetime = recUpdateDatetime;
		this.recCreateBy = recCreateBy;
		this.recCreateDatetime = recCreateDatetime;
		this.itemAttributeDetail = itemAttributeDetail;
		this.siteProfileClass = siteProfileClass;
	}

	@Id
	@GeneratedValue
	@Column(name = "item_attrib_detail_lang_id", nullable = false)
	public Long getItemAttribDetailLangId() {
		return this.itemAttribDetailLangId;
	}

	public void setItemAttribDetailLangId(Long itemAttribDetailLangId) {
		this.itemAttribDetailLangId = itemAttribDetailLangId;
	}

	@Column(name = "item_attrib_detail_value", length = 80)
	public String getItemAttribDetailValue() {
		return this.itemAttribDetailValue;
	}

	public void setItemAttribDetailValue(String itemAttribDetailValue) {
		this.itemAttribDetailValue = itemAttribDetailValue;
	}

	@Column(name = "rec_update_by", nullable = false, length = 20)
	public String getRecUpdateBy() {
		return this.recUpdateBy;
	}

	public void setRecUpdateBy(String recUpdateBy) {
		this.recUpdateBy = recUpdateBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "rec_update_datetime", nullable = false)
	public Date getRecUpdateDatetime() {
		return this.recUpdateDatetime;
	}

	public void setRecUpdateDatetime(Date recUpdateDatetime) {
		this.recUpdateDatetime = recUpdateDatetime;
	}

	@Column(name = "rec_create_by", nullable = false, length = 20)
	public String getRecCreateBy() {
		return this.recCreateBy;
	}

	public void setRecCreateBy(String recCreateBy) {
		this.recCreateBy = recCreateBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "rec_create_datetime", nullable = false)
	public Date getRecCreateDatetime() {
		return this.recCreateDatetime;
	}

	public void setRecCreateDatetime(Date recCreateDatetime) {
		this.recCreateDatetime = recCreateDatetime;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "item_attrib_detail_id")
	public ItemAttributeDetail getItemAttributeDetail() {
		return this.itemAttributeDetail;
	}

	public void setItemAttributeDetail(ItemAttributeDetail itemAttributeDetail) {
		this.itemAttributeDetail = itemAttributeDetail;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "site_profile_class_id")
	public SiteProfileClass getSiteProfileClass() {
		return this.siteProfileClass;
	}

	public void setSiteProfileClass(SiteProfileClass siteProfileClass) {
		this.siteProfileClass = siteProfileClass;
	}

}
