/*
 * Copyright 2007-2010 JadaSite.

 * This file is part of JadaSite.
 
 * JadaSite is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.

 * JadaSite is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.

 * You should have received a copy of the GNU General Public License
 * along with JadaSite.  If not, see <http://www.gnu.org/licenses/>.
 */

package com.jada.jpa.entity;

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ItemTierPriceCurrency generated by hbm2java
 */
@Entity
@Table(name = "item_tier_price_currency")
public class ItemTierPriceCurrency implements java.io.Serializable {

	private static final long serialVersionUID = -7296933387152557905L;
	private Long itemTierPriceCurrId;
	private Float itemPrice;
	private String recUpdateBy;
	private Date recUpdateDatetime;
	private String recCreateBy;
	private Date recCreateDatetime;
	private ItemTierPrice itemTierPrice;
	private SiteCurrencyClass siteCurrencyClass;

	public ItemTierPriceCurrency() {
	}

	public ItemTierPriceCurrency(String recUpdateBy, Date recUpdateDatetime,
			String recCreateBy, Date recCreateDatetime) {
		this.recUpdateBy = recUpdateBy;
		this.recUpdateDatetime = recUpdateDatetime;
		this.recCreateBy = recCreateBy;
		this.recCreateDatetime = recCreateDatetime;
	}

	public ItemTierPriceCurrency(Float itemPrice, String recUpdateBy,
			Date recUpdateDatetime, String recCreateBy, Date recCreateDatetime,
			ItemTierPrice itemTierPrice, SiteCurrencyClass siteCurrencyClass) {
		this.itemPrice = itemPrice;
		this.recUpdateBy = recUpdateBy;
		this.recUpdateDatetime = recUpdateDatetime;
		this.recCreateBy = recCreateBy;
		this.recCreateDatetime = recCreateDatetime;
		this.itemTierPrice = itemTierPrice;
		this.siteCurrencyClass = siteCurrencyClass;
	}

	@Id
	@GeneratedValue
	@Column(name = "item_tier_price_curr_id", nullable = false, length = 20)
	public Long getItemTierPriceCurrId() {
		return this.itemTierPriceCurrId;
	}

	public void setItemTierPriceCurrId(Long itemTierPriceCurrId) {
		this.itemTierPriceCurrId = itemTierPriceCurrId;
	}

	@Column(name = "item_price")
	public Float getItemPrice() {
		return this.itemPrice;
	}

	public void setItemPrice(Float itemPrice) {
		this.itemPrice = itemPrice;
	}

	@Column(name = "rec_update_by", nullable = false, length = 20)
	public String getRecUpdateBy() {
		return this.recUpdateBy;
	}

	public void setRecUpdateBy(String recUpdateBy) {
		this.recUpdateBy = recUpdateBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "rec_update_datetime", nullable = false)
	public Date getRecUpdateDatetime() {
		return this.recUpdateDatetime;
	}

	public void setRecUpdateDatetime(Date recUpdateDatetime) {
		this.recUpdateDatetime = recUpdateDatetime;
	}

	@Column(name = "rec_create_by", nullable = false, length = 20)
	public String getRecCreateBy() {
		return this.recCreateBy;
	}

	public void setRecCreateBy(String recCreateBy) {
		this.recCreateBy = recCreateBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "rec_create_datetime", nullable = false)
	public Date getRecCreateDatetime() {
		return this.recCreateDatetime;
	}

	public void setRecCreateDatetime(Date recCreateDatetime) {
		this.recCreateDatetime = recCreateDatetime;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "item_tier_price_id")
	public ItemTierPrice getItemTierPrice() {
		return this.itemTierPrice;
	}

	public void setItemTierPrice(ItemTierPrice itemTierPrice) {
		this.itemTierPrice = itemTierPrice;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "site_currency_class_id")
	public SiteCurrencyClass getSiteCurrencyClass() {
		return this.siteCurrencyClass;
	}

	public void setSiteCurrencyClass(SiteCurrencyClass siteCurrencyClass) {
		this.siteCurrencyClass = siteCurrencyClass;
	}

}
