/*
 * Copyright 2007-2010 JadaSite.

 * This file is part of JadaSite.
 
 * JadaSite is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.

 * JadaSite is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.

 * You should have received a copy of the GNU General Public License
 * along with JadaSite.  If not, see <http://www.gnu.org/licenses/>.
 */

package com.jada.jpa.entity;

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ItemPriceSearch generated by hbm2java
 */
@Entity
@Table(name = "item_price_search")
public class ItemPriceSearch implements java.io.Serializable {

	private static final long serialVersionUID = -3471865150173407162L;
	private Long itemPriceSearchId;
	private Float itemPrice;
	private Integer exchangeFactor;
	private Date itemPricePublishOn;
	private Date itemPriceExpireOn;
	private String recUpdateBy;
	private Date recUpdateDatetime;
	private String recCreateBy;
	private Date recCreateDatetime;
	private Item item;
	private SiteCurrencyClass siteCurrencyClass;

	public ItemPriceSearch() {
	}

	public ItemPriceSearch(Float itemPrice, Integer exchangeFactor,
			Date itemPricePublishOn, Date itemPriceExpireOn,
			String recUpdateBy, Date recUpdateDatetime, String recCreateBy,
			Date recCreateDatetime) {
		this.itemPrice = itemPrice;
		this.exchangeFactor = exchangeFactor;
		this.itemPricePublishOn = itemPricePublishOn;
		this.itemPriceExpireOn = itemPriceExpireOn;
		this.recUpdateBy = recUpdateBy;
		this.recUpdateDatetime = recUpdateDatetime;
		this.recCreateBy = recCreateBy;
		this.recCreateDatetime = recCreateDatetime;
	}

	public ItemPriceSearch(Float itemPrice, Integer exchangeFactor,
			Date itemPricePublishOn, Date itemPriceExpireOn,
			String recUpdateBy, Date recUpdateDatetime, String recCreateBy,
			Date recCreateDatetime, Item item,
			SiteCurrencyClass siteCurrencyClass) {
		this.itemPrice = itemPrice;
		this.exchangeFactor = exchangeFactor;
		this.itemPricePublishOn = itemPricePublishOn;
		this.itemPriceExpireOn = itemPriceExpireOn;
		this.recUpdateBy = recUpdateBy;
		this.recUpdateDatetime = recUpdateDatetime;
		this.recCreateBy = recCreateBy;
		this.recCreateDatetime = recCreateDatetime;
		this.item = item;
		this.siteCurrencyClass = siteCurrencyClass;
	}

	@Id
	@GeneratedValue
	@Column(name = "item_price_search_id", nullable = false, length = 20)
	public Long getItemPriceSearchId() {
		return this.itemPriceSearchId;
	}

	public void setItemPriceSearchId(Long itemPriceSearchId) {
		this.itemPriceSearchId = itemPriceSearchId;
	}

	@Column(name = "item_price", nullable = false)
	public Float getItemPrice() {
		return this.itemPrice;
	}

	public void setItemPrice(Float itemPrice) {
		this.itemPrice = itemPrice;
	}

	@Column(name = "exchange_factor", nullable = false)
	public Integer getExchangeFactor() {
		return this.exchangeFactor;
	}

	public void setExchangeFactor(Integer exchangeFactor) {
		this.exchangeFactor = exchangeFactor;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "item_price_publish_on", nullable = false)
	public Date getItemPricePublishOn() {
		return this.itemPricePublishOn;
	}

	public void setItemPricePublishOn(Date itemPricePublishOn) {
		this.itemPricePublishOn = itemPricePublishOn;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "item_price_expire_on", nullable = false)
	public Date getItemPriceExpireOn() {
		return this.itemPriceExpireOn;
	}

	public void setItemPriceExpireOn(Date itemPriceExpireOn) {
		this.itemPriceExpireOn = itemPriceExpireOn;
	}

	@Column(name = "rec_update_by", nullable = false, length = 20)
	public String getRecUpdateBy() {
		return this.recUpdateBy;
	}

	public void setRecUpdateBy(String recUpdateBy) {
		this.recUpdateBy = recUpdateBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "rec_update_datetime", nullable = false)
	public Date getRecUpdateDatetime() {
		return this.recUpdateDatetime;
	}

	public void setRecUpdateDatetime(Date recUpdateDatetime) {
		this.recUpdateDatetime = recUpdateDatetime;
	}

	@Column(name = "rec_create_by", nullable = false, length = 20)
	public String getRecCreateBy() {
		return this.recCreateBy;
	}

	public void setRecCreateBy(String recCreateBy) {
		this.recCreateBy = recCreateBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "rec_create_datetime", nullable = false)
	public Date getRecCreateDatetime() {
		return this.recCreateDatetime;
	}

	public void setRecCreateDatetime(Date recCreateDatetime) {
		this.recCreateDatetime = recCreateDatetime;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "item_id")
	public Item getItem() {
		return this.item;
	}

	public void setItem(Item item) {
		this.item = item;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "site_currency_class_id")
	public SiteCurrencyClass getSiteCurrencyClass() {
		return this.siteCurrencyClass;
	}

	public void setSiteCurrencyClass(SiteCurrencyClass siteCurrencyClass) {
		this.siteCurrencyClass = siteCurrencyClass;
	}

}
