/*
 * Copyright 2007-2010 JadaSite.

 * This file is part of JadaSite.
 
 * JadaSite is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.

 * JadaSite is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.

 * You should have received a copy of the GNU General Public License
 * along with JadaSite.  If not, see <http://www.gnu.org/licenses/>.
 */

package com.jada.jpa.entity;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OrderBy;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ItemLanguage generated by hbm2java
 */
@Entity
@Table(name = "item_language")
public class ItemLanguage implements java.io.Serializable {

	private static final long serialVersionUID = -5608081494421252347L;
	private Long itemLangId;
	private String itemShortDesc;
	private String itemDesc;
	private String pageTitle;
	private String itemImageOverride;
	private String metaKeywords;
	private String metaDescription;
	private String recUpdateBy;
	private Date recUpdateDatetime;
	private String recCreateBy;
	private Date recCreateDatetime;
	private Item item;
	private ItemImage image;
	private SiteProfileClass siteProfileClass;
	private Set<ItemImage> images = new HashSet<ItemImage>(0);

	public ItemLanguage() {
	}

	public ItemLanguage(String itemImageOverride, String recUpdateBy,
			Date recUpdateDatetime, String recCreateBy, Date recCreateDatetime) {
		this.itemImageOverride = itemImageOverride;
		this.recUpdateBy = recUpdateBy;
		this.recUpdateDatetime = recUpdateDatetime;
		this.recCreateBy = recCreateBy;
		this.recCreateDatetime = recCreateDatetime;
	}

	public ItemLanguage(String itemShortDesc, String itemDesc,
			String pageTitle, String itemImageOverride,
			String metaKeywords, String metaDescription,
			String recUpdateBy,
			Date recUpdateDatetime, String recCreateBy, Date recCreateDatetime,
			Item item, ItemImage image, SiteProfileClass siteProfileClass,
			Set<ItemImage> images) {
		this.itemShortDesc = itemShortDesc;
		this.itemDesc = itemDesc;
		this.pageTitle = pageTitle;
		this.itemImageOverride = itemImageOverride;
		this.metaKeywords = metaKeywords;
		this.metaDescription = metaDescription;
		this.recUpdateBy = recUpdateBy;
		this.recUpdateDatetime = recUpdateDatetime;
		this.recCreateBy = recCreateBy;
		this.recCreateDatetime = recCreateDatetime;
		this.item = item;
		this.image = image;
		this.siteProfileClass = siteProfileClass;
		this.images = images;
	}

	@Id
	@GeneratedValue
	@Column(name = "item_lang_id", nullable = false, length = 20)
	public Long getItemLangId() {
		return this.itemLangId;
	}

	public void setItemLangId(Long itemLangId) {
		this.itemLangId = itemLangId;
	}

	@Column(name = "item_short_desc", length = 128)
	public String getItemShortDesc() {
		return this.itemShortDesc;
	}

	public void setItemShortDesc(String itemShortDesc) {
		this.itemShortDesc = itemShortDesc;
	}

	@Column(name = "item_desc", length = 100000000)
	public String getItemDesc() {
		return this.itemDesc;
	}

	public void setItemDesc(String itemDesc) {
		this.itemDesc = itemDesc;
	}

	@Column(name = "page_title", length = 255)
	public String getPageTitle() {
		return this.pageTitle;
	}

	public void setPageTitle(String pageTitle) {
		this.pageTitle = pageTitle;
	}

	@Column(name = "item_image_override", nullable = false, length = 1)
	public String getItemImageOverride() {
		return this.itemImageOverride;
	}

	public void setItemImageOverride(String itemImageOverride) {
		this.itemImageOverride = itemImageOverride;
	}
	
	@Column(name = "meta_keywords", length = 1000)
	public String getMetaKeywords() {
		return this.metaKeywords;
	}

	public void setMetaKeywords(String metaKeywords) {
		this.metaKeywords = metaKeywords;
	}

	@Column(name = "meta_description", length = 1000)
	public String getMetaDescription() {
		return this.metaDescription;
	}

	public void setMetaDescription(String metaDescription) {
		this.metaDescription = metaDescription;
	}

	@Column(name = "rec_update_by", nullable = false, length = 20)
	public String getRecUpdateBy() {
		return this.recUpdateBy;
	}

	public void setRecUpdateBy(String recUpdateBy) {
		this.recUpdateBy = recUpdateBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "rec_update_datetime", nullable = false)
	public Date getRecUpdateDatetime() {
		return this.recUpdateDatetime;
	}

	public void setRecUpdateDatetime(Date recUpdateDatetime) {
		this.recUpdateDatetime = recUpdateDatetime;
	}

	@Column(name = "rec_create_by", nullable = false, length = 20)
	public String getRecCreateBy() {
		return this.recCreateBy;
	}

	public void setRecCreateBy(String recCreateBy) {
		this.recCreateBy = recCreateBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "rec_create_datetime", nullable = false)
	public Date getRecCreateDatetime() {
		return this.recCreateDatetime;
	}

	public void setRecCreateDatetime(Date recCreateDatetime) {
		this.recCreateDatetime = recCreateDatetime;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "item_id")
	public Item getItem() {
		return this.item;
	}

	public void setItem(Item item) {
		this.item = item;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "image_id", unique = true)
	public ItemImage getImage() {
		return this.image;
	}

	public void setImage(ItemImage image) {
		this.image = image;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "site_profile_class_id")
	public SiteProfileClass getSiteProfileClass() {
		return this.siteProfileClass;
	}

	public void setSiteProfileClass(SiteProfileClass siteProfileClass) {
		this.siteProfileClass = siteProfileClass;
	}

	@OneToMany(fetch = FetchType.LAZY)
	@OrderBy(value="seqNum")
	@JoinColumn(name = "item_lang_id", updatable = false)
	public Set<ItemImage> getImages() {
		return this.images;
	}

	public void setImages(Set<ItemImage> images) {
		this.images = images;
	}

}
