/*
 * Copyright 2007-2010 JadaSite.

 * This file is part of JadaSite.
 
 * JadaSite is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.

 * JadaSite is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.

 * You should have received a copy of the GNU General Public License
 * along with JadaSite.  If not, see <http://www.gnu.org/licenses/>.
 */

package com.jada.jpa.entity;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Language generated by hbm2java
 */
@Entity
@Table(name = "language")
public class Language implements java.io.Serializable {

	private static final long serialVersionUID = 2468478846085448785L;
	private Long langId;
	private String langName;
	private String langLocaleLanguage;
	private String langLocaleCountry;
	private String googleTranslateLocale;
	private char systemRecord;
	private String recUpdateBy;
	private Date recUpdateDatetime;
	private String recCreateBy;
	private Date recCreateDatetime;
	private Set<LanguageTranslation> translations = new HashSet<LanguageTranslation>(
			0);

	public Language() {
	}

	public Language(String langName, String langLocaleLanguage,
			String langLocaleCountry, String googleTranslateLocale,
			char systemRecord, String recUpdateBy, Date recUpdateDatetime,
			String recCreateBy, Date recCreateDatetime) {
		this.langName = langName;
		this.langLocaleLanguage = langLocaleLanguage;
		this.langLocaleCountry = langLocaleCountry;
		this.googleTranslateLocale = googleTranslateLocale;
		this.systemRecord = systemRecord;
		this.recUpdateBy = recUpdateBy;
		this.recUpdateDatetime = recUpdateDatetime;
		this.recCreateBy = recCreateBy;
		this.recCreateDatetime = recCreateDatetime;
	}

	public Language(String langName, String langLocaleLanguage,
			String langLocaleCountry, String googleTranslateLocale,
			char systemRecord, String recUpdateBy, Date recUpdateDatetime,
			String recCreateBy, Date recCreateDatetime,
			Set<LanguageTranslation> translations) {
		this.langName = langName;
		this.langLocaleLanguage = langLocaleLanguage;
		this.langLocaleCountry = langLocaleCountry;
		this.googleTranslateLocale = googleTranslateLocale;
		this.systemRecord = systemRecord;
		this.recUpdateBy = recUpdateBy;
		this.recUpdateDatetime = recUpdateDatetime;
		this.recCreateBy = recCreateBy;
		this.recCreateDatetime = recCreateDatetime;
		this.translations = translations;
	}

	@Id
	@GeneratedValue
	@Column(name = "lang_id", nullable = false)
	public Long getLangId() {
		return this.langId;
	}

	public void setLangId(Long langId) {
		this.langId = langId;
	}

	@Column(name = "lang_name", nullable = false, length = 50)
	public String getLangName() {
		return this.langName;
	}

	public void setLangName(String langName) {
		this.langName = langName;
	}

	@Column(name = "lang_locale_language", nullable = false, length = 2)
	public String getLangLocaleLanguage() {
		return this.langLocaleLanguage;
	}

	public void setLangLocaleLanguage(String langLocaleLanguage) {
		this.langLocaleLanguage = langLocaleLanguage;
	}

	@Column(name = "lang_locale_country", nullable = false, length = 2)
	public String getLangLocaleCountry() {
		return this.langLocaleCountry;
	}

	public void setLangLocaleCountry(String langLocaleCountry) {
		this.langLocaleCountry = langLocaleCountry;
	}

	@Column(name = "google_translate_locale", nullable = false, length = 10)
	public String getGoogleTranslateLocale() {
		return this.googleTranslateLocale;
	}

	public void setGoogleTranslateLocale(String googleTranslateLocale) {
		this.googleTranslateLocale = googleTranslateLocale;
	}

	@Column(name = "system_record", nullable = false, length = 1)
	public char getSystemRecord() {
		return this.systemRecord;
	}

	public void setSystemRecord(char systemRecord) {
		this.systemRecord = systemRecord;
	}

	@Column(name = "rec_update_by", nullable = false, length = 20)
	public String getRecUpdateBy() {
		return this.recUpdateBy;
	}

	public void setRecUpdateBy(String recUpdateBy) {
		this.recUpdateBy = recUpdateBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "rec_update_datetime", nullable = false)
	public Date getRecUpdateDatetime() {
		return this.recUpdateDatetime;
	}

	public void setRecUpdateDatetime(Date recUpdateDatetime) {
		this.recUpdateDatetime = recUpdateDatetime;
	}

	@Column(name = "rec_create_by", nullable = false, length = 20)
	public String getRecCreateBy() {
		return this.recCreateBy;
	}

	public void setRecCreateBy(String recCreateBy) {
		this.recCreateBy = recCreateBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "rec_create_datetime", nullable = false)
	public Date getRecCreateDatetime() {
		return this.recCreateDatetime;
	}

	public void setRecCreateDatetime(Date recCreateDatetime) {
		this.recCreateDatetime = recCreateDatetime;
	}

	@OneToMany(fetch = FetchType.LAZY)
	@JoinColumn(name = "lang_id", updatable = false)
	public Set<LanguageTranslation> getTranslations() {
		return this.translations;
	}

	public void setTranslations(Set<LanguageTranslation> translations) {
		this.translations = translations;
	}

}
