/*
 * Copyright 2007-2010 JadaSite.

 * This file is part of JadaSite.
 
 * JadaSite is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.

 * JadaSite is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.

 * You should have received a copy of the GNU General Public License
 * along with JadaSite.  If not, see <http://www.gnu.org/licenses/>.
 */

package com.jada.jpa.entity;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OrderBy;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Menu generated by hbm2java
 */
@Entity
@Table(name = "menu")
public class Menu implements java.io.Serializable {

	private static final long serialVersionUID = 629645331325030329L;
	private Long menuId;
	private String menuSetName;
	private int seqNum;
	private String menuType;
	private String menuUrl;
	private String menuWindowTarget;
	private String menuWindowMode;
	private char published;
	private String recUpdateBy;
	private Date recUpdateDatetime;
	private String recCreateBy;
	private Date recCreateDatetime;
	private MenuLanguage menuLanguage;
	private Menu menuParent;
	private Set<Menu> menuChildren = new HashSet<Menu>(0);
	private Category category;
	private Item item;
	private Content content;
	private Set<MenuLanguage> menuLanguages = new HashSet<MenuLanguage>(0);
	private SiteDomain siteDomain;

	public Menu() {
	}

	public Menu(String menuSetName, int seqNum, String menuType,
			String menuUrl, String menuWindowTarget, String menuWindowMode,
			char published, String recUpdateBy, Date recUpdateDatetime,
			String recCreateBy, Date recCreateDatetime, SiteDomain siteDomain) {
		this.menuSetName = menuSetName;
		this.seqNum = seqNum;
		this.menuType = menuType;
		this.menuUrl = menuUrl;
		this.menuWindowTarget = menuWindowTarget;
		this.menuWindowMode = menuWindowMode;
		this.published = published;
		this.recUpdateBy = recUpdateBy;
		this.recUpdateDatetime = recUpdateDatetime;
		this.recCreateBy = recCreateBy;
		this.recCreateDatetime = recCreateDatetime;
		this.siteDomain = siteDomain;
	}

	public Menu(String menuSetName, int seqNum, String menuType,
			String menuUrl, String menuWindowTarget, String menuWindowMode,
			char published, String recUpdateBy, Date recUpdateDatetime,
			String recCreateBy, Date recCreateDatetime,
			MenuLanguage menuLanguage, Menu menuParent, Set<Menu> menuChildren,
			Category category, Item item, Content content,
			Set<MenuLanguage> menuLanguages, SiteDomain siteDomain) {
		this.menuSetName = menuSetName;
		this.seqNum = seqNum;
		this.menuType = menuType;
		this.menuUrl = menuUrl;
		this.menuWindowTarget = menuWindowTarget;
		this.menuWindowMode = menuWindowMode;
		this.published = published;
		this.recUpdateBy = recUpdateBy;
		this.recUpdateDatetime = recUpdateDatetime;
		this.recCreateBy = recCreateBy;
		this.recCreateDatetime = recCreateDatetime;
		this.menuLanguage = menuLanguage;
		this.menuParent = menuParent;
		this.menuChildren = menuChildren;
		this.category = category;
		this.item = item;
		this.content = content;
		this.menuLanguages = menuLanguages;
		this.siteDomain = siteDomain;
	}

	@Id
	@GeneratedValue
	@Column(name = "menu_id", nullable = false)
	public Long getMenuId() {
		return this.menuId;
	}

	public void setMenuId(Long menuId) {
		this.menuId = menuId;
	}

	@Column(name = "menu_set_name", nullable = false, length = 20)
	public String getMenuSetName() {
		return this.menuSetName;
	}

	public void setMenuSetName(String menuSetName) {
		this.menuSetName = menuSetName;
	}

	@Column(name = "seq_num", nullable = false)
	public int getSeqNum() {
		return this.seqNum;
	}

	public void setSeqNum(int seqNum) {
		this.seqNum = seqNum;
	}

	@Column(name = "menu_type", nullable = false, length = 5)
	public String getMenuType() {
		return this.menuType;
	}

	public void setMenuType(String menuType) {
		this.menuType = menuType;
	}

	@Column(name = "menu_url", nullable = false, length = 255)
	public String getMenuUrl() {
		return this.menuUrl;
	}

	public void setMenuUrl(String menuUrl) {
		this.menuUrl = menuUrl;
	}

	@Column(name = "menu_window_target", nullable = false, length = 20)
	public String getMenuWindowTarget() {
		return this.menuWindowTarget;
	}

	public void setMenuWindowTarget(String menuWindowTarget) {
		this.menuWindowTarget = menuWindowTarget;
	}

	@Column(name = "menu_window_mode", nullable = false, length = 255)
	public String getMenuWindowMode() {
		return this.menuWindowMode;
	}

	public void setMenuWindowMode(String menuWindowMode) {
		this.menuWindowMode = menuWindowMode;
	}

	@Column(name = "published", nullable = false, length = 1)
	public char getPublished() {
		return this.published;
	}

	public void setPublished(char published) {
		this.published = published;
	}

	@Column(name = "rec_update_by", nullable = false, length = 20)
	public String getRecUpdateBy() {
		return this.recUpdateBy;
	}

	public void setRecUpdateBy(String recUpdateBy) {
		this.recUpdateBy = recUpdateBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "rec_update_datetime", nullable = false)
	public Date getRecUpdateDatetime() {
		return this.recUpdateDatetime;
	}

	public void setRecUpdateDatetime(Date recUpdateDatetime) {
		this.recUpdateDatetime = recUpdateDatetime;
	}

	@Column(name = "rec_create_by", nullable = false, length = 20)
	public String getRecCreateBy() {
		return this.recCreateBy;
	}

	public void setRecCreateBy(String recCreateBy) {
		this.recCreateBy = recCreateBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "rec_create_datetime", nullable = false)
	public Date getRecCreateDatetime() {
		return this.recCreateDatetime;
	}

	public void setRecCreateDatetime(Date recCreateDatetime) {
		this.recCreateDatetime = recCreateDatetime;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "menu_lang_id")
	public MenuLanguage getMenuLanguage() {
		return this.menuLanguage;
	}

	public void setMenuLanguage(MenuLanguage menuLanguage) {
		this.menuLanguage = menuLanguage;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "menu_parent_id")
	public Menu getMenuParent() {
		return this.menuParent;
	}

	public void setMenuParent(Menu menuParent) {
		this.menuParent = menuParent;
	}

	@OneToMany(fetch = FetchType.LAZY)
	@JoinColumn(name = "menu_parent_id", updatable = false)
	@OrderBy(value="seqNum")
	public Set<Menu> getMenuChildren() {
		return this.menuChildren;
	}

	public void setMenuChildren(Set<Menu> menuChildren) {
		this.menuChildren = menuChildren;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cat_id")
	public Category getCategory() {
		return this.category;
	}

	public void setCategory(Category category) {
		this.category = category;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "item_id")
	public Item getItem() {
		return this.item;
	}

	public void setItem(Item item) {
		this.item = item;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "content_id")
	public Content getContent() {
		return this.content;
	}

	public void setContent(Content content) {
		this.content = content;
	}

	@OneToMany(fetch = FetchType.LAZY)
	@JoinColumn(name = "menu_id", updatable = false)
	public Set<MenuLanguage> getMenuLanguages() {
		return this.menuLanguages;
	}

	public void setMenuLanguages(Set<MenuLanguage> menuLanguages) {
		this.menuLanguages = menuLanguages;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "site_domain_id", nullable = false)
	public SiteDomain getSiteDomain() {
		return this.siteDomain;
	}

	public void setSiteDomain(SiteDomain siteDomain) {
		this.siteDomain = siteDomain;
	}

}
