/*
 * Copyright 2007-2010 JadaSite.

 * This file is part of JadaSite.
 
 * JadaSite is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.

 * JadaSite is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.

 * You should have received a copy of the GNU General Public License
 * along with JadaSite.  If not, see <http://www.gnu.org/licenses/>.
 */

package com.jada.jpa.entity;

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * OrderOtherDetail generated by hbm2java
 */
@Entity
@Table(name = "order_other_detail")
public class OrderOtherDetail implements java.io.Serializable {

	private static final long serialVersionUID = 8917861650146416803L;
	private Long orderOtherDetailId;
	private Integer seqNum;
	private String orderOtherDetailNum;
	private String orderOtherDetailDesc;
	private Float orderOtherDetailAmount;
	private String recUpdateBy;
	private Date recUpdateDatetime;
	private String recCreateBy;
	private Date recCreateDatetime;
	private Coupon coupon;
	private OrderHeader orderHeader;

	public OrderOtherDetail() {
	}

	public OrderOtherDetail(String orderOtherDetailNum,
			String orderOtherDetailDesc, String recUpdateBy,
			Date recUpdateDatetime, String recCreateBy, Date recCreateDatetime) {
		this.orderOtherDetailNum = orderOtherDetailNum;
		this.orderOtherDetailDesc = orderOtherDetailDesc;
		this.recUpdateBy = recUpdateBy;
		this.recUpdateDatetime = recUpdateDatetime;
		this.recCreateBy = recCreateBy;
		this.recCreateDatetime = recCreateDatetime;
	}

	public OrderOtherDetail(Integer seqNum, String orderOtherDetailNum,
			String orderOtherDetailDesc, Float orderOtherDetailAmount,
			String recUpdateBy, Date recUpdateDatetime, String recCreateBy,
			Date recCreateDatetime, Coupon coupon, OrderHeader orderHeader) {
		this.seqNum = seqNum;
		this.orderOtherDetailNum = orderOtherDetailNum;
		this.orderOtherDetailDesc = orderOtherDetailDesc;
		this.orderOtherDetailAmount = orderOtherDetailAmount;
		this.recUpdateBy = recUpdateBy;
		this.recUpdateDatetime = recUpdateDatetime;
		this.recCreateBy = recCreateBy;
		this.recCreateDatetime = recCreateDatetime;
		this.coupon = coupon;
		this.orderHeader = orderHeader;
	}

	@Id
	@GeneratedValue
	@Column(name = "order_other_detail_id", nullable = false)
	public Long getOrderOtherDetailId() {
		return this.orderOtherDetailId;
	}

	public void setOrderOtherDetailId(Long orderOtherDetailId) {
		this.orderOtherDetailId = orderOtherDetailId;
	}

	@Column(name = "seq_num")
	public Integer getSeqNum() {
		return this.seqNum;
	}

	public void setSeqNum(Integer seqNum) {
		this.seqNum = seqNum;
	}

	@Column(name = "order_other_detail_num", nullable = false, length = 20)
	public String getOrderOtherDetailNum() {
		return this.orderOtherDetailNum;
	}

	public void setOrderOtherDetailNum(String orderOtherDetailNum) {
		this.orderOtherDetailNum = orderOtherDetailNum;
	}

	@Column(name = "order_other_detail_desc", nullable = false, length = 80)
	public String getOrderOtherDetailDesc() {
		return this.orderOtherDetailDesc;
	}

	public void setOrderOtherDetailDesc(String orderOtherDetailDesc) {
		this.orderOtherDetailDesc = orderOtherDetailDesc;
	}

	@Column(name = "order_other_detail_amount")
	public Float getOrderOtherDetailAmount() {
		return this.orderOtherDetailAmount;
	}

	public void setOrderOtherDetailAmount(Float orderOtherDetailAmount) {
		this.orderOtherDetailAmount = orderOtherDetailAmount;
	}

	@Column(name = "rec_update_by", nullable = false, length = 20)
	public String getRecUpdateBy() {
		return this.recUpdateBy;
	}

	public void setRecUpdateBy(String recUpdateBy) {
		this.recUpdateBy = recUpdateBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "rec_update_datetime", nullable = false)
	public Date getRecUpdateDatetime() {
		return this.recUpdateDatetime;
	}

	public void setRecUpdateDatetime(Date recUpdateDatetime) {
		this.recUpdateDatetime = recUpdateDatetime;
	}

	@Column(name = "rec_create_by", nullable = false, length = 20)
	public String getRecCreateBy() {
		return this.recCreateBy;
	}

	public void setRecCreateBy(String recCreateBy) {
		this.recCreateBy = recCreateBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "rec_create_datetime", nullable = false)
	public Date getRecCreateDatetime() {
		return this.recCreateDatetime;
	}

	public void setRecCreateDatetime(Date recCreateDatetime) {
		this.recCreateDatetime = recCreateDatetime;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "coupon_id")
	public Coupon getCoupon() {
		return this.coupon;
	}

	public void setCoupon(Coupon coupon) {
		this.coupon = coupon;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "order_header_id")
	public OrderHeader getOrderHeader() {
		return this.orderHeader;
	}

	public void setOrderHeader(OrderHeader orderHeader) {
		this.orderHeader = orderHeader;
	}

}
