/*
 * Copyright 2007-2010 JadaSite.

 * This file is part of JadaSite.
 
 * JadaSite is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.

 * JadaSite is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.

 * You should have received a copy of the GNU General Public License
 * along with JadaSite.  If not, see <http://www.gnu.org/licenses/>.
 */

package com.jada.jpa.entity;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * OrderItemDetail generated by hbm2java
 */
@Entity
@Table(name = "order_item_detail")
public class OrderItemDetail implements java.io.Serializable {

	private static final long serialVersionUID = 3013689761691407740L;
	private Long orderItemDetailId;
	private String itemNum;
	private String itemUpcCd;
	private String itemSkuCd;
	private Integer seqNum;
	private String itemShortDesc;
	private Integer itemTierQty;
	private Float itemTierPrice;
	private Integer itemOrderQty;
	private Float itemDetailAmount;
	private Float itemDetailDiscountAmount;
	private String recUpdateBy;
	private Date recUpdateDatetime;
	private String recCreateBy;
	private Date recCreateDatetime;
	private Set<OrderDetailTax> orderDetailTaxes = new HashSet<OrderDetailTax>(
			0);
	private Set<OrderAttributeDetail> orderAttributeDetails = new HashSet<OrderAttributeDetail>(
			0);
	private Set<InvoiceDetail> invoiceDetails = new HashSet<InvoiceDetail>(0);
	private Set<CreditDetail> creditDetails = new HashSet<CreditDetail>(0);
	private Set<ShipDetail> shipDetails = new HashSet<ShipDetail>(0);
	private Item item;
	private OrderHeader orderHeader;

	public OrderItemDetail() {
	}

	public OrderItemDetail(String itemNum, String itemUpcCd, String itemSkuCd, Integer seqNum,
			String itemShortDesc, Integer itemOrderQty, Float itemDetailAmount,
			Float itemDetailDiscountAmount, String recUpdateBy,
			Date recUpdateDatetime, String recCreateBy, Date recCreateDatetime) {
		this.itemNum = itemNum;
		this.itemUpcCd = itemUpcCd;
		this.itemSkuCd = itemSkuCd;
		this.seqNum = seqNum;
		this.itemShortDesc = itemShortDesc;
		this.itemOrderQty = itemOrderQty;
		this.itemDetailAmount = itemDetailAmount;
		this.itemDetailDiscountAmount = itemDetailDiscountAmount;
		this.recUpdateBy = recUpdateBy;
		this.recUpdateDatetime = recUpdateDatetime;
		this.recCreateBy = recCreateBy;
		this.recCreateDatetime = recCreateDatetime;
	}

	public OrderItemDetail(String itemNum, String itemUpcCd, String itemSkuCd, Integer seqNum,
			String itemShortDesc, Integer itemTierQty, Float itemTierPrice,
			Integer itemOrderQty, Float itemDetailAmount,
			Float itemDetailDiscountAmount, String recUpdateBy,
			Date recUpdateDatetime, String recCreateBy, Date recCreateDatetime,
			Set<OrderDetailTax> orderDetailTaxes,
			Set<OrderAttributeDetail> orderAttributeDetails,
			Set<InvoiceDetail> invoiceDetails, Set<CreditDetail> creditDetails,
			Set<ShipDetail> shipDetails, Item item, OrderHeader orderHeader) {
		this.itemNum = itemNum;
		this.itemUpcCd = itemUpcCd;
		this.itemSkuCd = itemSkuCd;
		this.seqNum = seqNum;
		this.itemShortDesc = itemShortDesc;
		this.itemTierQty = itemTierQty;
		this.itemTierPrice = itemTierPrice;
		this.itemOrderQty = itemOrderQty;
		this.itemDetailAmount = itemDetailAmount;
		this.itemDetailDiscountAmount = itemDetailDiscountAmount;
		this.recUpdateBy = recUpdateBy;
		this.recUpdateDatetime = recUpdateDatetime;
		this.recCreateBy = recCreateBy;
		this.recCreateDatetime = recCreateDatetime;
		this.orderDetailTaxes = orderDetailTaxes;
		this.orderAttributeDetails = orderAttributeDetails;
		this.invoiceDetails = invoiceDetails;
		this.creditDetails = creditDetails;
		this.shipDetails = shipDetails;
		this.item = item;
		this.orderHeader = orderHeader;
	}

	@Id
	@GeneratedValue
	@Column(name = "order_item_detail_id", nullable = false)
	public Long getOrderItemDetailId() {
		return this.orderItemDetailId;
	}

	public void setOrderItemDetailId(Long orderItemDetailId) {
		this.orderItemDetailId = orderItemDetailId;
	}

	@Column(name = "item_num", nullable = false, length = 20)
	public String getItemNum() {
		return this.itemNum;
	}

	public void setItemNum(String itemNum) {
		this.itemNum = itemNum;
	}

	@Column(name = "item_upc_cd", nullable = false, length = 20)
	public String getItemUpcCd() {
		return this.itemUpcCd;
	}

	public void setItemUpcCd(String itemUpcCd) {
		this.itemUpcCd = itemUpcCd;
	}

	@Column(name = "item_sku_cd", nullable = false, length = 40)
	public String getItemSkuCd() {
		return this.itemSkuCd;
	}

	public void setItemSkuCd(String itemSkuCd) {
		this.itemSkuCd = itemSkuCd;
	}

	@Column(name = "seq_num", nullable = false)
	public Integer getSeqNum() {
		return this.seqNum;
	}

	public void setSeqNum(Integer seqNum) {
		this.seqNum = seqNum;
	}

	@Column(name = "item_short_desc", nullable = false, length = 80)
	public String getItemShortDesc() {
		return this.itemShortDesc;
	}

	public void setItemShortDesc(String itemShortDesc) {
		this.itemShortDesc = itemShortDesc;
	}

	@Column(name = "item_tier_qty")
	public Integer getItemTierQty() {
		return this.itemTierQty;
	}

	public void setItemTierQty(Integer itemTierQty) {
		this.itemTierQty = itemTierQty;
	}

	@Column(name = "item_tier_price")
	public Float getItemTierPrice() {
		return this.itemTierPrice;
	}

	public void setItemTierPrice(Float itemTierPrice) {
		this.itemTierPrice = itemTierPrice;
	}

	@Column(name = "item_order_qty", nullable = false)
	public Integer getItemOrderQty() {
		return this.itemOrderQty;
	}

	public void setItemOrderQty(Integer itemOrderQty) {
		this.itemOrderQty = itemOrderQty;
	}

	@Column(name = "iitem_detail_amount", nullable = false)
	public Float getItemDetailAmount() {
		return this.itemDetailAmount;
	}

	public void setItemDetailAmount(Float itemDetailAmount) {
		this.itemDetailAmount = itemDetailAmount;
	}

	@Column(name = "item_detail_discount_amount", nullable = false)
	public Float getItemDetailDiscountAmount() {
		return this.itemDetailDiscountAmount;
	}

	public void setItemDetailDiscountAmount(Float itemDetailDiscountAmount) {
		this.itemDetailDiscountAmount = itemDetailDiscountAmount;
	}

	@Column(name = "rec_update_by", nullable = false, length = 20)
	public String getRecUpdateBy() {
		return this.recUpdateBy;
	}

	public void setRecUpdateBy(String recUpdateBy) {
		this.recUpdateBy = recUpdateBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "rec_update_datetime", nullable = false)
	public Date getRecUpdateDatetime() {
		return this.recUpdateDatetime;
	}

	public void setRecUpdateDatetime(Date recUpdateDatetime) {
		this.recUpdateDatetime = recUpdateDatetime;
	}

	@Column(name = "rec_create_by", nullable = false, length = 20)
	public String getRecCreateBy() {
		return this.recCreateBy;
	}

	public void setRecCreateBy(String recCreateBy) {
		this.recCreateBy = recCreateBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "rec_create_datetime", nullable = false)
	public Date getRecCreateDatetime() {
		return this.recCreateDatetime;
	}

	public void setRecCreateDatetime(Date recCreateDatetime) {
		this.recCreateDatetime = recCreateDatetime;
	}

	@OneToMany(fetch = FetchType.LAZY)
	@JoinColumn(name = "order_item_detail_id", updatable = false)
	public Set<OrderDetailTax> getOrderDetailTaxes() {
		return this.orderDetailTaxes;
	}

	public void setOrderDetailTaxes(Set<OrderDetailTax> orderDetailTaxes) {
		this.orderDetailTaxes = orderDetailTaxes;
	}

	@OneToMany(fetch = FetchType.LAZY)
	@JoinColumn(name = "order_item_detail_id", updatable = false)
	public Set<OrderAttributeDetail> getOrderAttributeDetails() {
		return this.orderAttributeDetails;
	}

	public void setOrderAttributeDetails(
			Set<OrderAttributeDetail> orderAttributeDetails) {
		this.orderAttributeDetails = orderAttributeDetails;
	}

	@OneToMany(fetch = FetchType.LAZY)
	@JoinColumn(name = "order_item_detail_id", updatable = false)
	public Set<InvoiceDetail> getInvoiceDetails() {
		return this.invoiceDetails;
	}

	public void setInvoiceDetails(Set<InvoiceDetail> invoiceDetails) {
		this.invoiceDetails = invoiceDetails;
	}

	@OneToMany(fetch = FetchType.LAZY)
	@JoinColumn(name = "order_item_detail_id", updatable = false)
	public Set<CreditDetail> getCreditDetails() {
		return this.creditDetails;
	}

	public void setCreditDetails(Set<CreditDetail> creditDetails) {
		this.creditDetails = creditDetails;
	}

	@OneToMany(fetch = FetchType.LAZY)
	@JoinColumn(name = "order_item_detail_id", updatable = false)
	public Set<ShipDetail> getShipDetails() {
		return this.shipDetails;
	}

	public void setShipDetails(Set<ShipDetail> shipDetails) {
		this.shipDetails = shipDetails;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "item_id", nullable = true)
	public Item getItem() {
		return this.item;
	}

	public void setItem(Item item) {
		this.item = item;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "order_header_id")
	public OrderHeader getOrderHeader() {
		return this.orderHeader;
	}

	public void setOrderHeader(OrderHeader orderHeader) {
		this.orderHeader = orderHeader;
	}

}
