/*
 * Copyright 2007-2010 JadaSite.

 * This file is part of JadaSite.
 
 * JadaSite is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.

 * JadaSite is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.

 * You should have received a copy of the GNU General Public License
 * along with JadaSite.  If not, see <http://www.gnu.org/licenses/>.
 */

package com.jada.jpa.entity;

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * OrderAddress generated by hbm2java
 */
@Entity
@Table(name = "order_address")
public class OrderAddress implements java.io.Serializable {

	private static final long serialVersionUID = 5259685903404243579L;
	private Long orderAddressId;
	private String custUseAddress;
	private String custPrefix;
	private String custFirstName;
	private String custMiddleName;
	private String custLastName;
	private String custSuffix;
	private String custAddressLine1;
	private String custAddressLine2;
	private String custCityName;
	private String custStateName;
	private String custStateCode;
	private String custCountryName;
	private String custCountryCode;
	private String custZipCode;
	private String custPhoneNum;
	private String custFaxNum;
	private String recUpdateBy;
	private Date recUpdateDatetime;
	private String recCreateBy;
	private Date recCreateDatetime;
	private Country country;
	private State state;

	public OrderAddress() {
	}

	public OrderAddress(String recUpdateBy, Date recUpdateDatetime,
			String recCreateBy, Date recCreateDatetime) {
		this.recUpdateBy = recUpdateBy;
		this.recUpdateDatetime = recUpdateDatetime;
		this.recCreateBy = recCreateBy;
		this.recCreateDatetime = recCreateDatetime;
	}

	public OrderAddress(String custUseAddress, String custPrefix,
			String custFirstName, String custMiddleName, String custLastName,
			String custSuffix, String custAddressLine1,
			String custAddressLine2, String custCityName, String custStateName,
			String custStateCode, String custCountryName,
			String custCountryCode, String custZipCode, String custPhoneNum,
			String custFaxNum, String recUpdateBy, Date recUpdateDatetime,
			String recCreateBy, Date recCreateDatetime, Country country,
			State state) {
		this.custUseAddress = custUseAddress;
		this.custPrefix = custPrefix;
		this.custFirstName = custFirstName;
		this.custMiddleName = custMiddleName;
		this.custLastName = custLastName;
		this.custSuffix = custSuffix;
		this.custAddressLine1 = custAddressLine1;
		this.custAddressLine2 = custAddressLine2;
		this.custCityName = custCityName;
		this.custStateName = custStateName;
		this.custStateCode = custStateCode;
		this.custCountryName = custCountryName;
		this.custCountryCode = custCountryCode;
		this.custZipCode = custZipCode;
		this.custPhoneNum = custPhoneNum;
		this.custFaxNum = custFaxNum;
		this.recUpdateBy = recUpdateBy;
		this.recUpdateDatetime = recUpdateDatetime;
		this.recCreateBy = recCreateBy;
		this.recCreateDatetime = recCreateDatetime;
		this.country = country;
		this.state = state;
	}

	@Id
	@GeneratedValue
	@Column(name = "order_address_id", nullable = false)
	public Long getOrderAddressId() {
		return this.orderAddressId;
	}

	public void setOrderAddressId(Long orderAddressId) {
		this.orderAddressId = orderAddressId;
	}

	@Column(name = "cust_use_address", length = 1)
	public String getCustUseAddress() {
		return this.custUseAddress;
	}

	public void setCustUseAddress(String custUseAddress) {
		this.custUseAddress = custUseAddress;
	}

	@Column(name = "cust_prefix", length = 20)
	public String getCustPrefix() {
		return this.custPrefix;
	}

	public void setCustPrefix(String custPrefix) {
		this.custPrefix = custPrefix;
	}

	@Column(name = "cust_first_name", length = 20)
	public String getCustFirstName() {
		return this.custFirstName;
	}

	public void setCustFirstName(String custFirstName) {
		this.custFirstName = custFirstName;
	}

	@Column(name = "cust_middle_name", length = 20)
	public String getCustMiddleName() {
		return this.custMiddleName;
	}

	public void setCustMiddleName(String custMiddleName) {
		this.custMiddleName = custMiddleName;
	}

	@Column(name = "cust_last_name", length = 20)
	public String getCustLastName() {
		return this.custLastName;
	}

	public void setCustLastName(String custLastName) {
		this.custLastName = custLastName;
	}

	@Column(name = "cust_suffix", length = 20)
	public String getCustSuffix() {
		return this.custSuffix;
	}

	public void setCustSuffix(String custSuffix) {
		this.custSuffix = custSuffix;
	}

	@Column(name = "cust_address_line1", length = 30)
	public String getCustAddressLine1() {
		return this.custAddressLine1;
	}

	public void setCustAddressLine1(String custAddressLine1) {
		this.custAddressLine1 = custAddressLine1;
	}

	@Column(name = "cust_address_line2", length = 30)
	public String getCustAddressLine2() {
		return this.custAddressLine2;
	}

	public void setCustAddressLine2(String custAddressLine2) {
		this.custAddressLine2 = custAddressLine2;
	}

	@Column(name = "cust_city_name", length = 25)
	public String getCustCityName() {
		return this.custCityName;
	}

	public void setCustCityName(String custCityName) {
		this.custCityName = custCityName;
	}

	@Column(name = "cust_state_name", length = 40)
	public String getCustStateName() {
		return this.custStateName;
	}

	public void setCustStateName(String custStateName) {
		this.custStateName = custStateName;
	}

	@Column(name = "cust_state_code", length = 2)
	public String getCustStateCode() {
		return this.custStateCode;
	}

	public void setCustStateCode(String custStateCode) {
		this.custStateCode = custStateCode;
	}

	@Column(name = "cust_country_name", length = 40)
	public String getCustCountryName() {
		return this.custCountryName;
	}

	public void setCustCountryName(String custCountryName) {
		this.custCountryName = custCountryName;
	}

	@Column(name = "cust_country_code", length = 2)
	public String getCustCountryCode() {
		return this.custCountryCode;
	}

	public void setCustCountryCode(String custCountryCode) {
		this.custCountryCode = custCountryCode;
	}

	@Column(name = "cust_zip_code", length = 10)
	public String getCustZipCode() {
		return this.custZipCode;
	}

	public void setCustZipCode(String custZipCode) {
		this.custZipCode = custZipCode;
	}

	@Column(name = "cust_phone_num", length = 15)
	public String getCustPhoneNum() {
		return this.custPhoneNum;
	}

	public void setCustPhoneNum(String custPhoneNum) {
		this.custPhoneNum = custPhoneNum;
	}

	@Column(name = "cust_fax_num", length = 15)
	public String getCustFaxNum() {
		return this.custFaxNum;
	}

	public void setCustFaxNum(String custFaxNum) {
		this.custFaxNum = custFaxNum;
	}

	@Column(name = "rec_update_by", nullable = false, length = 20)
	public String getRecUpdateBy() {
		return this.recUpdateBy;
	}

	public void setRecUpdateBy(String recUpdateBy) {
		this.recUpdateBy = recUpdateBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "rec_update_datetime", nullable = false)
	public Date getRecUpdateDatetime() {
		return this.recUpdateDatetime;
	}

	public void setRecUpdateDatetime(Date recUpdateDatetime) {
		this.recUpdateDatetime = recUpdateDatetime;
	}

	@Column(name = "rec_create_by", nullable = false, length = 20)
	public String getRecCreateBy() {
		return this.recCreateBy;
	}

	public void setRecCreateBy(String recCreateBy) {
		this.recCreateBy = recCreateBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "rec_create_datetime", nullable = false)
	public Date getRecCreateDatetime() {
		return this.recCreateDatetime;
	}

	public void setRecCreateDatetime(Date recCreateDatetime) {
		this.recCreateDatetime = recCreateDatetime;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "country_id")
	public Country getCountry() {
		return this.country;
	}

	public void setCountry(Country country) {
		this.country = country;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "state_id")
	public State getState() {
		return this.state;
	}

	public void setState(State state) {
		this.state = state;
	}

}
