/*
 * Copyright 2007-2010 JadaSite.

 * This file is part of JadaSite.
 
 * JadaSite is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.

 * JadaSite is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.

 * You should have received a copy of the GNU General Public License
 * along with JadaSite.  If not, see <http://www.gnu.org/licenses/>.
 */

package com.jada.jpa.entity;

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PaymentTran generated by hbm2java
 */
@Entity
@Table(name = "payment_tran")
public class PaymentTran implements java.io.Serializable {

	private static final long serialVersionUID = 3343638726136783870L;
	private Long paymentTranId;
	private String authCode;
	private String paymentReference1;
	private String paymentReference2;
	private String paymentReference3;
	private String paymentReference4;
	private String paymentReference5;
	private Date tranDatetime;
	private String recUpdateBy;
	private Date recUpdateDatetime;
	private String recCreateBy;
	private Date recCreateDatetime;

	public PaymentTran() {
	}

	public PaymentTran(String authCode, Date tranDatetime, String recUpdateBy,
			Date recUpdateDatetime, String recCreateBy, Date recCreateDatetime) {
		this.authCode = authCode;
		this.tranDatetime = tranDatetime;
		this.recUpdateBy = recUpdateBy;
		this.recUpdateDatetime = recUpdateDatetime;
		this.recCreateBy = recCreateBy;
		this.recCreateDatetime = recCreateDatetime;
	}

	public PaymentTran(String authCode, String paymentReference1,
			String paymentReference2, String paymentReference3,
			String paymentReference4, String paymentReference5,
			Date tranDatetime, String recUpdateBy, Date recUpdateDatetime,
			String recCreateBy, Date recCreateDatetime) {
		this.authCode = authCode;
		this.paymentReference1 = paymentReference1;
		this.paymentReference2 = paymentReference2;
		this.paymentReference3 = paymentReference3;
		this.paymentReference4 = paymentReference4;
		this.paymentReference5 = paymentReference5;
		this.tranDatetime = tranDatetime;
		this.recUpdateBy = recUpdateBy;
		this.recUpdateDatetime = recUpdateDatetime;
		this.recCreateBy = recCreateBy;
		this.recCreateDatetime = recCreateDatetime;
	}

	@Id
	@GeneratedValue
	@Column(name = "payment_tran_id", nullable = false)
	public Long getPaymentTranId() {
		return this.paymentTranId;
	}

	public void setPaymentTranId(Long paymentTranId) {
		this.paymentTranId = paymentTranId;
	}

	@Column(name = "auth_code", nullable = false, length = 30)
	public String getAuthCode() {
		return this.authCode;
	}

	public void setAuthCode(String authCode) {
		this.authCode = authCode;
	}

	@Column(name = "payment_reference1", length = 30)
	public String getPaymentReference1() {
		return this.paymentReference1;
	}

	public void setPaymentReference1(String paymentReference1) {
		this.paymentReference1 = paymentReference1;
	}

	@Column(name = "payment_reference2", length = 30)
	public String getPaymentReference2() {
		return this.paymentReference2;
	}

	public void setPaymentReference2(String paymentReference2) {
		this.paymentReference2 = paymentReference2;
	}

	@Column(name = "payment_reference3", length = 30)
	public String getPaymentReference3() {
		return this.paymentReference3;
	}

	public void setPaymentReference3(String paymentReference3) {
		this.paymentReference3 = paymentReference3;
	}

	@Column(name = "payment_reference4", length = 30)
	public String getPaymentReference4() {
		return this.paymentReference4;
	}

	public void setPaymentReference4(String paymentReference4) {
		this.paymentReference4 = paymentReference4;
	}

	@Column(name = "payment_reference5", length = 30)
	public String getPaymentReference5() {
		return this.paymentReference5;
	}

	public void setPaymentReference5(String paymentReference5) {
		this.paymentReference5 = paymentReference5;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "tran_datetime", nullable = false)
	public Date getTranDatetime() {
		return this.tranDatetime;
	}

	public void setTranDatetime(Date tranDatetime) {
		this.tranDatetime = tranDatetime;
	}

	@Column(name = "rec_update_by", nullable = false, length = 20)
	public String getRecUpdateBy() {
		return this.recUpdateBy;
	}

	public void setRecUpdateBy(String recUpdateBy) {
		this.recUpdateBy = recUpdateBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "rec_update_datetime", nullable = false)
	public Date getRecUpdateDatetime() {
		return this.recUpdateDatetime;
	}

	public void setRecUpdateDatetime(Date recUpdateDatetime) {
		this.recUpdateDatetime = recUpdateDatetime;
	}

	@Column(name = "rec_create_by", nullable = false, length = 20)
	public String getRecCreateBy() {
		return this.recCreateBy;
	}

	public void setRecCreateBy(String recCreateBy) {
		this.recCreateBy = recCreateBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "rec_create_datetime", nullable = false)
	public Date getRecCreateDatetime() {
		return this.recCreateDatetime;
	}

	public void setRecCreateDatetime(Date recCreateDatetime) {
		this.recCreateDatetime = recCreateDatetime;
	}

}
