/*
 * Copyright 2007-2010 JadaSite.

 * This file is part of JadaSite.
 
 * JadaSite is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.

 * JadaSite is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.

 * You should have received a copy of the GNU General Public License
 * along with JadaSite.  If not, see <http://www.gnu.org/licenses/>.
 */

package com.jada.jpa.entity;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OrderBy;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PollHeader generated by hbm2java
 */
@Entity
@Table(name = "poll_header")
public class PollHeader implements java.io.Serializable {

	private static final long serialVersionUID = 7646288091591323999L;
	private Long pollHeaderId;
	private String pollTopic;
	private Date pollPublishOn;
	private Date pollExpireOn;
	private char published;
	private String recUpdateBy;
	private Date recUpdateDatetime;
	private String recCreateBy;
	private Date recCreateDatetime;
	private String siteId;
	private Set<PollDetail> pollDetails = new HashSet<PollDetail>(0);
	private Site site;

	public PollHeader() {
	}

	public PollHeader(String pollTopic, Date pollPublishOn, Date pollExpireOn,
			char published, String recUpdateBy, Date recUpdateDatetime,
			String recCreateBy, Date recCreateDatetime, String siteId, Site site) {
		this.pollTopic = pollTopic;
		this.pollPublishOn = pollPublishOn;
		this.pollExpireOn = pollExpireOn;
		this.published = published;
		this.recUpdateBy = recUpdateBy;
		this.recUpdateDatetime = recUpdateDatetime;
		this.recCreateBy = recCreateBy;
		this.recCreateDatetime = recCreateDatetime;
		this.siteId = siteId;
		this.site = site;
	}

	public PollHeader(String pollTopic, Date pollPublishOn, Date pollExpireOn,
			char published, String recUpdateBy, Date recUpdateDatetime,
			String recCreateBy, Date recCreateDatetime, String siteId,
			Set<PollDetail> pollDetails, Site site) {
		this.pollTopic = pollTopic;
		this.pollPublishOn = pollPublishOn;
		this.pollExpireOn = pollExpireOn;
		this.published = published;
		this.recUpdateBy = recUpdateBy;
		this.recUpdateDatetime = recUpdateDatetime;
		this.recCreateBy = recCreateBy;
		this.recCreateDatetime = recCreateDatetime;
		this.siteId = siteId;
		this.pollDetails = pollDetails;
		this.site = site;
	}

	@Id
	@GeneratedValue
	@Column(name = "poll_header_id", nullable = false)
	public Long getPollHeaderId() {
		return this.pollHeaderId;
	}

	public void setPollHeaderId(Long pollHeaderId) {
		this.pollHeaderId = pollHeaderId;
	}

	@Column(name = "poll_topic", nullable = false, length = 255)
	public String getPollTopic() {
		return this.pollTopic;
	}

	public void setPollTopic(String pollTopic) {
		this.pollTopic = pollTopic;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "poll_publish_on", nullable = false, length = 10)
	public Date getPollPublishOn() {
		return this.pollPublishOn;
	}

	public void setPollPublishOn(Date pollPublishOn) {
		this.pollPublishOn = pollPublishOn;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "poll_expire_on", nullable = false, length = 10)
	public Date getPollExpireOn() {
		return this.pollExpireOn;
	}

	public void setPollExpireOn(Date pollExpireOn) {
		this.pollExpireOn = pollExpireOn;
	}

	@Column(name = "published", nullable = false, length = 1)
	public char getPublished() {
		return this.published;
	}

	public void setPublished(char published) {
		this.published = published;
	}

	@Column(name = "rec_update_by", nullable = false, length = 20)
	public String getRecUpdateBy() {
		return this.recUpdateBy;
	}

	public void setRecUpdateBy(String recUpdateBy) {
		this.recUpdateBy = recUpdateBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "rec_update_datetime", nullable = false)
	public Date getRecUpdateDatetime() {
		return this.recUpdateDatetime;
	}

	public void setRecUpdateDatetime(Date recUpdateDatetime) {
		this.recUpdateDatetime = recUpdateDatetime;
	}

	@Column(name = "rec_create_by", nullable = false, length = 20)
	public String getRecCreateBy() {
		return this.recCreateBy;
	}

	public void setRecCreateBy(String recCreateBy) {
		this.recCreateBy = recCreateBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "rec_create_datetime", nullable = false)
	public Date getRecCreateDatetime() {
		return this.recCreateDatetime;
	}

	public void setRecCreateDatetime(Date recCreateDatetime) {
		this.recCreateDatetime = recCreateDatetime;
	}

	@Column(name = "site_id", nullable = false, insertable = false, updatable = false, length = 20)
	public String getSiteId() {
		return this.siteId;
	}

	public void setSiteId(String siteId) {
		this.siteId = siteId;
	}

	@OneToMany(fetch = FetchType.LAZY)
	@JoinColumn(name = "poll_header_id")
	@OrderBy(value="seqNum")
	public Set<PollDetail> getPollDetails() {
		return this.pollDetails;
	}

	public void setPollDetails(Set<PollDetail> pollDetails) {
		this.pollDetails = pollDetails;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "site_id", nullable = false)
	public Site getSite() {
		return this.site;
	}

	public void setSite(Site site) {
		this.site = site;
	}

}
