/*
 * Copyright 2007-2010 JadaSite.

 * This file is part of JadaSite.
 
 * JadaSite is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.

 * JadaSite is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.

 * You should have received a copy of the GNU General Public License
 * along with JadaSite.  If not, see <http://www.gnu.org/licenses/>.
 */

package com.jada.jpa.entity;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ShipHeader generated by hbm2java
 */
@Entity
@Table(name = "ship_header")
public class ShipHeader implements java.io.Serializable {

	private static final long serialVersionUID = -895881924437595965L;
	private Long shipHeaderId;
	private String shipNum;
	private String updateInventory;
	private String shipStatus;
	private Date shipDate;
	private String recUpdateBy;
	private Date recUpdateDatetime;
	private String recCreateBy;
	private Date recCreateDatetime;
	private Set<ShipDetail> shipDetails = new HashSet<ShipDetail>(0);
	private Set<OrderTracking> shipTrackings = new HashSet<OrderTracking>(0);
	private OrderHeader orderHeader;

	public ShipHeader() {
	}

	public ShipHeader(String shipNum, String updateInventory,
			String shipStatus, Date shipDate, String recUpdateBy,
			Date recUpdateDatetime, String recCreateBy, Date recCreateDatetime) {
		this.shipNum = shipNum;
		this.updateInventory = updateInventory;
		this.shipStatus = shipStatus;
		this.shipDate = shipDate;
		this.recUpdateBy = recUpdateBy;
		this.recUpdateDatetime = recUpdateDatetime;
		this.recCreateBy = recCreateBy;
		this.recCreateDatetime = recCreateDatetime;
	}

	public ShipHeader(String shipNum, String updateInventory,
			String shipStatus, Date shipDate, String recUpdateBy,
			Date recUpdateDatetime, String recCreateBy, Date recCreateDatetime,
			Set<ShipDetail> shipDetails, Set<OrderTracking> shipTrackings,
			OrderHeader orderHeader) {
		this.shipNum = shipNum;
		this.updateInventory = updateInventory;
		this.shipStatus = shipStatus;
		this.shipDate = shipDate;
		this.recUpdateBy = recUpdateBy;
		this.recUpdateDatetime = recUpdateDatetime;
		this.recCreateBy = recCreateBy;
		this.recCreateDatetime = recCreateDatetime;
		this.shipDetails = shipDetails;
		this.shipTrackings = shipTrackings;
		this.orderHeader = orderHeader;
	}

	@Id
	@GeneratedValue
	@Column(name = "ship_header_id", nullable = false)
	public Long getShipHeaderId() {
		return this.shipHeaderId;
	}

	public void setShipHeaderId(Long shipHeaderId) {
		this.shipHeaderId = shipHeaderId;
	}

	@Column(name = "ship_num", nullable = false, length = 20)
	public String getShipNum() {
		return this.shipNum;
	}

	public void setShipNum(String shipNum) {
		this.shipNum = shipNum;
	}

	@Column(name = "update_inventory", nullable = false, length = 1)
	public String getUpdateInventory() {
		return this.updateInventory;
	}

	public void setUpdateInventory(String updateInventory) {
		this.updateInventory = updateInventory;
	}

	@Column(name = "ship_status", nullable = false, length = 1)
	public String getShipStatus() {
		return this.shipStatus;
	}

	public void setShipStatus(String shipStatus) {
		this.shipStatus = shipStatus;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ship_date", nullable = false)
	public Date getShipDate() {
		return this.shipDate;
	}

	public void setShipDate(Date shipDate) {
		this.shipDate = shipDate;
	}

	@Column(name = "rec_update_by", nullable = false, length = 20)
	public String getRecUpdateBy() {
		return this.recUpdateBy;
	}

	public void setRecUpdateBy(String recUpdateBy) {
		this.recUpdateBy = recUpdateBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "rec_update_datetime", nullable = false)
	public Date getRecUpdateDatetime() {
		return this.recUpdateDatetime;
	}

	public void setRecUpdateDatetime(Date recUpdateDatetime) {
		this.recUpdateDatetime = recUpdateDatetime;
	}

	@Column(name = "rec_create_by", nullable = false, length = 20)
	public String getRecCreateBy() {
		return this.recCreateBy;
	}

	public void setRecCreateBy(String recCreateBy) {
		this.recCreateBy = recCreateBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "rec_create_datetime", nullable = false)
	public Date getRecCreateDatetime() {
		return this.recCreateDatetime;
	}

	public void setRecCreateDatetime(Date recCreateDatetime) {
		this.recCreateDatetime = recCreateDatetime;
	}

	@OneToMany(fetch = FetchType.LAZY)
	@JoinColumn(name = "ship_header_id", updatable = false)
	public Set<ShipDetail> getShipDetails() {
		return this.shipDetails;
	}

	public void setShipDetails(Set<ShipDetail> shipDetails) {
		this.shipDetails = shipDetails;
	}

	@OneToMany(fetch = FetchType.LAZY)
	@JoinColumn(name = "ship_header_id", updatable = false)
	public Set<OrderTracking> getShipTrackings() {
		return this.shipTrackings;
	}

	public void setShipTrackings(Set<OrderTracking> shipTrackings) {
		this.shipTrackings = shipTrackings;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "order_header_id")
	public OrderHeader getOrderHeader() {
		return this.orderHeader;
	}

	public void setOrderHeader(OrderHeader orderHeader) {
		this.orderHeader = orderHeader;
	}

}
