/*
 * Copyright 2007-2010 JadaSite.

 * This file is part of JadaSite.
 
 * JadaSite is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.

 * JadaSite is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.

 * You should have received a copy of the GNU General Public License
 * along with JadaSite.  If not, see <http://www.gnu.org/licenses/>.
 */

package com.jada.jpa.entity;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ShippingRate generated by hbm2java
 */
@Entity
@Table(name = "shipping_rate")
public class ShippingRate implements java.io.Serializable {

	private static final long serialVersionUID = 8773265325443472734L;
	private Long shippingRateId;
	private Float shippingRatePercentage;
	private Float shippingAdditionalRatePercentage;
	private char published;
	private String recUpdateBy;
	private Date recUpdateDatetime;
	private String recCreateBy;
	private Date recCreateDatetime;
	private ShippingRateCurrency shippingRateCurrency;
	private Set<ShippingRateCurrency> shippingRateCurrencies = new HashSet<ShippingRateCurrency>(
			0);

	public ShippingRate() {
	}

	public ShippingRate(char published, String recUpdateBy,
			Date recUpdateDatetime, String recCreateBy, Date recCreateDatetime) {
		this.published = published;
		this.recUpdateBy = recUpdateBy;
		this.recUpdateDatetime = recUpdateDatetime;
		this.recCreateBy = recCreateBy;
		this.recCreateDatetime = recCreateDatetime;
	}

	public ShippingRate(Float shippingRatePercentage,
			Float shippingAdditionalRatePercentage, char published,
			String recUpdateBy, Date recUpdateDatetime, String recCreateBy,
			Date recCreateDatetime, ShippingRateCurrency shippingRateCurrency,
			Set<ShippingRateCurrency> shippingRateCurrencies) {
		this.shippingRatePercentage = shippingRatePercentage;
		this.shippingAdditionalRatePercentage = shippingAdditionalRatePercentage;
		this.published = published;
		this.recUpdateBy = recUpdateBy;
		this.recUpdateDatetime = recUpdateDatetime;
		this.recCreateBy = recCreateBy;
		this.recCreateDatetime = recCreateDatetime;
		this.shippingRateCurrency = shippingRateCurrency;
		this.shippingRateCurrencies = shippingRateCurrencies;
	}

	@Id
	@GeneratedValue
	@Column(name = "shipping_rate_id", nullable = false)
	public Long getShippingRateId() {
		return this.shippingRateId;
	}

	public void setShippingRateId(Long shippingRateId) {
		this.shippingRateId = shippingRateId;
	}

	@Column(name = "shipping_rate_percentage")
	public Float getShippingRatePercentage() {
		return this.shippingRatePercentage;
	}

	public void setShippingRatePercentage(Float shippingRatePercentage) {
		this.shippingRatePercentage = shippingRatePercentage;
	}

	@Column(name = "shipping_additional_rate_percentage")
	public Float getShippingAdditionalRatePercentage() {
		return this.shippingAdditionalRatePercentage;
	}

	public void setShippingAdditionalRatePercentage(
			Float shippingAdditionalRatePercentage) {
		this.shippingAdditionalRatePercentage = shippingAdditionalRatePercentage;
	}

	@Column(name = "published", nullable = false, length = 1)
	public char getPublished() {
		return this.published;
	}

	public void setPublished(char published) {
		this.published = published;
	}

	@Column(name = "rec_update_by", nullable = false, length = 20)
	public String getRecUpdateBy() {
		return this.recUpdateBy;
	}

	public void setRecUpdateBy(String recUpdateBy) {
		this.recUpdateBy = recUpdateBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "rec_update_datetime", nullable = false)
	public Date getRecUpdateDatetime() {
		return this.recUpdateDatetime;
	}

	public void setRecUpdateDatetime(Date recUpdateDatetime) {
		this.recUpdateDatetime = recUpdateDatetime;
	}

	@Column(name = "rec_create_by", nullable = false, length = 20)
	public String getRecCreateBy() {
		return this.recCreateBy;
	}

	public void setRecCreateBy(String recCreateBy) {
		this.recCreateBy = recCreateBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "rec_create_datetime", nullable = false)
	public Date getRecCreateDatetime() {
		return this.recCreateDatetime;
	}

	public void setRecCreateDatetime(Date recCreateDatetime) {
		this.recCreateDatetime = recCreateDatetime;
	}

	@ManyToOne(cascade = CascadeType.ALL, fetch = FetchType.LAZY)
	@JoinColumn(name = "shipping_rate_curr_id")
	public ShippingRateCurrency getShippingRateCurrency() {
		return this.shippingRateCurrency;
	}

	public void setShippingRateCurrency(
			ShippingRateCurrency shippingRateCurrency) {
		this.shippingRateCurrency = shippingRateCurrency;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY)
	@JoinColumn(name = "shipping_rate_id", updatable = false)
	public Set<ShippingRateCurrency> getShippingRateCurrencies() {
		return this.shippingRateCurrencies;
	}

	public void setShippingRateCurrencies(
			Set<ShippingRateCurrency> shippingRateCurrencies) {
		this.shippingRateCurrencies = shippingRateCurrencies;
	}

}
