/*
 * Copyright 2007-2010 JadaSite.

 * This file is part of JadaSite.
 
 * JadaSite is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.

 * JadaSite is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.

 * You should have received a copy of the GNU General Public License
 * along with JadaSite.  If not, see <http://www.gnu.org/licenses/>.
 */

package com.jada.jpa.entity;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ShippingMethodRegion generated by hbm2java
 */
@Entity
@Table(name = "shipping_method_region")
public class ShippingMethodRegion implements java.io.Serializable {

	private static final long serialVersionUID = -5612162979407424747L;
	private Long shippingMethodRegionId;
	private char published;
	private String recUpdateBy;
	private Date recUpdateDatetime;
	private String recCreateBy;
	private Date recCreateDatetime;
	private ShippingRegion shippingRegion;
	private ShippingMethod shippingMethod;
	private Set<ShippingMethodRegionType> shippingMethodRegionTypes = new HashSet<ShippingMethodRegionType>(
			0);

	public ShippingMethodRegion() {
	}

	public ShippingMethodRegion(char published, String recUpdateBy,
			Date recUpdateDatetime, String recCreateBy, Date recCreateDatetime) {
		this.published = published;
		this.recUpdateBy = recUpdateBy;
		this.recUpdateDatetime = recUpdateDatetime;
		this.recCreateBy = recCreateBy;
		this.recCreateDatetime = recCreateDatetime;
	}

	public ShippingMethodRegion(char published, String recUpdateBy,
			Date recUpdateDatetime, String recCreateBy, Date recCreateDatetime,
			ShippingRegion shippingRegion, ShippingMethod shippingMethod,
			Set<ShippingMethodRegionType> shippingMethodRegionTypes) {
		this.published = published;
		this.recUpdateBy = recUpdateBy;
		this.recUpdateDatetime = recUpdateDatetime;
		this.recCreateBy = recCreateBy;
		this.recCreateDatetime = recCreateDatetime;
		this.shippingRegion = shippingRegion;
		this.shippingMethod = shippingMethod;
		this.shippingMethodRegionTypes = shippingMethodRegionTypes;
	}

	@Id
	@GeneratedValue
	@Column(name = "shipping_method_region_id", nullable = false)
	public Long getShippingMethodRegionId() {
		return this.shippingMethodRegionId;
	}

	public void setShippingMethodRegionId(Long shippingMethodRegionId) {
		this.shippingMethodRegionId = shippingMethodRegionId;
	}

	@Column(name = "published", nullable = false, length = 1)
	public char getPublished() {
		return this.published;
	}

	public void setPublished(char published) {
		this.published = published;
	}

	@Column(name = "rec_update_by", nullable = false, length = 20)
	public String getRecUpdateBy() {
		return this.recUpdateBy;
	}

	public void setRecUpdateBy(String recUpdateBy) {
		this.recUpdateBy = recUpdateBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "rec_update_datetime", nullable = false)
	public Date getRecUpdateDatetime() {
		return this.recUpdateDatetime;
	}

	public void setRecUpdateDatetime(Date recUpdateDatetime) {
		this.recUpdateDatetime = recUpdateDatetime;
	}

	@Column(name = "rec_create_by", nullable = false, length = 20)
	public String getRecCreateBy() {
		return this.recCreateBy;
	}

	public void setRecCreateBy(String recCreateBy) {
		this.recCreateBy = recCreateBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "rec_create_datetime", nullable = false)
	public Date getRecCreateDatetime() {
		return this.recCreateDatetime;
	}

	public void setRecCreateDatetime(Date recCreateDatetime) {
		this.recCreateDatetime = recCreateDatetime;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "shipping_region_id")
	public ShippingRegion getShippingRegion() {
		return this.shippingRegion;
	}

	public void setShippingRegion(ShippingRegion shippingRegion) {
		this.shippingRegion = shippingRegion;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "shipping_method_id")
	public ShippingMethod getShippingMethod() {
		return this.shippingMethod;
	}

	public void setShippingMethod(ShippingMethod shippingMethod) {
		this.shippingMethod = shippingMethod;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY)
	@JoinColumn(name = "shipping_method_region_id", updatable = false)
	public Set<ShippingMethodRegionType> getShippingMethodRegionTypes() {
		return this.shippingMethodRegionTypes;
	}

	public void setShippingMethodRegionTypes(
			Set<ShippingMethodRegionType> shippingMethodRegionTypes) {
		this.shippingMethodRegionTypes = shippingMethodRegionTypes;
	}

}
