/*
 * Copyright 2007-2010 JadaSite.

 * This file is part of JadaSite.
 
 * JadaSite is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.

 * JadaSite is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.

 * You should have received a copy of the GNU General Public License
 * along with JadaSite.  If not, see <http://www.gnu.org/licenses/>.
 */

package com.jada.jpa.entity;

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ShippingRateCurrency generated by hbm2java
 */
@Entity
@Table(name = "shipping_rate_currency")
public class ShippingRateCurrency implements java.io.Serializable {

	private static final long serialVersionUID = -2365769669087125363L;
	private Long shippingRateCurrId;
	private Float shippingRateFee;
	private Float shippingAdditionalRateFee;
	private String recUpdateBy;
	private Date recUpdateDatetime;
	private String recCreateBy;
	private Date recCreateDatetime;
	private ShippingRate shippingRate;
	private SiteCurrencyClass siteCurrencyClass;

	public ShippingRateCurrency() {
	}

	public ShippingRateCurrency(String recUpdateBy, Date recUpdateDatetime,
			String recCreateBy, Date recCreateDatetime) {
		this.recUpdateBy = recUpdateBy;
		this.recUpdateDatetime = recUpdateDatetime;
		this.recCreateBy = recCreateBy;
		this.recCreateDatetime = recCreateDatetime;
	}

	public ShippingRateCurrency(Float shippingRateFee,
			Float shippingAdditionalRateFee, String recUpdateBy,
			Date recUpdateDatetime, String recCreateBy, Date recCreateDatetime,
			ShippingRate shippingRate, SiteCurrencyClass siteCurrencyClass) {
		this.shippingRateFee = shippingRateFee;
		this.shippingAdditionalRateFee = shippingAdditionalRateFee;
		this.recUpdateBy = recUpdateBy;
		this.recUpdateDatetime = recUpdateDatetime;
		this.recCreateBy = recCreateBy;
		this.recCreateDatetime = recCreateDatetime;
		this.shippingRate = shippingRate;
		this.siteCurrencyClass = siteCurrencyClass;
	}

	@Id
	@GeneratedValue
	@Column(name = "shipping_rate_curr_id", nullable = false, length = 20)
	public Long getShippingRateCurrId() {
		return this.shippingRateCurrId;
	}

	public void setShippingRateCurrId(Long shippingRateCurrId) {
		this.shippingRateCurrId = shippingRateCurrId;
	}

	@Column(name = "shipping_rate_fee")
	public Float getShippingRateFee() {
		return this.shippingRateFee;
	}

	public void setShippingRateFee(Float shippingRateFee) {
		this.shippingRateFee = shippingRateFee;
	}

	@Column(name = "shipping_additional_rate_fee")
	public Float getShippingAdditionalRateFee() {
		return this.shippingAdditionalRateFee;
	}

	public void setShippingAdditionalRateFee(Float shippingAdditionalRateFee) {
		this.shippingAdditionalRateFee = shippingAdditionalRateFee;
	}

	@Column(name = "rec_update_by", nullable = false, length = 20)
	public String getRecUpdateBy() {
		return this.recUpdateBy;
	}

	public void setRecUpdateBy(String recUpdateBy) {
		this.recUpdateBy = recUpdateBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "rec_update_datetime", nullable = false)
	public Date getRecUpdateDatetime() {
		return this.recUpdateDatetime;
	}

	public void setRecUpdateDatetime(Date recUpdateDatetime) {
		this.recUpdateDatetime = recUpdateDatetime;
	}

	@Column(name = "rec_create_by", nullable = false, length = 20)
	public String getRecCreateBy() {
		return this.recCreateBy;
	}

	public void setRecCreateBy(String recCreateBy) {
		this.recCreateBy = recCreateBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "rec_create_datetime", nullable = false)
	public Date getRecCreateDatetime() {
		return this.recCreateDatetime;
	}

	public void setRecCreateDatetime(Date recCreateDatetime) {
		this.recCreateDatetime = recCreateDatetime;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "shipping_rate_id")
	public ShippingRate getShippingRate() {
		return this.shippingRate;
	}

	public void setShippingRate(ShippingRate shippingRate) {
		this.shippingRate = shippingRate;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "site_currency_class_id")
	public SiteCurrencyClass getSiteCurrencyClass() {
		return this.siteCurrencyClass;
	}

	public void setSiteCurrencyClass(SiteCurrencyClass siteCurrencyClass) {
		this.siteCurrencyClass = siteCurrencyClass;
	}

}
