/*
 * Copyright 2007-2010 JadaSite.

 * This file is part of JadaSite.
 
 * JadaSite is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.

 * JadaSite is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.

 * You should have received a copy of the GNU General Public License
 * along with JadaSite.  If not, see <http://www.gnu.org/licenses/>.
 */

package com.jada.jpa.entity;

import java.util.Date;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ShippingMethodRegionType generated by hbm2java
 */
@Entity
@Table(name = "shipping_method_region_type")
public class ShippingMethodRegionType implements java.io.Serializable {

	private static final long serialVersionUID = 6211784726189793161L;
	private Long shippingMethodRegionTypeId;
	private char published;
	private String recUpdateBy;
	private Date recUpdateDatetime;
	private String recCreateBy;
	private Date recCreateDatetime;
	private ShippingRegion shippingRegion;
	private ShippingMethod shippingMethod;
	private ShippingType shippingType;
	private ShippingMethodRegion shippingMethodRegion;
	private ShippingRate shippingRate;

	public ShippingMethodRegionType() {
	}

	public ShippingMethodRegionType(char published, String recUpdateBy,
			Date recUpdateDatetime, String recCreateBy, Date recCreateDatetime) {
		this.published = published;
		this.recUpdateBy = recUpdateBy;
		this.recUpdateDatetime = recUpdateDatetime;
		this.recCreateBy = recCreateBy;
		this.recCreateDatetime = recCreateDatetime;
	}

	public ShippingMethodRegionType(char published, String recUpdateBy,
			Date recUpdateDatetime, String recCreateBy, Date recCreateDatetime,
			ShippingRegion shippingRegion, ShippingMethod shippingMethod,
			ShippingType shippingType,
			ShippingMethodRegion shippingMethodRegion, ShippingRate shippingRate) {
		this.published = published;
		this.recUpdateBy = recUpdateBy;
		this.recUpdateDatetime = recUpdateDatetime;
		this.recCreateBy = recCreateBy;
		this.recCreateDatetime = recCreateDatetime;
		this.shippingRegion = shippingRegion;
		this.shippingMethod = shippingMethod;
		this.shippingType = shippingType;
		this.shippingMethodRegion = shippingMethodRegion;
		this.shippingRate = shippingRate;
	}

	@Id
	@GeneratedValue
	@Column(name = "shipping_method_region_type_id", nullable = false)
	public Long getShippingMethodRegionTypeId() {
		return this.shippingMethodRegionTypeId;
	}

	public void setShippingMethodRegionTypeId(Long shippingMethodRegionTypeId) {
		this.shippingMethodRegionTypeId = shippingMethodRegionTypeId;
	}

	@Column(name = "published", nullable = false, length = 1)
	public char getPublished() {
		return this.published;
	}

	public void setPublished(char published) {
		this.published = published;
	}

	@Column(name = "rec_update_by", nullable = false, length = 20)
	public String getRecUpdateBy() {
		return this.recUpdateBy;
	}

	public void setRecUpdateBy(String recUpdateBy) {
		this.recUpdateBy = recUpdateBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "rec_update_datetime", nullable = false)
	public Date getRecUpdateDatetime() {
		return this.recUpdateDatetime;
	}

	public void setRecUpdateDatetime(Date recUpdateDatetime) {
		this.recUpdateDatetime = recUpdateDatetime;
	}

	@Column(name = "rec_create_by", nullable = false, length = 20)
	public String getRecCreateBy() {
		return this.recCreateBy;
	}

	public void setRecCreateBy(String recCreateBy) {
		this.recCreateBy = recCreateBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "rec_create_datetime", nullable = false)
	public Date getRecCreateDatetime() {
		return this.recCreateDatetime;
	}

	public void setRecCreateDatetime(Date recCreateDatetime) {
		this.recCreateDatetime = recCreateDatetime;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "shipping_region_id")
	public ShippingRegion getShippingRegion() {
		return this.shippingRegion;
	}

	public void setShippingRegion(ShippingRegion shippingRegion) {
		this.shippingRegion = shippingRegion;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "shipping_method_id")
	public ShippingMethod getShippingMethod() {
		return this.shippingMethod;
	}

	public void setShippingMethod(ShippingMethod shippingMethod) {
		this.shippingMethod = shippingMethod;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "shipping_type_id")
	public ShippingType getShippingType() {
		return this.shippingType;
	}

	public void setShippingType(ShippingType shippingType) {
		this.shippingType = shippingType;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "shipping_method_region_id")
	public ShippingMethodRegion getShippingMethodRegion() {
		return this.shippingMethodRegion;
	}

	public void setShippingMethodRegion(
			ShippingMethodRegion shippingMethodRegion) {
		this.shippingMethodRegion = shippingMethodRegion;
	}

	@ManyToOne(cascade = CascadeType.ALL, fetch = FetchType.LAZY)
	@JoinColumn(name = "shipping_rate_id", unique = true)
	public ShippingRate getShippingRate() {
		return this.shippingRate;
	}

	public void setShippingRate(ShippingRate shippingRate) {
		this.shippingRate = shippingRate;
	}

}
