/*
 * Copyright 2007-2010 JadaSite.

 * This file is part of JadaSite.
 
 * JadaSite is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.

 * JadaSite is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.

 * You should have received a copy of the GNU General Public License
 * along with JadaSite.  If not, see <http://www.gnu.org/licenses/>.
 */

package com.jada.jpa.entity;

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SiteCurrency generated by hbm2java
 */
@Entity
@Table(name = "site_currency")
public class SiteCurrency implements java.io.Serializable {

	private static final long serialVersionUID = -3116381661559568692L;
	private Long siteCurrencyId;
	private Float exchangeRate;
	private char cashPayment;
	private Integer seqNum;
	private char active;
	private String recUpdateBy;
	private Date recUpdateDatetime;
	private String recCreateBy;
	private Date recCreateDatetime;
	private SiteDomain siteDomain;
	private SiteCurrencyClass siteCurrencyClass;
	private PaymentGateway paymentGateway;
	private PaymentGateway payPalPaymentGateway;

	public SiteCurrency() {
	}

	public SiteCurrency(Float exchangeRate, Integer seqNum, char active,
			String recUpdateBy, Date recUpdateDatetime, String recCreateBy,
			Date recCreateDatetime) {
		this.exchangeRate = exchangeRate;
		this.seqNum = seqNum;
		this.active = active;
		this.recUpdateBy = recUpdateBy;
		this.recUpdateDatetime = recUpdateDatetime;
		this.recCreateBy = recCreateBy;
		this.recCreateDatetime = recCreateDatetime;
	}

	public SiteCurrency(Float exchangeRate, char cashPayment, Integer seqNum,
			char active, String recUpdateBy, Date recUpdateDatetime,
			String recCreateBy, Date recCreateDatetime, SiteDomain siteDomain,
			SiteCurrencyClass siteCurrencyClass, PaymentGateway paymentGateway,
			PaymentGateway payPalPaymentGateway) {
		this.exchangeRate = exchangeRate;
		this.cashPayment = cashPayment;
		this.seqNum = seqNum;
		this.active = active;
		this.recUpdateBy = recUpdateBy;
		this.recUpdateDatetime = recUpdateDatetime;
		this.recCreateBy = recCreateBy;
		this.recCreateDatetime = recCreateDatetime;
		this.siteDomain = siteDomain;
		this.siteCurrencyClass = siteCurrencyClass;
		this.paymentGateway = paymentGateway;
		this.payPalPaymentGateway = payPalPaymentGateway;
	}

	@Id
	@GeneratedValue
	@Column(name = "site_currency_id", nullable = false)
	public Long getSiteCurrencyId() {
		return this.siteCurrencyId;
	}

	public void setSiteCurrencyId(Long siteCurrencyId) {
		this.siteCurrencyId = siteCurrencyId;
	}

	@Column(name = "exchange_rate", nullable = false)
	public Float getExchangeRate() {
		return this.exchangeRate;
	}

	public void setExchangeRate(Float exchangeRate) {
		this.exchangeRate = exchangeRate;
	}

	@Column(name = "cash_payment", length = 1)
	public char getCashPayment() {
		return this.cashPayment;
	}

	public void setCashPayment(char cashPayment) {
		this.cashPayment = cashPayment;
	}

	@Column(name = "seq_num", nullable = false)
	public Integer getSeqNum() {
		return this.seqNum;
	}

	public void setSeqNum(Integer seqNum) {
		this.seqNum = seqNum;
	}

	@Column(name = "active", nullable = false, length = 1)
	public char getActive() {
		return this.active;
	}

	public void setActive(char active) {
		this.active = active;
	}

	@Column(name = "rec_update_by", nullable = false, length = 20)
	public String getRecUpdateBy() {
		return this.recUpdateBy;
	}

	public void setRecUpdateBy(String recUpdateBy) {
		this.recUpdateBy = recUpdateBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "rec_update_datetime", nullable = false)
	public Date getRecUpdateDatetime() {
		return this.recUpdateDatetime;
	}

	public void setRecUpdateDatetime(Date recUpdateDatetime) {
		this.recUpdateDatetime = recUpdateDatetime;
	}

	@Column(name = "rec_create_by", nullable = false, length = 20)
	public String getRecCreateBy() {
		return this.recCreateBy;
	}

	public void setRecCreateBy(String recCreateBy) {
		this.recCreateBy = recCreateBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "rec_create_datetime", nullable = false)
	public Date getRecCreateDatetime() {
		return this.recCreateDatetime;
	}

	public void setRecCreateDatetime(Date recCreateDatetime) {
		this.recCreateDatetime = recCreateDatetime;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "site_domain_id")
	public SiteDomain getSiteDomain() {
		return this.siteDomain;
	}

	public void setSiteDomain(SiteDomain siteDomain) {
		this.siteDomain = siteDomain;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "site_currency_class_id")
	public SiteCurrencyClass getSiteCurrencyClass() {
		return this.siteCurrencyClass;
	}

	public void setSiteCurrencyClass(SiteCurrencyClass siteCurrencyClass) {
		this.siteCurrencyClass = siteCurrencyClass;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "payment_gateway_id")
	public PaymentGateway getPaymentGateway() {
		return this.paymentGateway;
	}

	public void setPaymentGateway(PaymentGateway paymentGateway) {
		this.paymentGateway = paymentGateway;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "paypal_payment_gateway_id")
	public PaymentGateway getPayPalPaymentGateway() {
		return this.payPalPaymentGateway;
	}

	public void setPayPalPaymentGateway(PaymentGateway payPalPaymentGateway) {
		this.payPalPaymentGateway = payPalPaymentGateway;
	}

}
