/*
 * Copyright 2007-2010 JadaSite.

 * This file is part of JadaSite.
 
 * JadaSite is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.

 * JadaSite is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.

 * You should have received a copy of the GNU General Public License
 * along with JadaSite.  If not, see <http://www.gnu.org/licenses/>.
 */

package com.jada.jpa.entity;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OrderBy;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SiteDomain generated by hbm2java
 */
@Entity
@Table(name = "site_domain")
public class SiteDomain implements java.io.Serializable {

	private static final long serialVersionUID = 3706458426285304049L;
	private Long siteDomainId;
	private String siteDomainName;
	private String siteDomainPrefix;
	private String sitePublicPortNum;
	private char siteSslEnabled;
	private String siteSecurePortNum;
	private char active;
	private String recUpdateBy;
	private Date recUpdateDatetime;
	private String recCreateBy;
	private Date recCreateDatetime;
	private Site site;
	private HomePage homePage;
	private SiteDomainLanguage siteDomainLanguage;
	private Set<SiteProfile> siteProfiles = new HashSet<SiteProfile>(0);
	private Set<SiteCurrency> siteCurrencies = new HashSet<SiteCurrency>(0);
	private Set<SiteDomainLanguage> siteDomainLanguages = new HashSet<SiteDomainLanguage>(
			0);
	private SiteCurrencyClass baseCurrency;
	private Template template;
	private SiteProfile siteProfileDefault;
	private SiteCurrency siteCurrencyDefault;

	public SiteDomain() {
	}

	public SiteDomain(String siteDomainName, String siteDomainPrefix,
			String sitePublicPortNum, char siteSslEnabled,
			String siteSecurePortNum, char active, String recUpdateBy,
			Date recUpdateDatetime, String recCreateBy, Date recCreateDatetime) {
		this.siteDomainName = siteDomainName;
		this.siteDomainPrefix = siteDomainPrefix;
		this.sitePublicPortNum = sitePublicPortNum;
		this.siteSslEnabled = siteSslEnabled;
		this.siteSecurePortNum = siteSecurePortNum;
		this.active = active;
		this.recUpdateBy = recUpdateBy;
		this.recUpdateDatetime = recUpdateDatetime;
		this.recCreateBy = recCreateBy;
		this.recCreateDatetime = recCreateDatetime;
	}

	public SiteDomain(String siteDomainName, String siteDomainPrefix,
			String sitePublicPortNum, char siteSslEnabled,
			String siteSecurePortNum, char active, String recUpdateBy,
			Date recUpdateDatetime, String recCreateBy, Date recCreateDatetime,
			Site site, HomePage homePage,
			SiteDomainLanguage siteDomainLanguage,
			Set<SiteProfile> siteProfiles, Set<SiteCurrency> siteCurrencies,
			Set<SiteDomainLanguage> siteDomainLanguages,
			SiteCurrencyClass baseCurrency, Template template,
			SiteProfile siteProfileDefault, SiteCurrency siteCurrencyDefault) {
		this.siteDomainName = siteDomainName;
		this.siteDomainPrefix = siteDomainPrefix;
		this.sitePublicPortNum = sitePublicPortNum;
		this.siteSslEnabled = siteSslEnabled;
		this.siteSecurePortNum = siteSecurePortNum;
		this.active = active;
		this.recUpdateBy = recUpdateBy;
		this.recUpdateDatetime = recUpdateDatetime;
		this.recCreateBy = recCreateBy;
		this.recCreateDatetime = recCreateDatetime;
		this.site = site;
		this.homePage = homePage;
		this.siteDomainLanguage = siteDomainLanguage;
		this.siteProfiles = siteProfiles;
		this.siteCurrencies = siteCurrencies;
		this.siteDomainLanguages = siteDomainLanguages;
		this.baseCurrency = baseCurrency;
		this.template = template;
		this.siteProfileDefault = siteProfileDefault;
		this.siteCurrencyDefault = siteCurrencyDefault;
	}

	@Id
	@GeneratedValue
	@Column(name = "site_domain_id", nullable = false)
	public Long getSiteDomainId() {
		return this.siteDomainId;
	}

	public void setSiteDomainId(Long siteDomainId) {
		this.siteDomainId = siteDomainId;
	}

	@Column(name = "site_domain_name", nullable = false, length = 50)
	public String getSiteDomainName() {
		return this.siteDomainName;
	}

	public void setSiteDomainName(String siteDomainName) {
		this.siteDomainName = siteDomainName;
	}

	@Column(name = "site_domain_prefix", nullable = false, length = 50)
	public String getSiteDomainPrefix() {
		return this.siteDomainPrefix;
	}

	public void setSiteDomainPrefix(String siteDomainPrefix) {
		this.siteDomainPrefix = siteDomainPrefix;
	}

	@Column(name = "site_public_port_num", nullable = false, length = 4)
	public String getSitePublicPortNum() {
		return this.sitePublicPortNum;
	}

	public void setSitePublicPortNum(String sitePublicPortNum) {
		this.sitePublicPortNum = sitePublicPortNum;
	}

	@Column(name = "site_ssl_enabled", nullable = false, length = 1)
	public char getSiteSslEnabled() {
		return this.siteSslEnabled;
	}

	public void setSiteSslEnabled(char siteSslEnabled) {
		this.siteSslEnabled = siteSslEnabled;
	}

	@Column(name = "site_secure_port_num", nullable = false, length = 4)
	public String getSiteSecurePortNum() {
		return this.siteSecurePortNum;
	}

	public void setSiteSecurePortNum(String siteSecurePortNum) {
		this.siteSecurePortNum = siteSecurePortNum;
	}

	@Column(name = "active", nullable = false, length = 1)
	public char getActive() {
		return this.active;
	}

	public void setActive(char active) {
		this.active = active;
	}

	@Column(name = "rec_update_by", nullable = false, length = 20)
	public String getRecUpdateBy() {
		return this.recUpdateBy;
	}

	public void setRecUpdateBy(String recUpdateBy) {
		this.recUpdateBy = recUpdateBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "rec_update_datetime", nullable = false)
	public Date getRecUpdateDatetime() {
		return this.recUpdateDatetime;
	}

	public void setRecUpdateDatetime(Date recUpdateDatetime) {
		this.recUpdateDatetime = recUpdateDatetime;
	}

	@Column(name = "rec_create_by", nullable = false, length = 20)
	public String getRecCreateBy() {
		return this.recCreateBy;
	}

	public void setRecCreateBy(String recCreateBy) {
		this.recCreateBy = recCreateBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "rec_create_datetime", nullable = false)
	public Date getRecCreateDatetime() {
		return this.recCreateDatetime;
	}

	public void setRecCreateDatetime(Date recCreateDatetime) {
		this.recCreateDatetime = recCreateDatetime;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "site_id")
	public Site getSite() {
		return this.site;
	}

	public void setSite(Site site) {
		this.site = site;
	}

	@ManyToOne(cascade = CascadeType.ALL, fetch = FetchType.LAZY)
	@JoinColumn(name = "home_page_id")
	public HomePage getHomePage() {
		return this.homePage;
	}

	public void setHomePage(HomePage homePage) {
		this.homePage = homePage;
	}

	@ManyToOne(cascade = CascadeType.ALL, fetch = FetchType.LAZY)
	@JoinColumn(name = "site_domain_lang_id")
	public SiteDomainLanguage getSiteDomainLanguage() {
		return this.siteDomainLanguage;
	}

	public void setSiteDomainLanguage(SiteDomainLanguage siteDomainLanguage) {
		this.siteDomainLanguage = siteDomainLanguage;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY)
	@JoinColumn(name = "site_domain_id")
	@OrderBy(value = "seqNum")
	public Set<SiteProfile> getSiteProfiles() {
		return this.siteProfiles;
	}

	public void setSiteProfiles(Set<SiteProfile> siteProfiles) {
		this.siteProfiles = siteProfiles;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY)
	@JoinColumn(name = "site_domain_id")
	@OrderBy(value = "seqNum")
	public Set<SiteCurrency> getSiteCurrencies() {
		return this.siteCurrencies;
	}

	public void setSiteCurrencies(Set<SiteCurrency> siteCurrencies) {
		this.siteCurrencies = siteCurrencies;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY)
	@JoinColumn(name = "site_domain_id")
	public Set<SiteDomainLanguage> getSiteDomainLanguages() {
		return this.siteDomainLanguages;
	}

	public void setSiteDomainLanguages(
			Set<SiteDomainLanguage> siteDomainLanguages) {
		this.siteDomainLanguages = siteDomainLanguages;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "site_currency_class_id")
	public SiteCurrencyClass getBaseCurrency() {
		return this.baseCurrency;
	}

	public void setBaseCurrency(SiteCurrencyClass baseCurrency) {
		this.baseCurrency = baseCurrency;
	}

	@ManyToOne(cascade = CascadeType.ALL, fetch = FetchType.LAZY)
	@JoinColumn(name = "template_id")
	public Template getTemplate() {
		return this.template;
	}

	public void setTemplate(Template template) {
		this.template = template;
	}

	@ManyToOne(cascade = CascadeType.ALL, fetch = FetchType.LAZY)
	@JoinColumn(name = "site_profile_default_id")
	public SiteProfile getSiteProfileDefault() {
		return this.siteProfileDefault;
	}

	public void setSiteProfileDefault(SiteProfile siteProfileDefault) {
		this.siteProfileDefault = siteProfileDefault;
	}

	@ManyToOne(cascade = CascadeType.ALL, fetch = FetchType.LAZY)
	@JoinColumn(name = "site_currency_default_id")
	public SiteCurrency getSiteCurrencyDefault() {
		return this.siteCurrencyDefault;
	}

	public void setSiteCurrencyDefault(SiteCurrency siteCurrencyDefault) {
		this.siteCurrencyDefault = siteCurrencyDefault;
	}

}
