/*
 * Copyright 2007-2010 JadaSite.

 * This file is part of JadaSite.
 
 * JadaSite is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.

 * JadaSite is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.

 * You should have received a copy of the GNU General Public License
 * along with JadaSite.  If not, see <http://www.gnu.org/licenses/>.
 */

package com.jada.jpa.entity;

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SiteCurrencyClass generated by hbm2java
 */
@Entity
@Table(name = "site_currency_class")
public class SiteCurrencyClass implements java.io.Serializable {

	private static final long serialVersionUID = -189845110725206728L;
	private Long siteCurrencyClassId;
	private String siteCurrencyClassName;
	private String currencyLocaleLanguage;
	private String currencyLocaleCountry;
	private char systemRecord;
	private String recUpdateBy;
	private Date recUpdateDatetime;
	private String recCreateBy;
	private Date recCreateDatetime;
	private Currency currency;
	private Site site;

	public SiteCurrencyClass() {
	}

	public SiteCurrencyClass(String siteCurrencyClassName,
			String currencyLocaleLanguage, String currencyLocaleCountry,
			char systemRecord, String recUpdateBy, Date recUpdateDatetime,
			String recCreateBy, Date recCreateDatetime) {
		this.siteCurrencyClassName = siteCurrencyClassName;
		this.currencyLocaleLanguage = currencyLocaleLanguage;
		this.currencyLocaleCountry = currencyLocaleCountry;
		this.systemRecord = systemRecord;
		this.recUpdateBy = recUpdateBy;
		this.recUpdateDatetime = recUpdateDatetime;
		this.recCreateBy = recCreateBy;
		this.recCreateDatetime = recCreateDatetime;
	}

	public SiteCurrencyClass(String siteCurrencyClassName,
			String currencyLocaleLanguage, String currencyLocaleCountry,
			char systemRecord, String recUpdateBy, Date recUpdateDatetime,
			String recCreateBy, Date recCreateDatetime, Currency currency,
			Site site) {
		this.siteCurrencyClassName = siteCurrencyClassName;
		this.currencyLocaleLanguage = currencyLocaleLanguage;
		this.currencyLocaleCountry = currencyLocaleCountry;
		this.systemRecord = systemRecord;
		this.recUpdateBy = recUpdateBy;
		this.recUpdateDatetime = recUpdateDatetime;
		this.recCreateBy = recCreateBy;
		this.recCreateDatetime = recCreateDatetime;
		this.currency = currency;
		this.site = site;
	}

	@Id
	@GeneratedValue
	@Column(name = "site_currency_class_id", nullable = false)
	public Long getSiteCurrencyClassId() {
		return this.siteCurrencyClassId;
	}

	public void setSiteCurrencyClassId(Long siteCurrencyClassId) {
		this.siteCurrencyClassId = siteCurrencyClassId;
	}

	@Column(name = "site_currency_class_name", nullable = false, length = 40)
	public String getSiteCurrencyClassName() {
		return this.siteCurrencyClassName;
	}

	public void setSiteCurrencyClassName(String siteCurrencyClassName) {
		this.siteCurrencyClassName = siteCurrencyClassName;
	}

	@Column(name = "currency_locale_language", nullable = false, length = 2)
	public String getCurrencyLocaleLanguage() {
		return this.currencyLocaleLanguage;
	}

	public void setCurrencyLocaleLanguage(String currencyLocaleLanguage) {
		this.currencyLocaleLanguage = currencyLocaleLanguage;
	}

	@Column(name = "currency_locale_country", nullable = false, length = 2)
	public String getCurrencyLocaleCountry() {
		return this.currencyLocaleCountry;
	}

	public void setCurrencyLocaleCountry(String currencyLocaleCountry) {
		this.currencyLocaleCountry = currencyLocaleCountry;
	}

	@Column(name = "system_record", nullable = false, length = 1)
	public char getSystemRecord() {
		return this.systemRecord;
	}

	public void setSystemRecord(char systemRecord) {
		this.systemRecord = systemRecord;
	}

	@Column(name = "rec_update_by", nullable = false, length = 20)
	public String getRecUpdateBy() {
		return this.recUpdateBy;
	}

	public void setRecUpdateBy(String recUpdateBy) {
		this.recUpdateBy = recUpdateBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "rec_update_datetime", nullable = false)
	public Date getRecUpdateDatetime() {
		return this.recUpdateDatetime;
	}

	public void setRecUpdateDatetime(Date recUpdateDatetime) {
		this.recUpdateDatetime = recUpdateDatetime;
	}

	@Column(name = "rec_create_by", nullable = false, length = 20)
	public String getRecCreateBy() {
		return this.recCreateBy;
	}

	public void setRecCreateBy(String recCreateBy) {
		this.recCreateBy = recCreateBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "rec_create_datetime", nullable = false)
	public Date getRecCreateDatetime() {
		return this.recCreateDatetime;
	}

	public void setRecCreateDatetime(Date recCreateDatetime) {
		this.recCreateDatetime = recCreateDatetime;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "currency_id")
	public Currency getCurrency() {
		return this.currency;
	}

	public void setCurrency(Currency currency) {
		this.currency = currency;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "site_id")
	public Site getSite() {
		return this.site;
	}

	public void setSite(Site site) {
		this.site = site;
	}

}
