/*
 * Copyright 2007-2010 JadaSite.

 * This file is part of JadaSite.
 
 * JadaSite is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.

 * JadaSite is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.

 * You should have received a copy of the GNU General Public License
 * along with JadaSite.  If not, see <http://www.gnu.org/licenses/>.
 */

package com.jada.jpa.entity;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OrderBy;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Site generated by hbm2java
 */
@Entity
@Table(name = "site")
public class Site implements java.io.Serializable {

	private static final long serialVersionUID = 7270287470683039031L;
	private String siteId;
	private String siteDesc;
	private char shareInventory;
	private char manageInventory;
	private char singleCheckout;
	private Integer listingPageSize;
	private String mailSmtpHost;
	private String mailSmtpPort;
	private String mailSmtpAccount;
	private String mailSmtpPassword;
	private String siteParam;
	private char systemRecord;
	private char active;
	private String recUpdateBy;
	private Date recUpdateDatetime;
	private String recCreateBy;
	private Date recCreateDatetime;
	private Set<User> users = new HashSet<User>(0);
	private Set<SiteDomain> siteDomains = new HashSet<SiteDomain>(0);
	private SiteDomain siteDomainDefault;
	private SiteProfileClass siteProfileClassDefault;
	private SiteCurrencyClass siteCurrencyClassDefault;

	public Site() {
	}

	public Site(String siteId, String siteDesc, char shareInventory,
			char manageInventory, char singleCheckout, Integer listingPageSize,
			String mailSmtpHost, String mailSmtpPort, String mailSmtpAccount,
			String mailSmtpPassword, String siteParam, char systemRecord, char active,
			String recUpdateBy, Date recUpdateDatetime, String recCreateBy,
			Date recCreateDatetime) {
		this.siteId = siteId;
		this.siteDesc = siteDesc;
		this.shareInventory = shareInventory;
		this.manageInventory = manageInventory;
		this.singleCheckout = singleCheckout;
		this.listingPageSize = listingPageSize;
		this.mailSmtpHost = mailSmtpHost;
		this.mailSmtpPort = mailSmtpPort;
		this.mailSmtpAccount = mailSmtpAccount;
		this.mailSmtpPassword = mailSmtpPassword;
		this.siteParam = siteParam;
		this.systemRecord = systemRecord;
		this.active = active;
		this.recUpdateBy = recUpdateBy;
		this.recUpdateDatetime = recUpdateDatetime;
		this.recCreateBy = recCreateBy;
		this.recCreateDatetime = recCreateDatetime;
	}

	public Site(String siteId, String siteDesc, char shareInventory,
			char manageInventory, char singleCheckout, Integer listingPageSize,
			String mailSmtpHost, String mailSmtpPort, String mailSmtpAccount,
			String mailSmtpPassword, String siteParam, char systemRecord, char active,
			String recUpdateBy, Date recUpdateDatetime, String recCreateBy,
			Date recCreateDatetime, Set<User> users,
			Set<SiteDomain> siteDomains, SiteDomain siteDomainDefault,
			SiteProfileClass siteProfileClassDefault,
			SiteCurrencyClass siteCurrencyClassDefault) {
		this.siteId = siteId;
		this.siteDesc = siteDesc;
		this.shareInventory = shareInventory;
		this.manageInventory = manageInventory;
		this.singleCheckout = singleCheckout;
		this.listingPageSize = listingPageSize;
		this.mailSmtpHost = mailSmtpHost;
		this.mailSmtpPort = mailSmtpPort;
		this.mailSmtpAccount = mailSmtpAccount;
		this.mailSmtpPassword = mailSmtpPassword;
		this.siteParam = siteParam;
		this.systemRecord = systemRecord;
		this.active = active;
		this.recUpdateBy = recUpdateBy;
		this.recUpdateDatetime = recUpdateDatetime;
		this.recCreateBy = recCreateBy;
		this.recCreateDatetime = recCreateDatetime;
		this.users = users;
		this.siteDomains = siteDomains;
		this.siteDomainDefault = siteDomainDefault;
		this.siteProfileClassDefault = siteProfileClassDefault;
		this.siteCurrencyClassDefault = siteCurrencyClassDefault;
	}

	@Id
	@Column(name = "site_id", nullable = false, length = 20)
	public String getSiteId() {
		return this.siteId;
	}

	public void setSiteId(String siteId) {
		this.siteId = siteId;
	}

	@Column(name = "site_desc", nullable = false, length = 50)
	public String getSiteDesc() {
		return this.siteDesc;
	}

	public void setSiteDesc(String siteDesc) {
		this.siteDesc = siteDesc;
	}

	@Column(name = "share_inventory", nullable = false, length = 1)
	public char getShareInventory() {
		return this.shareInventory;
	}

	public void setShareInventory(char shareInventory) {
		this.shareInventory = shareInventory;
	}

	@Column(name = "manage_inventory", nullable = false, length = 1)
	public char getManageInventory() {
		return this.manageInventory;
	}

	public void setManageInventory(char manageInventory) {
		this.manageInventory = manageInventory;
	}

	@Column(name = "single_checkout", nullable = false, length = 1)
	public char getSingleCheckout() {
		return this.singleCheckout;
	}

	public void setSingleCheckout(char singleCheckout) {
		this.singleCheckout = singleCheckout;
	}

	@Column(name = "listing_page_size", nullable = false)
	public Integer getListingPageSize() {
		return this.listingPageSize;
	}

	public void setListingPageSize(Integer listingPageSize) {
		this.listingPageSize = listingPageSize;
	}

	@Column(name = "mail_smtp_host", nullable = false, length = 50)
	public String getMailSmtpHost() {
		return this.mailSmtpHost;
	}

	public void setMailSmtpHost(String mailSmtpHost) {
		this.mailSmtpHost = mailSmtpHost;
	}

	@Column(name = "mail_smtp_port", nullable = false, length = 4)
	public String getMailSmtpPort() {
		return this.mailSmtpPort;
	}

	public void setMailSmtpPort(String mailSmtpPort) {
		this.mailSmtpPort = mailSmtpPort;
	}

	@Column(name = "mail_smtp_account", nullable = false, length = 50)
	public String getMailSmtpAccount() {
		return this.mailSmtpAccount;
	}

	public void setMailSmtpAccount(String mailSmtpAccount) {
		this.mailSmtpAccount = mailSmtpAccount;
	}

	@Column(name = "mail_smtp_password", nullable = false, length = 50)
	public String getMailSmtpPassword() {
		return this.mailSmtpPassword;
	}

	public void setMailSmtpPassword(String mailSmtpPassword) {
		this.mailSmtpPassword = mailSmtpPassword;
	}
	
	@Column(name = "site_param", length = 100000000)
	public String getSiteParam() {
		return this.siteParam;
	}

	public void setSiteParam(String siteParam) {
		this.siteParam = siteParam;
	}

	@Column(name = "system_record", nullable = false, length = 1)
	public char getSystemRecord() {
		return this.systemRecord;
	}

	public void setSystemRecord(char systemRecord) {
		this.systemRecord = systemRecord;
	}

	@Column(name = "active", nullable = false, length = 1)
	public char getActive() {
		return this.active;
	}

	public void setActive(char active) {
		this.active = active;
	}

	@Column(name = "rec_update_by", nullable = false, length = 20)
	public String getRecUpdateBy() {
		return this.recUpdateBy;
	}

	public void setRecUpdateBy(String recUpdateBy) {
		this.recUpdateBy = recUpdateBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "rec_update_datetime", nullable = false)
	public Date getRecUpdateDatetime() {
		return this.recUpdateDatetime;
	}

	public void setRecUpdateDatetime(Date recUpdateDatetime) {
		this.recUpdateDatetime = recUpdateDatetime;
	}

	@Column(name = "rec_create_by", nullable = false, length = 20)
	public String getRecCreateBy() {
		return this.recCreateBy;
	}

	public void setRecCreateBy(String recCreateBy) {
		this.recCreateBy = recCreateBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "rec_create_datetime", nullable = false)
	public Date getRecCreateDatetime() {
		return this.recCreateDatetime;
	}

	public void setRecCreateDatetime(Date recCreateDatetime) {
		this.recCreateDatetime = recCreateDatetime;
	}

	@ManyToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "sites")
	public Set<User> getUsers() {
		return this.users;
	}

	public void setUsers(Set<User> users) {
		this.users = users;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY)
	@JoinColumn(name = "site_id", updatable = false)
	@OrderBy(value="siteDomainId")
	public Set<SiteDomain> getSiteDomains() {
		return this.siteDomains;
	}

	public void setSiteDomains(Set<SiteDomain> siteDomains) {
		this.siteDomains = siteDomains;
	}

	@ManyToOne(cascade = CascadeType.ALL, fetch = FetchType.LAZY)
	@JoinColumn(name = "site_domain_default_id")
	public SiteDomain getSiteDomainDefault() {
		return this.siteDomainDefault;
	}

	public void setSiteDomainDefault(SiteDomain siteDomainDefault) {
		this.siteDomainDefault = siteDomainDefault;
	}

	@ManyToOne(cascade = CascadeType.ALL, fetch = FetchType.LAZY)
	@JoinColumn(name = "site_profile_class_default_id")
	public SiteProfileClass getSiteProfileClassDefault() {
		return this.siteProfileClassDefault;
	}

	public void setSiteProfileClassDefault(
			SiteProfileClass siteProfileClassDefault) {
		this.siteProfileClassDefault = siteProfileClassDefault;
	}

	@ManyToOne(cascade = CascadeType.ALL, fetch = FetchType.LAZY)
	@JoinColumn(name = "site_currency_class_default_id")
	public SiteCurrencyClass getSiteCurrencyClassDefault() {
		return this.siteCurrencyClassDefault;
	}

	public void setSiteCurrencyClassDefault(
			SiteCurrencyClass siteCurrencyClassDefault) {
		this.siteCurrencyClassDefault = siteCurrencyClassDefault;
	}

}
