/*
 * Copyright 2007-2010 JadaSite.

 * This file is part of JadaSite.
 
 * JadaSite is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.

 * JadaSite is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.

 * You should have received a copy of the GNU General Public License
 * along with JadaSite.  If not, see <http://www.gnu.org/licenses/>.
 */

package com.jada.jpa.entity;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Tax generated by hbm2java
 */
@Entity
@Table(name = "tax")
public class Tax implements java.io.Serializable {

	private static final long serialVersionUID = -6070088323741419944L;
	private Long taxId;
	private Float taxRate;
	private char published;
	private String recUpdateBy;
	private Date recUpdateDatetime;
	private String recCreateBy;
	private Date recCreateDatetime;
	private String siteId;
	private TaxLanguage taxLanguage;
	private Set<Country> countries = new HashSet<Country>(0);
	private Set<State> states = new HashSet<State>(0);
	private Set<TaxLanguage> taxLanguages = new HashSet<TaxLanguage>(0);
	private Site site;

	public Tax() {
	}

	public Tax(Float taxRate, char published, String recUpdateBy,
			Date recUpdateDatetime, String recCreateBy, Date recCreateDatetime,
			String siteId, TaxLanguage taxLanguage, Site site) {
		this.taxRate = taxRate;
		this.published = published;
		this.recUpdateBy = recUpdateBy;
		this.recUpdateDatetime = recUpdateDatetime;
		this.recCreateBy = recCreateBy;
		this.recCreateDatetime = recCreateDatetime;
		this.siteId = siteId;
		this.taxLanguage = taxLanguage;
		this.site = site;
	}

	public Tax(Float taxRate, char published, String recUpdateBy,
			Date recUpdateDatetime, String recCreateBy, Date recCreateDatetime,
			String siteId, TaxLanguage taxLanguage, Set<Country> countries,
			Set<State> states, Set<TaxLanguage> taxLanguages, Site site) {
		this.taxRate = taxRate;
		this.published = published;
		this.recUpdateBy = recUpdateBy;
		this.recUpdateDatetime = recUpdateDatetime;
		this.recCreateBy = recCreateBy;
		this.recCreateDatetime = recCreateDatetime;
		this.siteId = siteId;
		this.taxLanguage = taxLanguage;
		this.countries = countries;
		this.states = states;
		this.taxLanguages = taxLanguages;
		this.site = site;
	}

	@Id
	@GeneratedValue
	@Column(name = "tax_id", nullable = false)
	public Long getTaxId() {
		return this.taxId;
	}

	public void setTaxId(Long taxId) {
		this.taxId = taxId;
	}

	@Column(name = "tax_rate", nullable = false)
	public Float getTaxRate() {
		return this.taxRate;
	}

	public void setTaxRate(Float taxRate) {
		this.taxRate = taxRate;
	}

	@Column(name = "published", nullable = false, length = 1)
	public char getPublished() {
		return this.published;
	}

	public void setPublished(char published) {
		this.published = published;
	}

	@Column(name = "rec_update_by", nullable = false, length = 20)
	public String getRecUpdateBy() {
		return this.recUpdateBy;
	}

	public void setRecUpdateBy(String recUpdateBy) {
		this.recUpdateBy = recUpdateBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "rec_update_datetime", nullable = false)
	public Date getRecUpdateDatetime() {
		return this.recUpdateDatetime;
	}

	public void setRecUpdateDatetime(Date recUpdateDatetime) {
		this.recUpdateDatetime = recUpdateDatetime;
	}

	@Column(name = "rec_create_by", nullable = false, length = 20)
	public String getRecCreateBy() {
		return this.recCreateBy;
	}

	public void setRecCreateBy(String recCreateBy) {
		this.recCreateBy = recCreateBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "rec_create_datetime", nullable = false)
	public Date getRecCreateDatetime() {
		return this.recCreateDatetime;
	}

	public void setRecCreateDatetime(Date recCreateDatetime) {
		this.recCreateDatetime = recCreateDatetime;
	}

	@Column(name = "site_id", nullable = false, insertable = false, updatable = false, length = 20)
	public String getSiteId() {
		return this.siteId;
	}

	public void setSiteId(String siteId) {
		this.siteId = siteId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "tax_lang_id", nullable = false)
	public TaxLanguage getTaxLanguage() {
		return this.taxLanguage;
	}

	public void setTaxLanguage(TaxLanguage taxLanguage) {
		this.taxLanguage = taxLanguage;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "tax_country", joinColumns = { @JoinColumn(name = "tax_id", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "country_id", nullable = false, updatable = false) })
	public Set<Country> getCountries() {
		return this.countries;
	}

	public void setCountries(Set<Country> countries) {
		this.countries = countries;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "tax_state", joinColumns = { @JoinColumn(name = "tax_id", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "state_id", nullable = false, updatable = false) })
	public Set<State> getStates() {
		return this.states;
	}

	public void setStates(Set<State> states) {
		this.states = states;
	}

	@OneToMany(fetch = FetchType.LAZY)
	@JoinColumn(name = "tax_id", updatable = false)
	public Set<TaxLanguage> getTaxLanguages() {
		return this.taxLanguages;
	}

	public void setTaxLanguages(Set<TaxLanguage> taxLanguages) {
		this.taxLanguages = taxLanguages;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "site_id", nullable = false)
	public Site getSite() {
		return this.site;
	}

	public void setSite(Site site) {
		this.site = site;
	}

}
