/*
 * Copyright 2007-2010 JadaSite.

 * This file is part of JadaSite.
 
 * JadaSite is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.

 * JadaSite is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.

 * You should have received a copy of the GNU General Public License
 * along with JadaSite.  If not, see <http://www.gnu.org/licenses/>.
 */

package com.jada.jpa.entity;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OrderBy;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TaxRegionProduct generated by hbm2java
 */
@Entity
@Table(name = "tax_region_product")
public class TaxRegionProduct implements java.io.Serializable {

	private static final long serialVersionUID = 2997954665776004731L;
	private Long taxRegionProductId;
	private String recUpdateBy;
	private Date recUpdateDatetime;
	private String recCreateBy;
	private Date recCreateDatetime;
	private ProductClass productClass;
	private TaxRegion taxRegion;
	private Set<TaxRegionProductCust> customerClasses = new HashSet<TaxRegionProductCust>(
			0);

	public TaxRegionProduct() {
	}

	public TaxRegionProduct(String recUpdateBy, Date recUpdateDatetime,
			String recCreateBy, Date recCreateDatetime) {
		this.recUpdateBy = recUpdateBy;
		this.recUpdateDatetime = recUpdateDatetime;
		this.recCreateBy = recCreateBy;
		this.recCreateDatetime = recCreateDatetime;
	}

	public TaxRegionProduct(String recUpdateBy, Date recUpdateDatetime,
			String recCreateBy, Date recCreateDatetime,
			ProductClass productClass, TaxRegion taxRegion,
			Set<TaxRegionProductCust> customerClasses) {
		this.recUpdateBy = recUpdateBy;
		this.recUpdateDatetime = recUpdateDatetime;
		this.recCreateBy = recCreateBy;
		this.recCreateDatetime = recCreateDatetime;
		this.productClass = productClass;
		this.taxRegion = taxRegion;
		this.customerClasses = customerClasses;
	}

	@Id
	@GeneratedValue
	@Column(name = "tax_region_product_id", nullable = false)
	public Long getTaxRegionProductId() {
		return this.taxRegionProductId;
	}

	public void setTaxRegionProductId(Long taxRegionProductId) {
		this.taxRegionProductId = taxRegionProductId;
	}

	@Column(name = "rec_update_by", nullable = false, length = 20)
	public String getRecUpdateBy() {
		return this.recUpdateBy;
	}

	public void setRecUpdateBy(String recUpdateBy) {
		this.recUpdateBy = recUpdateBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "rec_update_datetime", nullable = false)
	public Date getRecUpdateDatetime() {
		return this.recUpdateDatetime;
	}

	public void setRecUpdateDatetime(Date recUpdateDatetime) {
		this.recUpdateDatetime = recUpdateDatetime;
	}

	@Column(name = "rec_create_by", nullable = false, length = 20)
	public String getRecCreateBy() {
		return this.recCreateBy;
	}

	public void setRecCreateBy(String recCreateBy) {
		this.recCreateBy = recCreateBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "rec_create_datetime", nullable = false)
	public Date getRecCreateDatetime() {
		return this.recCreateDatetime;
	}

	public void setRecCreateDatetime(Date recCreateDatetime) {
		this.recCreateDatetime = recCreateDatetime;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "product_class_id")
	public ProductClass getProductClass() {
		return this.productClass;
	}

	public void setProductClass(ProductClass productClass) {
		this.productClass = productClass;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "tax_region_id")
	public TaxRegion getTaxRegion() {
		return this.taxRegion;
	}

	public void setTaxRegion(TaxRegion taxRegion) {
		this.taxRegion = taxRegion;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.EAGER)
	@OrderBy(value="taxRegionProductCustId")
	@JoinColumn(name = "tax_region_product_id", updatable = false)
	public Set<TaxRegionProductCust> getCustomerClasses() {
		return this.customerClasses;
	}

	public void setCustomerClasses(Set<TaxRegionProductCust> customerClasses) {
		this.customerClasses = customerClasses;
	}

}
