/*
 * Copyright 2007-2010 JadaSite.

 * This file is part of JadaSite.
 
 * JadaSite is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.

 * JadaSite is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.

 * You should have received a copy of the GNU General Public License
 * along with JadaSite.  If not, see <http://www.gnu.org/licenses/>.
 */

package com.jada.jpa.entity;

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TaxRegionZip generated by hbm2java
 */
@Entity
@Table(name = "tax_region_zip")
public class TaxRegionZip implements java.io.Serializable {

	private static final long serialVersionUID = 8205416424519988490L;
	private Long taxRegionZipId;
	private String zipCodeStart;
	private String zipCodeEnd;
	private String recUpdateBy;
	private Date recUpdateDatetime;
	private String recCreateBy;
	private Date recCreateDatetime;
	private TaxRegion taxRegion;

	public TaxRegionZip() {
	}

	public TaxRegionZip(String zipCodeStart, String zipCodeEnd,
			String recUpdateBy, Date recUpdateDatetime, String recCreateBy,
			Date recCreateDatetime) {
		this.zipCodeStart = zipCodeStart;
		this.zipCodeEnd = zipCodeEnd;
		this.recUpdateBy = recUpdateBy;
		this.recUpdateDatetime = recUpdateDatetime;
		this.recCreateBy = recCreateBy;
		this.recCreateDatetime = recCreateDatetime;
	}

	public TaxRegionZip(String zipCodeStart, String zipCodeEnd,
			String recUpdateBy, Date recUpdateDatetime, String recCreateBy,
			Date recCreateDatetime, TaxRegion taxRegion) {
		this.zipCodeStart = zipCodeStart;
		this.zipCodeEnd = zipCodeEnd;
		this.recUpdateBy = recUpdateBy;
		this.recUpdateDatetime = recUpdateDatetime;
		this.recCreateBy = recCreateBy;
		this.recCreateDatetime = recCreateDatetime;
		this.taxRegion = taxRegion;
	}

	@Id
	@GeneratedValue
	@Column(name = "tax_region_zip_id", nullable = false)
	public Long getTaxRegionZipId() {
		return this.taxRegionZipId;
	}

	public void setTaxRegionZipId(Long taxRegionZipId) {
		this.taxRegionZipId = taxRegionZipId;
	}

	@Column(name = "zip_code_start", nullable = false, length = 10)
	public String getZipCodeStart() {
		return this.zipCodeStart;
	}

	public void setZipCodeStart(String zipCodeStart) {
		this.zipCodeStart = zipCodeStart;
	}

	@Column(name = "zip_code_end", nullable = false, length = 10)
	public String getZipCodeEnd() {
		return this.zipCodeEnd;
	}

	public void setZipCodeEnd(String zipCodeEnd) {
		this.zipCodeEnd = zipCodeEnd;
	}

	@Column(name = "rec_update_by", nullable = false, length = 20)
	public String getRecUpdateBy() {
		return this.recUpdateBy;
	}

	public void setRecUpdateBy(String recUpdateBy) {
		this.recUpdateBy = recUpdateBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "rec_update_datetime", nullable = false)
	public Date getRecUpdateDatetime() {
		return this.recUpdateDatetime;
	}

	public void setRecUpdateDatetime(Date recUpdateDatetime) {
		this.recUpdateDatetime = recUpdateDatetime;
	}

	@Column(name = "rec_create_by", nullable = false, length = 20)
	public String getRecCreateBy() {
		return this.recCreateBy;
	}

	public void setRecCreateBy(String recCreateBy) {
		this.recCreateBy = recCreateBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "rec_create_datetime", nullable = false)
	public Date getRecCreateDatetime() {
		return this.recCreateDatetime;
	}

	public void setRecCreateDatetime(Date recCreateDatetime) {
		this.recCreateDatetime = recCreateDatetime;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "tax_region_id")
	public TaxRegion getTaxRegion() {
		return this.taxRegion;
	}

	public void setTaxRegion(TaxRegion taxRegion) {
		this.taxRegion = taxRegion;
	}

}
