/*
 * Copyright 2007-2010 JadaSite.

 * This file is part of JadaSite.
 
 * JadaSite is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.

 * JadaSite is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.

 * You should have received a copy of the GNU General Public License
 * along with JadaSite.  If not, see <http://www.gnu.org/licenses/>.
 */

package com.jada.jpa.entity;

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Transaction generated by hbm2java
 */
@Entity
@Table(name = "transaction")
public class Transaction implements java.io.Serializable {

	private static final long serialVersionUID = -8350432139623047784L;
	private Long tranId;
	private Date tranDatetime;
	private Integer tranQty;
	private String tranType;
	private String tranReference;
	private String tranRemarks;
	private String recUpdateBy;
	private Date recUpdateDatetime;
	private String recCreateBy;
	private Date recCreateDatetime;
	private String siteId;
	private Item item;
	private Site site;

	public Transaction() {
	}

	public Transaction(Date tranDatetime, Integer tranQty, String tranType,
			String tranReference, String tranRemarks, String recUpdateBy,
			Date recUpdateDatetime, String recCreateBy, Date recCreateDatetime,
			String siteId, Site site) {
		this.tranDatetime = tranDatetime;
		this.tranQty = tranQty;
		this.tranType = tranType;
		this.tranReference = tranReference;
		this.tranRemarks = tranRemarks;
		this.recUpdateBy = recUpdateBy;
		this.recUpdateDatetime = recUpdateDatetime;
		this.recCreateBy = recCreateBy;
		this.recCreateDatetime = recCreateDatetime;
		this.siteId = siteId;
		this.site = site;
	}

	public Transaction(Date tranDatetime, Integer tranQty, String tranType,
			String tranReference, String tranRemarks, String recUpdateBy,
			Date recUpdateDatetime, String recCreateBy, Date recCreateDatetime,
			String siteId, Item item, Site site) {
		this.tranDatetime = tranDatetime;
		this.tranQty = tranQty;
		this.tranType = tranType;
		this.tranReference = tranReference;
		this.tranRemarks = tranRemarks;
		this.recUpdateBy = recUpdateBy;
		this.recUpdateDatetime = recUpdateDatetime;
		this.recCreateBy = recCreateBy;
		this.recCreateDatetime = recCreateDatetime;
		this.siteId = siteId;
		this.item = item;
		this.site = site;
	}

	@Id
	@GeneratedValue
	@Column(name = "tran_id", nullable = false)
	public Long getTranId() {
		return this.tranId;
	}

	public void setTranId(Long tranId) {
		this.tranId = tranId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "tran_datetime", nullable = false)
	public Date getTranDatetime() {
		return this.tranDatetime;
	}

	public void setTranDatetime(Date tranDatetime) {
		this.tranDatetime = tranDatetime;
	}

	@Column(name = "tran_qty", nullable = false)
	public Integer getTranQty() {
		return this.tranQty;
	}

	public void setTranQty(Integer tranQty) {
		this.tranQty = tranQty;
	}

	@Column(name = "tran_type", nullable = false, length = 1)
	public String getTranType() {
		return this.tranType;
	}

	public void setTranType(String tranType) {
		this.tranType = tranType;
	}

	@Column(name = "tran_reference", nullable = false, length = 20)
	public String getTranReference() {
		return this.tranReference;
	}

	public void setTranReference(String tranReference) {
		this.tranReference = tranReference;
	}

	@Column(name = "tran_remarks", nullable = false, length = 255)
	public String getTranRemarks() {
		return this.tranRemarks;
	}

	public void setTranRemarks(String tranRemarks) {
		this.tranRemarks = tranRemarks;
	}

	@Column(name = "rec_update_by", nullable = false, length = 20)
	public String getRecUpdateBy() {
		return this.recUpdateBy;
	}

	public void setRecUpdateBy(String recUpdateBy) {
		this.recUpdateBy = recUpdateBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "rec_update_datetime", nullable = false)
	public Date getRecUpdateDatetime() {
		return this.recUpdateDatetime;
	}

	public void setRecUpdateDatetime(Date recUpdateDatetime) {
		this.recUpdateDatetime = recUpdateDatetime;
	}

	@Column(name = "rec_create_by", nullable = false, length = 20)
	public String getRecCreateBy() {
		return this.recCreateBy;
	}

	public void setRecCreateBy(String recCreateBy) {
		this.recCreateBy = recCreateBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "rec_create_datetime", nullable = false)
	public Date getRecCreateDatetime() {
		return this.recCreateDatetime;
	}

	public void setRecCreateDatetime(Date recCreateDatetime) {
		this.recCreateDatetime = recCreateDatetime;
	}

	@Column(name = "site_id", nullable = false, insertable = false, updatable = false, length = 20)
	public String getSiteId() {
		return this.siteId;
	}

	public void setSiteId(String siteId) {
		this.siteId = siteId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "item_id")
	public Item getItem() {
		return this.item;
	}

	public void setItem(Item item) {
		this.item = item;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "site_id", nullable = false)
	public Site getSite() {
		return this.site;
	}

	public void setSite(Site site) {
		this.site = site;
	}

}
