/*
 * Copyright 2007-2010 JadaSite.

 * This file is part of JadaSite.
 
 * JadaSite is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.

 * JadaSite is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.

 * You should have received a copy of the GNU General Public License
 * along with JadaSite.  If not, see <http://www.gnu.org/licenses/>.
 */

package com.jada.jpa.entity;

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * VoidOrder generated by hbm2java
 */
@Entity
@Table(name = "void_order")
public class VoidOrder implements java.io.Serializable {

	private static final long serialVersionUID = 7560600266097117195L;
	private Long voidOrderId;
	private String voidOrderNum;
	private Date voidOrderDatetime;
	private String recUpdateBy;
	private Date recUpdateDatetime;
	private String recCreateBy;
	private Date recCreateDatetime;
	private PaymentTran paymentTran;

	public VoidOrder() {
	}

	public VoidOrder(String voidOrderNum, Date voidOrderDatetime,
			String recUpdateBy, Date recUpdateDatetime, String recCreateBy,
			Date recCreateDatetime) {
		this.voidOrderNum = voidOrderNum;
		this.voidOrderDatetime = voidOrderDatetime;
		this.recUpdateBy = recUpdateBy;
		this.recUpdateDatetime = recUpdateDatetime;
		this.recCreateBy = recCreateBy;
		this.recCreateDatetime = recCreateDatetime;
	}

	public VoidOrder(String voidOrderNum, Date voidOrderDatetime,
			String recUpdateBy, Date recUpdateDatetime, String recCreateBy,
			Date recCreateDatetime, PaymentTran paymentTran) {
		this.voidOrderNum = voidOrderNum;
		this.voidOrderDatetime = voidOrderDatetime;
		this.recUpdateBy = recUpdateBy;
		this.recUpdateDatetime = recUpdateDatetime;
		this.recCreateBy = recCreateBy;
		this.recCreateDatetime = recCreateDatetime;
		this.paymentTran = paymentTran;
	}

	@Id
	@GeneratedValue
	@Column(name = "void_order_id", nullable = false)
	public Long getVoidOrderId() {
		return this.voidOrderId;
	}

	public void setVoidOrderId(Long voidOrderId) {
		this.voidOrderId = voidOrderId;
	}

	@Column(name = "void_order_num", nullable = false, length = 20)
	public String getVoidOrderNum() {
		return this.voidOrderNum;
	}

	public void setVoidOrderNum(String voidOrderNum) {
		this.voidOrderNum = voidOrderNum;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "void_order_datetime", nullable = false)
	public Date getVoidOrderDatetime() {
		return this.voidOrderDatetime;
	}

	public void setVoidOrderDatetime(Date voidOrderDatetime) {
		this.voidOrderDatetime = voidOrderDatetime;
	}

	@Column(name = "rec_update_by", nullable = false, length = 20)
	public String getRecUpdateBy() {
		return this.recUpdateBy;
	}

	public void setRecUpdateBy(String recUpdateBy) {
		this.recUpdateBy = recUpdateBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "rec_update_datetime", nullable = false)
	public Date getRecUpdateDatetime() {
		return this.recUpdateDatetime;
	}

	public void setRecUpdateDatetime(Date recUpdateDatetime) {
		this.recUpdateDatetime = recUpdateDatetime;
	}

	@Column(name = "rec_create_by", nullable = false, length = 20)
	public String getRecCreateBy() {
		return this.recCreateBy;
	}

	public void setRecCreateBy(String recCreateBy) {
		this.recCreateBy = recCreateBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "rec_create_datetime", nullable = false)
	public Date getRecCreateDatetime() {
		return this.recCreateDatetime;
	}

	public void setRecCreateDatetime(Date recCreateDatetime) {
		this.recCreateDatetime = recCreateDatetime;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "payment_tran_id")
	public PaymentTran getPaymentTran() {
		return this.paymentTran;
	}

	public void setPaymentTran(PaymentTran paymentTran) {
		this.paymentTran = paymentTran;
	}

}
