java -jar D:\work\JavaContent\others\tango-icon-theme-0.7.1\batik-1.6\batik-rasterizer.jar -m image/jpeg -d d:\work\JavaContent\others\tango-icon-theme-0.7.1\output-32x32\actions -w 32 -h 32 D:\work\JavaContent\others\tango-icon-theme-0.7.1\scalable\actions
java -jar D:\work\JavaContent\others\tango-icon-theme-0.7.1\batik-1.6\batik-rasterizer.jar -m image/jpeg -d d:\work\JavaContent\others\tango-icon-theme-0.7.1\output-32x32\animations -w 32 -h 32 D:\work\JavaContent\others\tango-icon-theme-0.7.1\scalable\animations
java -jar D:\work\JavaContent\others\tango-icon-theme-0.7.1\batik-1.6\batik-rasterizer.jar -m image/jpeg -d d:\work\JavaContent\others\tango-icon-theme-0.7.1\output-32x32\apps -w 32 -h 32 D:\work\JavaContent\others\tango-icon-theme-0.7.1\scalable\apps
java -jar D:\work\JavaContent\others\tango-icon-theme-0.7.1\batik-1.6\batik-rasterizer.jar -m image/jpeg -d d:\work\JavaContent\others\tango-icon-theme-0.7.1\output-32x32\categories -w 32 -h 32 D:\work\JavaContent\others\tango-icon-theme-0.7.1\scalable\categories
java -jar D:\work\JavaContent\others\tango-icon-theme-0.7.1\batik-1.6\batik-rasterizer.jar -m image/jpeg -d d:\work\JavaContent\others\tango-icon-theme-0.7.1\output-32x32\devices -w 32 -h 32 D:\work\JavaContent\others\tango-icon-theme-0.7.1\scalable\devices
java -jar D:\work\JavaContent\others\tango-icon-theme-0.7.1\batik-1.6\batik-rasterizer.jar -m image/jpeg -d d:\work\JavaContent\others\tango-icon-theme-0.7.1\output-32x32\emblems -w 32 -h 32 D:\work\JavaContent\others\tango-icon-theme-0.7.1\scalable\emblems
java -jar D:\work\JavaContent\others\tango-icon-theme-0.7.1\batik-1.6\batik-rasterizer.jar -m image/jpeg -d d:\work\JavaContent\others\tango-icon-theme-0.7.1\output-32x32\emotes -w 32 -h 32 D:\work\JavaContent\others\tango-icon-theme-0.7.1\scalable\emotes
java -jar D:\work\JavaContent\others\tango-icon-theme-0.7.1\batik-1.6\batik-rasterizer.jar -m image/jpeg -d d:\work\JavaContent\others\tango-icon-theme-0.7.1\output-32x32\mimetypes -w 32 -h 32 D:\work\JavaContent\others\tango-icon-theme-0.7.1\scalable\mimetypes
java -jar D:\work\JavaContent\others\tango-icon-theme-0.7.1\batik-1.6\batik-rasterizer.jar -m image/jpeg -d d:\work\JavaContent\others\tango-icon-theme-0.7.1\output-32x32\places -w 32 -h 32 D:\work\JavaContent\others\tango-icon-theme-0.7.1\scalable\places
java -jar D:\work\JavaContent\others\tango-icon-theme-0.7.1\batik-1.6\batik-rasterizer.jar -m image/jpeg -d d:\work\JavaContent\others\tango-icon-theme-0.7.1\output-32x32\status -w 32 -h 32 D:\work\JavaContent\others\tango-icon-theme-0.7.1\scalable\status

